### ISSUE TITLE
How to install python packages with pip

### ISSUE THREAD

**Issue by keyingliu** [ostreedev/ostree#1003]
```
ostree --version
libostree:
 Version: 2017.5
 Git: 11d26191eeb3b8cd34c2ad06ee3cc5dd9a0e3924
 Features:
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - libmount
```

OS: `CentOS Linux release 7.3.1611`

My ostree is for centos, and I would like to install some python packages with pip, I tried to have the packages installed in `postprocess-script`, but from the document, I was told there is no network access, I'm trying to download the python packages, and add them in `add-files`, but the files are added after post process.

Can you please let me know if there are any other ways to install python packages with pip during ostree compose?
Thanks.

**Comment by cgwalters** [comment]
This looks like an rpm-ostree issue; closing in favor of https://github.com/projectatomic/rpm-ostree/issues/874
