### ISSUE TITLE
RFE: don't hard error if localcache repo is bogus

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1005]
In https://github.com/ostreedev/ostree/pull/982 we added support from checking a local repo cache for information when pulling from a remote. If that localcache ends up being bogus for some reason it would be nice if we don't end up erroring out, but rather give a warning or some other indicator, since the localcache is really only an optimization.

**Comment by dustymabe** [comment]
reference to where we were getting errors in Fedora: https://pagure.io/atomic-wg/issue/301

**Comment by cgwalters** [comment]
No; callers should avoid passing invalid repos.

**Comment by dustymabe** [comment]
That's fair, just wanted to propose it. Also, might be hard for a caller to 'validate' if a repo is good or not.
