### ISSUE TITLE
grub2-mkconfig when invoked directly generates bad config on EFI

### ISSUE THREAD

**Issue by cmurf** [ostreedev/ostree#1009]
I'm still running into this with Fedora-Workstation-ostree-x86_64-Rawhide-20170714.n.0.iso
atomic-1.18.1-4.fc27.x86_64
ostree-2017.8-2.fc27.x86_64
rpm-ostree-2017.7-1.fc27.x86_64

[chris@frawhide ~]$ sudo ostree admin instutil grub2-generate -v 0
OT: Deployment 6dc795302af832537ad225050a00441726350937f4f9b218b01f5e885c0e1619.0 unlocked=0
**
OSTree:ERROR:src/libostree/ostree-bootloader-grub2.c:167:_ostree_bootloader_grub2_generate_config: assertion failed: (grub2_boot_device_id != NULL)
Aborted
[chris@frawhide ~]$ sudo ostree admin instutil grub2-generate -v 1
OT: Deployment 6dc795302af832537ad225050a00441726350937f4f9b218b01f5e885c0e1619.0 unlocked=0
**
OSTree:ERROR:src/libostree/ostree-bootloader-grub2.c:167:_ostree_bootloader_grub2_generate_config: assertion failed: (grub2_boot_device_id != NULL)
Aborted
[chris@frawhide ~]$

Recalling 
https://bugzilla.redhat.com/show_bug.cgi?id=1293986
https://github.com/ostreedev/ostree/pull/165

This command isn't really supposed to be user servicable, but on Workstation there needs to be a way to regenerate the grub.cfg. When I run grub2-mkconfig it does not pick up items in /etc/default/grub and it also uses linux16 and initrd16 commands, instead of linuxefi/initrdefi as appropriate for this UEFI installation.

**Comment by cgwalters** [comment]
See also https://github.com/projectatomic/rpm-ostree/issues/594

**Comment by cmurf** [comment]
https://github.com/projectatomic/rpm-ostree/issues/594 says on EFI do:
`grub2-mkconfig > /boot/efi/EFI/fedora/grub.cfg.new && mv /boot/efi/EFI/fedora/grub.cfg{.new,}`

But this creates a grub.cfg with linux16/initrd16 commands which is incorrect. I don't know why the original grub.cfg came out correct during install, but post-install it results in invalid grub commands.

**Comment by cgwalters** [comment]
Yep, confirmed that bug.  Hmm.  Man this code sucks :cry:

**Comment by cgwalters** [comment]
See also https://github.com/ostreedev/ostree/issues/717

**Comment by vtolstov** [comment]
any news about  efi bugs ?

**Comment by mildred** [comment]
Second time I install silverblue, and second time anaconda cannot install the bootloader (I suspect due to btrfs).

In order to regenerate the GRUB config with EFI enabled, you can just set `_OSTREE_GRUB2_IS_EFI=1`. Implementation is here: https://github.com/ostreedev/ostree/blob/d69214ade3d5b187ebfbb791d7cfb36155c4f8dd/src/libostree/ostree-bootloader-grub2.c#L176

For example:

    _OSTREE_GRUB2_IS_EFI=1 grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg

Assuming you manually booted the system once.

**Comment by vtolstov** [comment]
@cgwalters any chance to get this fixed?

**Comment by bam80** [comment]
ping
