### ISSUE TITLE
Assert in curl callback makes gnome-software crash on rawhide

### ISSUE THREAD

**Issue by hughsie** [ostreedev/ostree#1035]
We're debugging Andreas Nilsson's rawhide laptop here and he's running into a gnome-software crash in ostree-fetcher-curl.c in event_cb. Looks like there's an assert in curl networking code callback that curl returns OK; this is clearly not the case here.

`rc = curl_multi_socket_action ()`
`g_assert (rc = CURLM_OK)`

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1038

**Comment by cgwalters** [comment]
Was this debugged to any root cause?  e.g. incorrect proxy settings, connection being interrupted, DNS resolution failure, etc?

**Comment by kalev** [comment]
No, we didn't debug it further, but a number of ports are blocked here on the network. Could that be the cause?

Thanks for the quick fix!
