### ISSUE TITLE
Documentation: ostree-pull man page sentence is missing an end

### ISSUE THREAD

**Issue by guyshapiro** [ostreedev/ostree#1043]
In the ostree-pull man page, in the Description section, the second paragraph ends in "This ".
See it on [Line 140 in ostree-pull.xml](https://github.com/ostreedev/ostree/blob/master/man/ostree-pull.xml#L140).

Looks like it was committed in the middle of the writing.

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1045
