### ISSUE TITLE
Return more detailed error codes from ostree_repo_remote_fetch_summary()

### ISSUE THREAD

**Issue by pwithnall** [ostreedev/ostree#1064]
https://github.com/flatpak/flatpak/issues/917#issuecomment-320705726 requires flatpak to differentiate between failures due to missing network connectivity (which we want to treat as OK), and failures due to invalid signatures (which are bad and the user should feel bad).

⇒ `ostree_repo_remote_fetch_summary()` needs to return more error codes than just `G_IO_ERROR_FAILED`, but how do we do that without breaking API? Or do we not care about the API for error codes unless they are already explicitly documented?

**Comment by pwithnall** [comment]
This is related to https://github.com/ostreedev/ostree/issues/1061, the solution to which will either involve adding and returning an error code for 404s, or returning `TRUE` and a `NULL` summary for them.

**Comment by cgwalters** [comment]
If it's just starting to return `G_IO_ERROR_NOT_FOUND` for 404s that seems fully compatible to me.

**Comment by pwithnall** [comment]
> If it's just starting to return `G_IO_ERROR_NOT_FOUND` for 404s that seems fully compatible to me.

The solution for #1061 is to return `TRUE` and `NULL`, so the error handling doesn’t actually come into it there.

Regarding GPG signature checking, I can’t see an immediately relevant error code in `G_IO_ERROR` which we could use for it. What are your thoughts about adding a new error domain specifically for signing/verification errors? It would have to be (potentially) returned by a lot of the libostree API, so would be a fairly big API break, iff we care about error codes changing.

**Comment by cgwalters** [comment]
I don't see an issue with adding a new error domain offhand.  Why would someone catch `G_IO_ERROR_FAILED` versus just a blanket catch?  It's only once we have a custom error enum that adding to it becomes an ABI hazard, right?

**Comment by pwithnall** [comment]
> Why would someone catch `G_IO_ERROR_FAILED` versus just a blanket catch?

I often ask that kind of question before making small API breaks, then someone comes and punches me in the face for breaking the one thing they depended on.

I’m happy with adding a new error domain though. I’ll take a look at doing so tomorrow.

**Comment by pwithnall** [comment]
I’ve got a local patch to add this, which modifies a load of error sites. Unfortunately, one of the sites I’d like to modify, `_ostree_repo_gpg_verify_with_metadata()`, is currently emitting `G_IO_ERROR_NOT_FOUND` for a missing signature, and changing that breaks a number of the unit tests — apparently other code in libostree is detecting that error and squashing it at times. I’ll see what I can do to fix consumption of that.
