### ISSUE TITLE
maint.mk injects LC_ALL=C which is not neccessarily UTF-8 

### ISSUE THREAD

**Issue by heftig** [ostreedev/ostree#1101]
```
  DOC   Building XML
./ostree-decl.txt:1209: warning: OstreeRemote has multiple definitions.
./ostree-decl.txt:3064: warning: OstreeRemote has multiple definitions.
../src/libostree/ostree-bloom.c:75: warning: Section bloom is not defined in the ostree-sections.txt file.
../src/libostree/ostree-remote.c:53: warning: Section remote is not defined in the ostree-sections.txt file.
../src/libostree/ostree-repo-finder-avahi.c:101: warning: Section ostree-repo-finder-avahi is not defined in the ostree-sections.txt file.
../src/libostree/ostree-repo-finder-config.c:58: warning: Section ostree-repo-finder-config is not defined in the ostree-sections.txt file.
../src/libostree/ostree-repo-finder-mount.c:68: warning: Section ostree-repo-finder-mount is not defined in the ostree-sections.txt file.
../src/libostree/ostree-soup-form.c:28: warning: Section soup-form is not defined in the ostree-sections.txt file.
../src/libostree/ostree-soup-uri.c:125: warning: Section soup-uri is not defined in the ostree-sections.txt file.
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-mkdb", line 61, in <module>
    mkdb.Run(options)
  File "/usr/share/gtk-doc/python/gtkdoc/mkdb.py", line 284, in Run
    changed, book_top, book_bottom = OutputDB(os.path.join(ROOT_DIR, MODULE + "-sections.txt"), options)
  File "/usr/share/gtk-doc/python/gtkdoc/mkdb.py", line 671, in OutputDB
    file_objects)
  File "/usr/share/gtk-doc/python/gtkdoc/mkdb.py", line 2203, in OutputDBFile
    'MODULE': MODULE.upper(),
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 12932: ordinal not in range(128)
make[2]: *** [Makefile:821: sgml-build.stamp] Error 1
make[2]: Leaving directory '/build/ostree/src/ostree/apidoc'
```

`src/libostree/ostree-async-progress.c` contains two annotations with an ellipsis (`…`).
The error vanishes after replacing `LC_ALL = C` in `maint.mk` with `LC_ALL = en_US.utf8`.

ostree v2017.10
gtk-doc master (01844e7)
Arch Linux x86_64

**Comment by cgwalters** [comment]
Yeah, and a lot of build systems hardcode the `C` locale.  But really I think it's quite reasonable to interpret this to mean `C.UTF-8` which I believe glibc now interprets.  So this is really a Python bug...I've seen references to this before.

**Comment by heftig** [comment]
glibc 2.26 here still doesn't recognize `C.UTF-8`, so it seem this locale remains non-standard.

**Comment by cgwalters** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=902094

**Comment by cgwalters** [comment]
FWIW the transition to Python for some tools also had side effects elsewhere; I also did these for Fedora recently:

https://git.gnome.org/browse/libgnome/commit/?id=33313713c4f5c1de500859ff128d6fd7e3af5722
https://git.gnome.org/browse/libgnomeui/commit/?id=30334c28794ef85d8973f4ed0779b5ceed6594f2

**Comment by cgwalters** [comment]
Just to follow up on this, if you (or someone) submits a patch to remove non-ASCII from the docs that you've tested, I'd probably apply it.  But while I do take a pretty hard line on regressions, and try to be conservative about build systems...not supporting UTF-8 in the build environment is something people are just going to have to fix at some point.

**Comment by heftig** [comment]
> not supporting UTF-8 in the build environment is something people are just going to have to fix at some point.

To be clear, if it wasn't for ostree's `maint.mk` enforcing `LANG=C`, ostree would build fine here, since our build environment has `LANG=en_US.utf8`.

**Comment by cgwalters** [comment]
Oh wow, yes that's totally our fault.

**Comment by cgwalters** [comment]
AFAICS that line is still in upstream gnulib, where this file was copied from originally.  Hmm.  I guess that's not biting elsewhere since they're not using Python programs executed out of their makefiles?  Or maybe if they do those Python programs go out of their way to enable UTF-8?

**Comment by heftig** [comment]
I guess everybody else is using Python 2, which doesn't care about encoding. GTK-Doc 1.26 didn't even work correctly with Py3 on release and needed further patches (which are on master).

Even GTK-Doc master is still using the naive approach to opening files which decodes/encodes using the system locale. If `LC_CTYPE` is `C` or unset, Python 3 will choke on anything non-ASCII. In the error above, it seems the files were correctly decoded as UTF-8 but writing the database file fails, since the output encoding is still ASCII.

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1107 

@heftig see https://github.com/projectatomic/papr#more-details-about-project-atomic-ci-services for how to approve the patch for merging
