### ISSUE TITLE
copying content between two repos of different types

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1117]
I believe I have seen issues (or been told it doesn't work) in the past where pull operations from a repo of one content type (bare, vs archive) is not allowed. I have been trying to copy around some data and having some issues, I think this is related to my source repo being a bare repo and my target repo being an archive repo.

My first question is: "Is there an issue pulling from mixed content repos?" 

My 2nd question is: For operations like `pull-local` and `pull --localcache-repo` can we cleanly give a message to the user to indicate issues if they are trying to do this?

**Comment by jlebon** [comment]
> My first question is: "Is there an issue pulling from mixed content repos?"

`ostree pull` only supports archive remote repos. `ostree pull-local` should work with all content types.

> My 2nd question is: For operations like `pull-local` and `pull --localcache-repo` can we cleanly give a message to the user to indicate issues if they are trying to do this?

Hmm, those should just work with any content type, I'd think. Have you seen differently?

**Comment by cgwalters** [comment]
The docs also mention converting between `archive` and `bare-user` at least: https://ostree.readthedocs.io/en/latest/manual/buildsystem-and-repos/

**Comment by dustymabe** [comment]
ok so it should work fine for `pull-local`. 

For `pull` (and in the case of what I was doing: `pull --localcache`) we can't copy between two repos of different content types. Can we add a helpful error message for this case?

**Comment by cgwalters** [comment]
Can you clarify exactly what command you were running and what the error message was?

**Comment by cgwalters** [comment]
I did an `ostree pull -L /srv/host/ostree/repo remotename ref` (in a container, where `/srv/host/ostree/` is a ro-bind mount from my host's `bare` repo) and things worked fine.   Our unit tests cover this too.

**Comment by dustymabe** [comment]
i had copied some files out of an atomic host VM onto my desktop and then tried to do a pull with `--localcache`. I did an rsync of `/ostree/repo/` and then tried to use that. Is there something flawed with that approach?

**Comment by jlebon** [comment]
Hmm, that should be fine. What was the error message?

**Comment by dustymabe** [comment]
:) - that was long ago. I just thought it was something that was flat out unsupported so I didn't even include the error message. I'll close this and open a new issue if I see it again.
