### ISSUE TITLE
Is there a way to run "rpm-ostree install $pkg" for non-rpm-ostree composed repo?

### ISSUE THREAD

**Issue by isula-xufeng** [ostreedev/ostree#1128]
I know this is not a bug, I just want to know is there a way to install packages by rpm-ostree if the ostree
repo was not composed by rpm-ostree, instead it was generated by "ostree commit --tree=dir=$rootfs-dir"。

I think this should be caused by rpm-ostree Treefile default behavior, by default, selinux is enabled in rpm-ostree.

This is the error message:
[root@localhost ~]# rpm-ostree install git
.......
Importing: [=====================================================================================================================================] 100%
error: Failed to find metadata key rpmostree.sepolicy (signature s)

Thanks a lot!

**Comment by jlebon** [comment]
Let's close this one and discuss in https://github.com/projectatomic/rpm-ostree/issues/971.
