### ISSUE TITLE
Cannot use remotes_config_dir without sysroot

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#1133]
I have a repository manager that runs on a server and pulls from build machines into a set of central repos. In order to pull, ostree needs a remote. Rather than adding every possible remote to every repo (both cluttering the repo config file and leaking internal details), I use a remotes configuration directory. Commit e0346c1 broke this since now the `remotes-config-dir` property is only respected if the `sysroot-path` property is set. That's not set since these are not system repos.

**Comment by cgwalters** [comment]
Ah.  Hmm, makes sense I guess; I'd just seen the `remotes-config-dir` as part of the weird way we propagate bits from the sysroot to repo levels.

**Comment by dbnicholson** [comment]
Right. I would say the the remotes config dir is typically used in the system repo scope, but it was helpful to use for a normal repo.

Alternatively, if you could pull without specifying a remote, I'd use that. The way I use the remotes configuration directory right now is that I just populate a single fake remote without a URL and then always override the URL when pulling and fetching the summary. This allows me to pull from semi-arbitrary URLs without managing remote configuration.

**Comment by dbnicholson** [comment]
Also, `g_file_resolve_relative_path (self->sysroot_dir, self->remotes_config_dir);` is broken if `remotes_config_dir` is absolute and `sysroot_dir` is set (and you actually want to use the alternate sysroot).

**Comment by dbnicholson** [comment]
This also breaks flatpak's use of `remotes-config-dir` - https://github.com/flatpak/flatpak/blob/master/common/flatpak-dir.c#L762. That was actually the reason this was originally added for #247.

**Comment by cgwalters** [comment]
Ugh.  OK, I'll look at this.

**Comment by dbnicholson** [comment]
Hmm, if I fix this by making `remotes-config-dir` respected again, it will certainly break flatpak (which is how I ended up here in the first place). Before e0346c1, only reading the config would respect `remotes-config-dir`. Adding remotes would only use it for a system repo (and then it was hardcoded to /etc/ostree/remotes.d). After e0346c1, adding remotes respects `remotes-config-dir` but only for system repos.

If I fix `get_remotes_d_dir` to respect `remotes-config-dir`, then flatpak will start creating remotes in /etc/flatpak/remotes.d. That's a problem because what flatpak does to allow modifying remotes (since there's no ostree API to merge options with an existing remote) is to `ADD_IF_NOT_EXISTS` and then use `ostree_repo_write_config` to add new options. That ends up creating duplicate remote entries.

We ran into this because /var/lib/flatpak/repo is a symlink to /ostree/repo and now ostree uses `stat` to check if the repo is the same whereas it used to just look at the paths.

**Comment by dbnicholson** [comment]
I suppose I could just add back the check for `is_system_repo` in the remote add case to bring it roughly back to what it was before. That would fix flatpak and my repo manager uses, but we'd still be battling duplicate remotes for EOS. The latter is more the reason for #1134.

**Comment by cgwalters** [comment]
One sort of big picture thing here is the Endless case of "system ostree == flatpak ostree" is a lot less useful for SELinux-enabled systems like Fedora (even if the *host* is e.g. rpm-ostree) due to https://github.com/flatpak/flatpak/issues/927 and I'm not sure we'd want to enable it by default for non-ostree based OSes like Ubuntu either.  I think this bifurcation impacts both ostree and flatpak design badly in that I assume both me and @alexlarsson aren't considering it enough.

**Comment by dbnicholson** [comment]
Right. It's ended up causing a lot of issues for us. We have regular repo corruption (I've always assumed because flatpak and ostree are both operating on the repo concurrently). We've considered changing that going forwards (possibly making /ostree/repo a parent of /var/lib/flatpak/repo with whatever problems that could cause), but we still need to support existing installations.

**Comment by cgwalters** [comment]
It seems clear to that the fact that there's no API/cli for remote modification in ostree is a bug; this is a bit of a downside of flatpak wrapping ostree.

But...I'm not sure about trying to conflate adding that API with this issue.
