### ISSUE TITLE
lib/repo-finder-mount: Support /var/lib/flatpak

### ISSUE THREAD

**Issue by pwithnall** [ostreedev/ostree#1210]
See https://github.com/ostreedev/ostree/pull/1179#issuecomment-331489547. Add support for searching for `/var/lib/flatpak` and `/var/lib/containers/atomic` (@cgwalters is that correct?) on a mounted USB stick to `OstreeRepoFinderMount`. Ideally also add that to the unit tests.

**Comment by cgwalters** [comment]
This was fixed by https://github.com/ostreedev/ostree/commit/cd70aaac11c68888f56c753f8d1fda8a7895c75f
