### ISSUE TITLE
2017.11 does not compile without libarchive

### ISSUE THREAD

**Issue by jtojnar** [ostreedev/ostree#1232]
When `HAVE_LIBARCHIVE` is not defined, [this opening bracket](https://github.com/ostreedev/ostree/blob/v2017.11/src/ostree/ot-builtin-commit.c#L605) will not have a counterpart and the compilation will fail with the following error:

```
src/ostree/ot-builtin-commit.c: In function 'ostree_builtin_commit':
src/ostree/ot-builtin-commit.c:641:11: error: expected '}' before 'else'
           else if (strcmp (tree_type, "ref") == 0)
           ^~~~
```

**Comment by cgwalters** [comment]
Hi, thanks for the report. This is fixed in git master via https://github.com/ostreedev/ostree/pull/1181 and also https://github.com/ostreedev/ostree/pull/1194
