### ISSUE TITLE
Extending read-only state to /sysroot and /boot

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#1265]
Today ostree has a ro bind mount over `/usr`, but one can just do e.g. `rm -rf /sysroot/*` and the whole system is destroyed.

Similarly, we tried to have support for `/boot` as a ro mount but it needs work.

What we should do is have these be `ro` by default, and then have apps using libostree create a new mount namespace, and make manipulations there.  That way the system stays read-only to *everything else*.  Alternatively, we could teach libostree how to do that internally, but it'd get ugly fast...we'd need to fork off a subprocess basically.

For example `rpm-ostreed` and `eos-updater` could change their systemd unit files to create a new mount namespace, and tell libostree that one is set up.

(Conceptually this overlaps a ton with systemd's `ProtectSystem=strict`...we're basically imposing that on the whole system by default)

**Comment by cgwalters** [comment]
See also for `/tmp`:
https://pagure.io/fedora-atomic/pull-request/62
https://github.com/projectatomic/rpm-ostree/issues/820

**Comment by giuseppe** [comment]
would this be an issue for system containers that use `/ostree/deploy/$OS_NAME/$DEST_FILE` for creating hard links?

**Comment by cgwalters** [comment]
@giuseppe an important bit from the above is:

> ...and then have apps using libostree create a new mount namespace, and make manipulations there.

The goal here isn't to make things truly immutable, it's to prevent things like `restorecon -R /` from destroying the system.  And similar non-ostree-aware tools.

See also on-list discussion:

https://mail.gnome.org/archives/ostree-list/2017-December/msg00009.html

**Comment by giuseppe** [comment]
I see, thanks.  Could the new API allow also the current mount namespace to be used?  It will be the user responsibility to ensure a new mount namespace is created and `/sysroot` can be remounted as writeable (and back to ro if needed).

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1767

**Comment by cgwalters** [comment]
Requirements to implement this for Fedora CoreOS:

 https://github.com/coreos/fedora-coreos-config/pull/39
https://github.com/coreos/ignition-dracut/pull/36

**Comment by jlebon** [comment]
Yeah, we really should fix this. Right now, `restorecon -R /` and `autorelabel=1` are super dangerous (see e.g. user report at https://twitter.com/goozbach/status/1118697493657681920?s=19).

To anyone in that situation, you can recover from this by booting with `enforcing=0`, then:

```
# rpm-ostree status -v # copy "BaseChecksum" or if missing, "Checksum"
# ostree checkout -H $checksum /ostree/repo/tmp/selinux-fix
# ostree fsck --delete
# ostree commit --consume --link-checkout-speedup --orphan --selinux-policy=/ /ostree/repo/tmp/selinux-fix
# restorecon -Rv /var
# restorecon -Rv /etc
# ostree admin deploy fedora-atomic:fedora/29/x86_64/atomic-host # or whatever refspec you're on
# reboot
```

At this point, you should be able to boot in enforcing mode again. Final cleanup:

```
# rpm-ostree cleanup --rollback
```

Note this will blow away all your layered packages; you'll have to relayer those again.

**Comment by goozbach** [comment]
should that be `BaseCommit` or ` Commit` instead of checksum?

**Comment by jlebon** [comment]
Thanks! I edited the original comment.

**Comment by goozbach** [comment]
For future reference I had to do an `rpm-ostree upgrade` prior to the above steps for them to work.

Other than that, this workaround is good!

**Comment by bam80** [comment]
> Yeah, we really should fix this. Right now, `restorecon -R /` and `autorelabel=1` are super dangerous

I still broke my Fedora Silverblue 31 system with `restorecon -R /` command. Isn't it fixed yet?

**Comment by jlebon** [comment]
> I still broke my Fedora Silverblue 31 system with `restorecon -R /` command. Isn't it fixed yet?

OSTree knows how to handle read-only `/sysroot`, but it doesn't automatically apply to existing nodes, because it requires modifying files not maintained by updates. We'll probably need a systemd service in `fedora-release-silverblue` or something to transition over existing systems.

**Comment by bam80** [comment]
Thanks @jlebon. Could we dedicate a separate issue for that part of the task then?

**Comment by bam80** [comment]
> Note this will blow away all your layered packages; you'll have to relayer those again.

Hmm, still see `LayeredPackages:` in rpm-ostree status with all bunch of my packages, they actually are not installed though.. Is it a bug?
