### ISSUE TITLE
unclear error when running ostree-admin-unlock without overlayfs

### ISSUE THREAD

**Issue by guyshapiro** [ostreedev/ostree#1273]
Tried to run `ostree admin unlock` on machine without overlayfs support (before I know it shouldn't work).
The result was the following message:
```
(ostree admin unlock:811): GLib-WARNING **: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: No such file or directory
error: overlayfs mount helper: Child process exited with code 1
```
If I understand correctly, this message indicates a bug in the error handling code.

(Tested on commit fc33ae018dccbcab633b69474db0811987355212)

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1279 and you have `r+` rights.
