### ISSUE TITLE
Documentation: another related project

### ISSUE THREAD

**Issue by tjim** [ostreedev/ostree#1284]
This is very relevant: [Live Upgrading Thousands of Servers from an Ancient Red Hat Distribution to 10 Year Newer Debian Based One](https://www.usenix.org/node/177348) (USENIX LISA 2013).

Live updates (no reboot) of file trees using an rsync-like protocol.

**Comment by cgwalters** [comment]
The fact that the kernel is maintained by a separate group from userspace seems weird to me.  Anyways, yes...PR in https://github.com/ostreedev/ostree/pull/1299
