### ISSUE TITLE
Not reading commitpartial state from parent repo

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#1306]
When loading a commit with ostree_repo_load_commit() it can load the commit from ->parent_repo. However, it never reads the commitpartial state from the parent, even when the commit is from there.

This leads to issues when doing a delta update from a repo with a parent, if the commit is partial and in the parent it will still try to do a delta update which may reference files that are not locally available, as in https://github.com/flatpak/flatpak/pull/1126

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1308
