### ISSUE TITLE
Consider "content hash"

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#1315]
For a [promotion workflow](https://github.com/ostreedev/ostree-releng-scripts/blob/master/do-release-tags) it'd be nice if we added the concept of a "content hash" which was basically just `SHA256(dirtree + dirmeta)` of a commit's rootfs.

Then a promotion system could ensure that *content* hashes remain the same when promoting a commit, and deployment systems could also show this (we'd have an abbreviation like "chash"?).

What I'm a bit unsure about implementing is "pull by content hash"...maybe it'd end up in the summary file?

**Comment by cgwalters** [comment]
What this issue is getting at is that one can't have *both*

 - Chained commit history (git, ostree default)
 - Content promotion

Now...something one could try today would be to forego commit history.  Basically just generate every commit without a parent; then promotion is simply changing the ref.  The downside of this is that I think you'd end up wanting some sort of other database to track "history".

**Comment by cgwalters** [comment]
Bigger picture, in the rpm-ostree world (driven by some usability design from [Cockpit](http://cockpit-project.org/)) we've been focusing on version numbers as the thing that operators see - for a lot of reasons.  One interesting thing here is that most package systems (RPM,dpkg,etc.) as well as OCI don't have built-in history.  In the package system case there's a unique ID (NEVRA in the RPM world), and in the OCI case there's a digest as well as mutable "names" that act a lot like git/ostree branches/refs.  

But in both the pkg and Docker/OCI case, there's no built-in history/connection between independent builds.

**Comment by abferm** [comment]
A problem with dropping history or refs with multiple commits is that you can no longer use the ostree admin tools effectively, because your origin ref will never have any new commits. I may be wrong, but I believe this would affect the ability to generate and use static deltas as well.

A potential solution that just jumped out to me is making commits track content and metadata, while refs/branches track history. In other words I am suggesting removing "parent" from a commit, and making a ref an ordered list of commits. This would allow moving commits between refs without modifying the commit itself

**Comment by cgwalters** [comment]
Static deltas are between arbitrary commits - it doesn't actually require that one is a parent of another in any way.  For example today one can make *reverse* deltas for downgrade scenarios.  Another example is for e.g. Fedora Atomic Host, we make deltas between the last major branch e.g. `fedora/26/x86_64/atomic-host` and `fedora/27/x86_64/atomic-host`, even though those are distinct branches.

One just needs to run `ostree static-delta generate --from FROM --to TO` with any arbitrary pair of `FROM` and `TO` commit hashes (or branches), rather than the shorthand `static-delta generate BRANCH` which implicitly looks at `BRANCH^` (i.e. the previous commit).

**Comment by abferm** [comment]
Okay, so that just leaves the upgrade path. To make configuration sane I would want to point a device at a reference that is updated with new commits.

**Comment by cgwalters** [comment]
It works today to do e.g.:

```
ostree commit --parent=none -b exampleos/42/x86_64/demo --add-metadata-string=version=42.0 ...
ostree commit --parent=none -b exampleos/42/x86_64/demo --add-metadata-string=version=42.1 ...
```

That will update the ref, but the second commit won't refer to the first.  Any client systems pointed at `exampleos/42/x86_64/demo` are going to find the updated commit.

**Comment by cgwalters** [comment]
Now I'll be honest I haven't tried using ostree in this mode for any kind of production use, so there *could* be gotchas that aren't coming to mind now, but I can't think of any other than that every bit of ostree that *does* use history will break (e.g. `ostree prune --depth`, `ostree pull --depth`).

**Comment by abferm** [comment]
Might I suggest a set of sub-commands in the ostree binary for dealing with refs? Specifically `ostree ref list` and `ostree ref set REF COMMIT`.

**Comment by dustymabe** [comment]
content hash is an interesting idea. I wonder how this discussion fits in with the ***support tags*** discussion:  https://github.com/ostreedev/ostree/issues/805

**Comment by cgwalters** [comment]
@abferm Not your fault, the ref commands are confusing/weird for sure.  There are a few issues that have touched on that - https://github.com/ostreedev/ostree/pull/1069 is a recent one.

As far as tags, yeah I see an intersection in that if one is going this "no parent history" path one would probably want tags for "released" commits.  But I think it'd be mostly for semantic clarity?
