### ISSUE TITLE
ostree static-delta apply-offline seems broken

### ISSUE THREAD

**Issue by pataelmo** [ostreedev/ostree#1334]
I apologize ahead of time if I'm being stupid, but I have an ostree enabled Boot to Qt image that I've made and everything works well except apply static deltas.  I can generate a static delta from my repository on my server:
```
ostree --repo=ostree-repo static-delta generate --from=<commit1> --to=<commit2> --min-fallback-size=0 --inline --filename=superblock --disable-bsdiff linux/qt
```
After transferring the superblock file to my embedded system and running:
```
ostree static-delta apply-offline superblock
```
There is no error, no feedback, it just seems to accept it, but checking the log and refs shows nothing has changed.

I'm currently passing the entire repository to a USB stick and doing a pull-local which works, but it'd be nice to not have to drag a 500MB repository around to push a 1MB update.   Please let me know if this is a known bug, or if I'm doing something stupid.   

Server ostree version is: ```ostree 2016.8  +libsoup +gpgme +libarchive```
Device ostree version is: ```ostree 2016.8  +libsoup +gpgme +libmount```

**Comment by pataelmo** [comment]
I did this again manually with gpg signatures and it worked.  So either I just did something horribly wrong before, or you actually need proper gpg signatures on the commits for it work?

Either way this seems to be my own mistake.

**Comment by cgwalters** [comment]
Sorry about the lack of reply here earlier!  Hmm...it looks like we don't have a lot of output for apply-offline, but it is in the unit tests (though I'd note your version of libostree is quite old now).  I don't think there's anything there that should be requiring signatures though.

**Comment by pataelmo** [comment]
@cgwalters thanks for getting back to me on this.  I stumbled onto it working by banging against it the first time.  Then when I went to implement an interface in an application this all was broken again.  I wanted to say, and maybe this is my version or just a well known process, that the static-delta was working, but not as expected.

After applying a delta offline I had to know what the commit hash for that delta was and then use ostree reset to make my branch actually use those commits.

To your point earlier it would be nice to have some more output from the ostree static-delta apply-offline.   At the very least it would be nice for it to print out the commits that were added, ideally for my own use it would be nice to have an option to bring a current ref up to the latest commits applied by the delta.

**Comment by stonefly128** [comment]
@pataelmo @cgwalters 
Sorry for commenting the issue, i saw it was closed, but mybe i can get some help from you.
I also encountered this problem， but i haven't test it with gpg signatures.
I tested apply-offline like this:
```
mkdir repo
mkdir tree
ostree --repo=repo init
echo 11111 > tree/1.txt

ostree --repo=repo commit -b test tree
ostree --repo=tree-local init
 
ostree --repo=tree-local pull-local ./repo test
mkdir tree/2
echo 22222 > ./tree/2/2.txt
ostree --repo=repo commit -b test tree

ostree --repo=repo static-delta generate --from={commit} --to={commit}  --min-fallback-size=0 --inline --filename=superblock --disable-bsdiff test
ostree --repo=tree-local static-delta apply-offline superblock
``` 
after that,  `ostree --repo=tree-local fsck ` got same objects with the "repo" repository, but also, checking the log and refs shows nothing has changed.

My os is centos 7.4, the ostree version is:
```
ostree --version
libostree:
 Version: 2017.8
 Git: 25209bfa204950a23908a035bc008556b5ba47e9
 Features:
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - libmount
  - release
```
I also tried it on version:2018.5, but got the same results.

I want to know if there is something wrong with my experimental procedure, and what is the correct procedure?

Thanks.

**Comment by stonefly128** [comment]
yes, it's work!
Thank you very mach, it help me a lot.

**Comment by cgwalters** [comment]
Thanks for following up!  And yeah...sorry this is admittedly quite confusing.  Today deltas just go from commit `A` to commit `B`; they don't carry information about refs.  We could add that fairly cheaply, although it gets into some interesting questions as soon as one starts then later creating branches that refer to the same commits targeted by a delta.

Feels like the end here is we need to tweak the docs to note that `apply-offline` is (today) intended more as just a tool that a higher level script/process invokes, and include updating the ref with that?  Though maybe it's simplest to add:

`apply-offline --ref=exampleos/x86_64/someref` ?
