### ISSUE TITLE
allow just pulling a specified commit without specifying a ref

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1339]
From the docs you can pull a specific commit, but you have to specify a ref along with it:
```
$ ostree --repo=repo pull remote_name exampleos/x86_64/standard@98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4

Download the specific commit starting with 98ea6e as if it was the latest commit for exampleos/x86_64/standard.
```

I'm not sure why the ref is necessary. I'm guessing the ref also gets updated in the transaction? In my case I just want to download the commit and not update the ref.

**Comment by cgwalters** [comment]
We support just specifying the commit, like
`ostree --repo=repo pull remote_name 98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4` right?

**Comment by dustymabe** [comment]
weird. I could have swore this didn't work when I was trying it the other night. I think this more had to do that I was pulling from a remote that didn't have the entire history in it (when I thought it did). Sorry about that.
