### ISSUE TITLE
Alias refs don’t work when created pointing to a remote ref

### ISSUE THREAD

**Issue by pwithnall** [ostreedev/ostree#1342]
@dbnicholson pointed this out in a chat today; we haven’t had time to reproduce it properly.

Something along the lines of:
```
ostree refs --alias  --create=new-alias remote1:old-ref
```
doesn’t work.

**Comment by cgwalters** [comment]
Given that remote names are freeform data, I'm not sure about supporting this.

**Comment by pwithnall** [comment]
What do you mean? I was assuming it would either be:
 * supported as a symlink to `refs/remotes/$remote_name/$ref_name`; or
 * explicitly not supported (`ostree refs` returns an error message).

**Comment by cgwalters** [comment]
I'm thinking "explicitly not supported".

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1381

**Comment by pwithnall** [comment]
Should this be mentioned in the documentation somewhere?
