### ISSUE TITLE
Building manpages from the source tarball fails

### ISSUE THREAD

**Issue by kgraefe** [ostreedev/ostree#1374]
When building from source on Ubuntu 16.04 and no parameters to `./configure`, building with `make` fails:
```bash
# make V=1
make  all-recursive
make[1]: Entering directory '/home/kgraefe/src/libostree-2017.14'
Making all in .
make[2]: Entering directory '/home/kgraefe/src/libostree-2017.14'
/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 --output man/ostree.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl man/ostree.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
Makefile:8449: recipe for target 'man/ostree.1' failed
make[2]: *** [man/ostree.1] Error 4
make[2]: Leaving directory '/home/kgraefe/src/libostree-2017.14'
Makefile:6911: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/kgraefe/src/libostree-2017.14'
Makefile:2757: recipe for target 'all' failed
make: *** [all] Error 2
```

This is caused by calling `xsltproc` with the `--nonet` option ([Makefile-man.am:54](https://github.com/ostreedev/ostree/blob/v2017.14/Makefile-man.am#L54)) but pulling the stylesheet from `http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl` ([Makefile-man.am:64](https://github.com/ostreedev/ostree/blob/v2017.14/Makefile-man.am#L64) and [Makefile-man.am:67](https://github.com/ostreedev/ostree/blob/v2017.14/Makefile-man.am#L67)).

**Comment by cgwalters** [comment]
This came up before somewhere else but I can't find it in a quick search. Basically you need to either:

 - Install the stylesheets: They're packaged for Debian/Fedora/Ubuntu/Arch/etc.
 - Disable documentation: (Used by e.g. OpenEmbedded)

You *really* don't want any kind of real production build process to depend on Internet availability.

BTW one approach I highly recommend is to use e.g. `apt build-dep`; in this case `apt build-dep glib2.0` will get you a lot of the libostree build deps.

This is all true of building software in general, from systemd to coreutils.
