### ISSUE TITLE
pass ostree version in http user agent string

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1405]
We have a case where there is a bug in libcurl in old versions of ostree and we are going to work around in the rpm package for newer versions of ostree and also server side in Fedora so that clients can upgrade. What we'd like to be able to do is send clients with the bug one place and clients without the bug to another place, but we have no way to do that because we don't know what version of ostree the client is using.

If we can get that information passed to us in an http header or user agent string then we can implement workarounds in the future if we need them. 

some background here: https://pagure.io/atomic-wg/issue/405

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1406
