### ISSUE TITLE
--with-static-compiler fails if parameter has arguments

### ISSUE THREAD

**Issue by akiernan** [ostreedev/ostree#1428]
Building OSTree 2018.01 inside Yocto, if you pass `--with-static-compiler="${CC}"` then the expansion of ${CC} includes both the compiler and (some) arguments, this makes the configuration fail to use the passed compiler correctly because of missing quoting:

```diff --git a/configure.ac b/configure.ac
index a4e1e74..758e225 100644
--- a/configure.ac
+++ b/configure.ac
@@ -519,7 +519,7 @@ AC_ARG_WITH(static-compiler,
             AS_HELP_STRING([--with-static-compiler],
                            [Use the given compiler to build ostree-prepare-root statically linked (default: no)]),,
               [with_static_compiler=no])
-AM_CONDITIONAL(BUILDOPT_USE_STATIC_COMPILER, test x$with_static_compiler != xno)
+AM_CONDITIONAL(BUILDOPT_USE_STATIC_COMPILER, test "x$with_static_compiler" != xno)
 AC_SUBST(STATIC_COMPILER, $with_static_compiler)

 dnl for tests (but we can't use asan with gjs or any introspection,```

**Comment by cgwalters** [comment]
Just getting to this now, sorry about being slow.  This looks sane to me too, do you want to open a PR?  If not I can do one and attribute it to you easily enough.

**Comment by akiernan** [comment]
Sure:

https://github.com/ostreedev/ostree/pull/1454

**Comment by lucab** [comment]
This has been fixed by the PR above, thus I guess the ticket can be closed.

**Comment by cgwalters** [comment]
Yep, thanks!
