### ISSUE TITLE
Documentation license question

### ISSUE THREAD

**Issue by btreut** [ostreedev/ostree#1431]
under which license is the documentation?

I tried to populate the information about OSTree in Wikipedia by reusing parts of the introduction, but it got deleted due to Copyright issues. So a more liberal Copyright (at least for parts of the manual) would be very welcome. Currently the entry about OSTree [https://en.wikipedia.org/wiki/OSTree] is a stub and I do not feel to be competent enough to put there more Information, which is not reusing stuff more or less verbally. It was again deleted for being a self-referencing ad, but happily someone else restored it.

**Comment by cgwalters** [comment]
So I saw https://en.wikipedia.org/wiki/Wikipedia:Non-free_content but it's really long; is the TL;DR "license under CC BY-SA or alternatively CC BY-SA and GFDL"?

**Comment by btreut** [comment]
I am not sure, but GNU LGPL is not enough. But I guess GFDL and CC licenses would be OK. 

The guy who deleted my first attempt said: "Thanks for checking on that, Bernhard. Unfortunately GNU licenses aren't compatible with Wikipedia. I'd suggest rewriting the article in your own words. – Joe" but this post is only in Wikipedias history.

**Comment by cgwalters** [comment]
Does anyone have an example of a project that does dual licensing of GFDL and CC BY-SA for their docs?

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1432

**Comment by btreut** [comment]
Thanks a lot.

**Comment by cgwalters** [comment]
@btreut Thank *you* for looking at doing a Wikipedia page!  If there's anything else we can do to help don't hesitate to ask.
