### ISSUE TITLE
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl

### ISSUE THREAD

**Issue by BH1SCW** [ostreedev/ostree#1448]
make[1]: Entering directory '/hddisk/work/github/ostree/apidoc'
make[1]: Leaving directory '/hddisk/work/github/ostree/apidoc'
make  all-recursive
make[1]: Entering directory '/hddisk/work/github/ostree'
Making all in .
make[2]: Entering directory '/hddisk/work/github/ostree'
  GEN      man/ostree.1
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
Makefile:8523: recipe for target 'man/ostree.1' failed
make[2]: *** [man/ostree.1] Error 4
make[2]: Leaving directory '/hddisk/work/github/ostree'
Makefile:6965: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/hddisk/work/github/ostree'
Makefile:2790: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cgwalters** [comment]
See https://github.com/ostreedev/ostree/issues/1374

**Comment by cgwalters** [comment]
I think you want something like this: https://en.opensuse.org/SDB:Zypper_usage_11.3#Source_packages_and_build_dependencies
