### ISSUE TITLE
Max outstanding fetches assertion in soup

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#1451]
I have a job where I ask ostree to pull a lot of commits at once. I'm occasionally hitting an assertion in the soup fetcher:
```
OSTree:ERROR:src/libostree/ostree-fetcher-soup.c:387:start_pending_request: assertion failed (g_hash_table_size (thread_closure->outstanding) < thread_closure->max_outstanding): (24 < 24)
```
Looking at the pull code, I don't understand how this is happening. It seems like it starts queuing requests (rather than immediately starting them) as soon as you get to _OSTREE_MAX_OUTSTANDING_FETCHER_REQUESTS. How is it getting to 3 times that value?

**Comment by cgwalters** [comment]
I think f4d1334e19ce3ab2f8872b1e28da52044f559401 missed deleting the assertions; looking at current master, nothing actually checks against `max_outstanding` in libsoup.

**Comment by dbnicholson** [comment]
For the record, I think the real issue is that the deltas superblock fetches aren't being counted in the total number of fetches - https://github.com/ostreedev/ostree/pull/1453#discussion_r168321706.
