### ISSUE TITLE
support /boot in the root filesystem; i.e. no separate /boot

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1452]
Whenever someone does manual partitioning and they don't add a separate `/boot` partition. They end up getting an error in anaconda: see [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1497094).

I looked and I couldn't find a specific issue that addressed this but there is https://github.com/ostreedev/ostree/issues/876 which seems somewhat related but mostly focusing on atomicity of the filesystem I think.

Can we support `/boot` in the root filesystem? Of course, for efi systems there will always be the vFAT `/boot/efi`.

Note: This may be an issue that needs code work in Anaconda instead of in ostree.

**Comment by cgwalters** [comment]
This is mostly in https://github.com/ostreedev/ostree/pull/1404

**Comment by dustymabe** [comment]
> This is mostly in #1404

Ah, cool. A PR. Now we can close this issue when it gets merged.

Quick question. That PR title says for uboot and syslinux. Does it also apply to grub2?

**Comment by vtolstov** [comment]
any progress for such think?

**Comment by clime** [comment]
Same question here.

**Comment by cgwalters** [comment]
I was thinking about this briefly, and it may simplify things to avoid copying the kernel/initramfs to `/boot` in the single partition scenario - there's no reason to do it!  We can just point the bootloader configs at the canonical kernel state in `/usr/lib/modules/$kver`.

**Comment by akiernan** [comment]
We run w/o a separate `/boot` on U-Boot, obviously they just end up hardlinked anyway!
