### ISSUE TITLE
Please clarify documentation copyright/licensing

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#1456]
README.md now says

> The license for the *documentation* of libostree is: `SPDX-License-Identifier: (CC-BY-SA-3.0 OR GFDL-1.3-or-later)`

but that doesn't appear to be entirely true: the man pages are generated from source code that is explicitly LGPL-2.0+, and the API documentation is generated from the library's own source code so it would be difficult for it to be anything other than LGPL-2.0+.

If the intention is that files that carry a SPDX-License-Identifier tag (plus README.md and docs/CONTRIBUTING.md) are licensed according to that tag, please could you say that instead?

The documentation files also carry a license tag but no copyright notice. Who holds the copyright on those files? Presumably it's Colin + Red Hat?

I'm not sure that this relicensing was a great idea - it prevents copying and pasting between the API documentation and the readthedocs documentation, in either direction, by anyone who doesn't have the authority to relicense the text being copied - but obviously that's your choice.

**Comment by cgwalters** [comment]
Right, I should have been clearer; "documentation" here is just the `doc/` directory.  You're right that trying to do the API docs and man pages would quickly get into problems.

In practice...I don't see us copy/pasting or moving text much between the API docs and `doc/`.  The man pages are indeed trickier...perhaps it's simplest in practice to keep them as mostly basic "brief command summary + option listings" and not try to have a big `man ostree.system` or something that's like `man bootup` from systemd.

As far as copyright holder, the canonical reference for that is always `git log` right?

**Comment by cgwalters** [comment]
So concretely we should add `SPDX-License-Identifier: LGPLv1.2+` to the man pages at least.  I can do that.

**Comment by cgwalters** [comment]
Actually the man pages already have that.

**Comment by smcv** [comment]
> As far as copyright holder, the canonical reference for that is always `git log` right?

The name in the commit is often not the copyright holder, because developers often have contracts with their employers that sign away copyright for some or all of the code that developer writes. (For my work for Collabora, it actually depends which of our clients I wrote the code for - most of my contributions to dbus are owned by Collabora, but a few are owned by one of our clients instead.)

**Comment by smcv** [comment]
> Right, I should have been clearer; "documentation" here is just the `doc/` directory

Perhaps you could change the bit about that in README.md to something like

> The license for the documentation in the `doc/` directory is: `SPDX-License-Identifier: (CC-BY-SA-3.0 OR GFDL-1.3-or-later)`

or

> Some documentation files are marked with `SPDX-License-Identifier: (CC-BY-SA-3.0 OR GFDL-1.3-or-later)` and are released under the license indicated

or something like that, to indicate that you aren't trying to relicense the API docs or the man pages? At the moment it would be easy to think that two contradictory statements are being made about some files' licenses.
