### ISSUE TITLE
Add support for "pinning" 📌 deployments

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#1460]
Update 2018-02-23 PR: https://github.com/ostreedev/ostree/pull/1464

---

We should add `ostree admin pin <deploymentid>` which makes the deployment persist until explicitly unpinned.  Example user story: Jane rebases her OS to a new major version `N`, and wants to keep around `N-1` even after a few upgrades for a while so she can easily roll back.

**Comment by dustymabe** [comment]
very similar to https://github.com/projectatomic/rpm-ostree/issues/577. basically the difference is in the heuristic. Both want to keep around old deployments. One asks for them to be garbage collected based on a number, the other asks for them to be garbage collected based on a configurable flag.
