### ISSUE TITLE
`ostree find-remotes` doesn't recognize all mounts

### ISSUE THREAD

**Issue by mwleeds** [ostreedev/ostree#1466]
Oddly, `ostree find-remotes --finders=mount` is only detecting the root file system mount, when it should also detect the flash drive that's plugged in. `gio mount -l` does show the mount, so it would seem it's ostree's fault.

```
endless@endless:~$ sudo G_MESSAGES_DEBUG=all ostree find-remotes --finders=mount com.endlessm.Dev.Os os/eos/amd64/eos3.3
(ostree find-remotes:1755): OSTree-DEBUG: ostree_repo_finder_resolve_all_async: Resolving refs [(com.endlessm.Dev.Os, os/eos/amd64/eos3.3)] with finders [OstreeRepoFinderMount]
(ostree find-remotes:1755): OSTree-DEBUG: ostree_repo_finder_mount_resolve_async: Found 1 mounts
(ostree find-remotes:1755): OSTree-DEBUG: Ignoring repository ‘.ostree/repo’ on mount ‘Filesystem root’ as it could not be opened: opendir(.ostree/repo): No such file or directory
(ostree find-remotes:1755): OSTree-DEBUG: Ignoring repository ‘ostree/repo’ on mount ‘Filesystem root’ as it is the same as the one we are resolving
(ostree find-remotes:1755): OSTree-DEBUG: Ignoring repository ‘var/lib/flatpak’ on mount ‘Filesystem root’ as it could not be opened: opendir(objects): No such file or directory
(ostree find-remotes:1755): OSTree-DEBUG: resolve_all_finished_one: Finished, results: (none)
No results.
endless@endless:~$ gio mount --list
Drive(0): BWBD3R
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
Drive(1): Unnamed Drive (/dev/mmcblk0boot1)
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
Drive(2): SanDisk Ultra
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  Volume(0): 124 GB Volume
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    Mount(0): 124 GB Volume -> file:///run/media/endless/9f4cbedc-700c-4b2b-9bf7-5055c1667ad3
      Type: GProxyMount (GProxyVolumeMonitorUDisks2)
```

**Comment by pwithnall** [comment]
Is `file:///run/media/endless/9f4cbe…` the mount you’re meaning?

It might be that `GVolumeMonitor` only returns mounts which have no drive or volume when you call `g_volume_monitor_get_mounts()`. Looking at the `gio-tool-mount.c` code in GLib, we might also need to call `g_volume_monitor_get_connected_drives()` and `g_volume_monitor_get_volumes()` and enumerate the mounts associated with those drives/volumes.

The GLib documentation for this could *really* do with clarifying. I’ve never been sure what the difference is between a drive, volume or mount,  or exactly where you should expect to find each instance of them.

**Comment by mwleeds** [comment]
>Is file:///run/media/endless/9f4cbe… the mount you’re meaning?

Yes.

> It might be that GVolumeMonitor only returns mounts which have no drive or volume when you call g_volume_monitor_get_mounts(). Looking at the gio-tool-mount.c code in GLib, we might also need to call g_volume_monitor_get_connected_drives() and g_volume_monitor_get_volumes() and enumerate the mounts associated with those drives/volumes.

Looks like in `gio-tool-mount.c`, the mounts that are part of volumes are manually excluded so that's not a property of `g_volume_monitor_get_mounts()`. Anyway it turns out the reason for the different mount lists is `sudo`. If I run `sudo gio mount -l`, it doesn't show the USB drive mount.

**Comment by mwleeds** [comment]
Alright I have a patch for this using udisks instead and it finds all mounts system-wide, so as long as it's okay to add that dependency I'll just clean it up and submit it.

**Comment by pwithnall** [comment]
I’ve [commented on the PR](https://github.com/mwleeds/ostree/commit/ef361be7596f77ec9a7b737d1596612ec3df1d56#commitcomment-27884641). tl;dr, I don’t think removing the `GVolumeMonitor` abstraction is the right approach.

I need to spend some time working out how `GVolumeMonitor` actually gets instantiated and an implementation chosen. I’ll write up my findings here or in the PR.

**Comment by pwithnall** [comment]
OK, I think I’ve got to the bottom of this. Writeup forthcoming.

**Comment by mwleeds** [comment]
This was fixed by [Philip's glib patch](https://bugzilla.gnome.org/show_bug.cgi?id=793994). Given that Endless is the only user of this, I don't think it's worth leaving the issue open until ostree bumps its glib dependency.
