### ISSUE TITLE
RFE: Allow libostree user to append to the user agent

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#1495]
On flathub now, all user agents are something like: `ostree libsoup/2.52.2`. I would like a function to append a string to it so i could instead get `ostree libsoup/2.52.2 flatpak/0.10.2`

**Comment by ramcq** [comment]
(also couldn't we include the ostree version?)

**Comment by jlebon** [comment]
> (also couldn't we include the ostree version?)

This part at least was already done in #1406 and should be in v2018.1.

**Comment by jlebon** [comment]
WIP in #1496.

**Comment by jlebon** [comment]
This was done in #1496.
