### ISSUE TITLE
flatpak tests fail when Avahi is enabled but not running

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#1618]
I tried building Flatpak 0.11.8 for Debian experimental against libostree snapshot ecdebeb2, with Avahi support enabled. The installed-tests (in autopkgtest), which do not currently pull in `avahi-daemon`, fail with errors like this:

```
(flatpak install:7036): OSTree-WARNING **: 10:45:27.477: Avahi finder failed abnormally; removing it: Failed to create service browser: Bad state
/usr/lib/flatpak/installed-tests/Flatpak/test-unsigned-summaries.sh: line 81:  7036 Trace/breakpoint trap   ${FLATPAK} ${U} install test-repo org.test.App master
```

I think this is because the fix for #1542 is not (fully?) effective. The Avahi client does this:

```
  client = avahi_client_new (avahi_glib_poll_get (self->poll),
                             AVAHI_CLIENT_NO_FAIL,
                             client_cb, self, &failure);

  if (client == NULL)
    {
      if (failure == AVAHI_ERR_NO_DAEMON)
        g_set_error (error, G_IO_ERROR, G_IO_ERROR_NOT_FOUND,
                     "Avahi daemon is not running: %s",
                     avahi_strerror (failure));
      else
        g_set_error (error, G_IO_ERROR, G_IO_ERROR_FAILED,
                     "Failed to create finder client: %s",
                     avahi_strerror (failure));

      return;
    }
```

but the meaning of `AVAHI_CLIENT_NO_FAIL` is that, instead of failing with `AVAHI_ERR_NO_DAEMON`, the Avahi client will continue to try to connect in the background. Until it has successfully connected, most methods will fail with `AVAHI_ERR_BAD_STATE`.

cc @mwleeds @pwithnall @smspillaz

**Comment by smcv** [comment]
(Endless developers: The packaging is available at https://salsa.debian.org/debian/ostree and https://salsa.debian.org/debian/flatpak if you want to send merge requests with any of your changes.)

**Comment by mwleeds** [comment]
Looking at https://ci.debian.net/packages/f/flatpak/testing/amd64/ it doesn't seem like the tests are actually run. Is there somewhere else to look for this? Or, could you give steps to reproduce it locally?

**Comment by smcv** [comment]
The tests can't be run on ci.debian.net because it only offers LXC containers, not full virtual machines, but you can run them locally with `gnome-desktop-testing-runner Flatpak`, or in an autopkgtest-virt-qemu virtual machine (see autopkgtest-virt-qemu(1) to create one) with something like:

```
autopkgtest \
$(dcmd --deb ostree_2018.5+42+gecdebeb2-1_amd64.changes) \
$(dcmd --deb flatpak_0.11.8.2-1+exp1_amd64.changes) \
flatpak_0.11.8.2-1+exp1.dsc \
-- \
qemu sid-amd64.qcow2
```

See the `debian/experimental` branches of the ostree and flatpak packaging for suitable ostree and flatpak packages.

(ci.debian.net also only tests versions of packages that have been released to unstable, which I am not going to do until the tests pass in autopkgtest-virt-qemu, and probably also not until the p2p code is in a release.)

**Comment by cgwalters** [comment]
Offhand: Do we need the `_NO_FAIL`?  I'm guessing it was designed for long-running processes; for the `flatpak` CLI it's not necessary.  For rpm-ostree the daemon auto-exits, so if we race on startup and can't connect to Avahi, then we'll try again next time.

I suspect the main problematic case here is going to be gnome-software, which I think is long-running today.

**Comment by smcv** [comment]
> Offhand: Do we need the `_NO_FAIL`?

I don't think we do.

> For rpm-ostree the daemon auto-exits, so if we race on startup and can't connect to Avahi, then we'll try again next time.

How much sense does it even make for rpm-ostree to try "reconnecting" to Avahi, in a world where the `dbus-daemon --system` and Avahi are normally both started by systemd on-demand, so there shouldn't be a race at all?

> I suspect the main problematic case here is going to be gnome-software, which I think is long-running today.

Yes it is, but if it either can't connect to the system bus, or can connect but can't communicate with Avahi, by the time a user's login session starts, is time passing actually going to fix that?

I think `_NO_FAIL` may have been designed very early in the lifetime of the D-Bus project, when we didn't have dependency-graph-based init systems like systemd and Upstart, system bus auto-activation, or system bus systemd activation. It isn't clear to me that it still adds much value now.

If we keep `_NO_FAIL`, then there needs to be a flag for "has Avahi started?", and all methods that would talk to Avahi need to raise `G_IO_ERROR_NOT_FOUND` if that flag isn't set yet. My understanding is that `AVAHI_ERR_BAD_STATE` is basically in the same sort of "programmer error" territory as `g_return_if_fail`, so we really shouldn't allow ourselves to hit it?
