### ISSUE TITLE
ConditionNeedsUpdate needs /usr to have newer modification time than /etc

### ISSUE THREAD

**Issue by peterbaouoft** [ostreedev/ostree#1628]
Hi,
For `/usr` on Atomic host, the modification time is canonicalized to epoch (1970) by ostree, and this makes /usr always older than /etc.

However, to have system-sysusers( or any service with ConditionNeedsUpdate ) to trigger automatically during boot time, /usr needs to be newer than /etc due to ConditionNeedsUpdate=/etc in the service file:

```
[rbao@unused-10-15-17-147 ~]$ cat /usr/lib/systemd/system/systemd-sysusers.service 
[Unit]
Description=Create System Users
Documentation=man:sysusers.d(5) man:systemd-sysusers.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-remount-fs.service
Before=sysinit.target shutdown.target systemd-update-done.service
ConditionNeedsUpdate=/etc

 ................................................
```
Reading a bit from systemd code base, it seems like ConditionNeedsUpdate needs /usr to be strictly newer than /etc (i.e only > and not >=). See [code](https://github.com/systemd/systemd/blob/master/src/shared/condition.c#L417-L481) and [documentation](https://github.com/systemd/systemd/commit/cdf0c7abf8594db37bbb0720f7c18a1765465110).  

Endless seem to already have an implementation to fix this: **Related commit:** https://github.com/endlessm/ostree/commit/9ef61fd1623ffed6580c0309aff8d1b29e671ec7  \o/
Migrated from https://github.com/projectatomic/rpm-ostree/issues/1415

**Comment by cgwalters** [comment]
The idea behind https://github.com/endlessm/ostree/commit/9ef61fd1623ffed6580c0309aff8d1b29e671ec7 seems generally OK to me. I just have minor code style nits, and it'd be good to have a test.

@dbnicholson I vaguely recall this came up before - let's try to get this upstream?

**Comment by cgwalters** [comment]
@peterbaouoft Would you mind testing this patch fixes the problem for rpm-ostree+sysusers?

**Comment by peterbaouoft** [comment]
> @peterbaouoft Would you mind testing this patch fixes the problem for rpm-ostree+sysusers?

No, not at all, will be trying it out =).

**Comment by peterbaouoft** [comment]
Yup, it does fix the problem for `ConditionNeedsUpdate` =). Now systemd-sysusers is triggered at boot time \o/.

**Comment by dbnicholson** [comment]
@cgwalters yes, please. My cleaner version with tests (based on 2018.4, don't have time to rebase on master at the moment) is in https://github.com/dbnicholson/ostree/commit/6b3d0cc5d02d9904a8205a08d8f30f3d61064ec0.

**Comment by dbnicholson** [comment]
BTW, this is also https://bugzilla.gnome.org/show_bug.cgi?id=752950.

**Comment by dbnicholson** [comment]
I rebased my branch now in #1631 and it passes locally.
