### ISSUE TITLE
Add a change-update-summary repo config option

### ISSUE THREAD

**Issue by mwleeds** [ostreedev/ostree#1664]
Currently ostree supports the `core.commit-update-summary` option to automatically update the `summary` file after a commit, but this only applies to commits that happen via the `ostree commit` command. So there's no way to have the summary update after a pull, which is the most common way the repo changes on the client side, for example during app install/update/uninstall and OS update operations. I'm proposing a `pull-update-summary` option (or maybe `change-update-summary`?) that would regenerate the summary when a ref is added, removed, or updated. I'll probably end up implementing it soon but I want to get feedback first.

The use case for it is twofold:
1. Currently the `ostree create-usb` and `flatpak create-usb` commands depend on the summary, and the alternative ways of updating it are pretty ugly. Currently the user is asked to do it, but that's a bad experience and won't work when we teach GNOME Software how to call out to it. Another possibility is escalating to root privileges, but that seems pretty ugly when all you really need to do is read operations from the system repo and write operations to a repo you control.
2. `eos-updater-avahi` depends on the `summary` file when generating DNS-SD records informing LAN peers of the refs it's offering, so it needs to be up to date for that to work.

As far as I can tell it would be pretty hard to remove the dependency on the summary by the `create-usb` commands, because it seems to be deeply embedded in the way `ostree_repo_pull_with_options` works.

Alternatively, we could change the meaning of `commit-update-summary` if its current behavior is not intended/required.

**Comment by mwleeds** [comment]
cc @pwithnall

**Comment by mwleeds** [comment]
@dbnicholson do you know if repository locking is in a shape where it would prevent concurrency issues with this?

**Comment by dbnicholson** [comment]
A shared lock is taken during the commit transaction, but you can't regenerate the summary there since none of the refs have been committed yet. In my unfinished locking work, I added a shared lock when regenerating the summary - https://github.com/ostreedev/ostree/pull/1292/commits/eba8a175e9b9a8241b0e5b6eec5a29621d250df0.

**Comment by mwleeds** [comment]
> In my unfinished locking work, I added a shared lock when regenerating the summary - eba8a17.

So it sounds like that lock will be sufficient for this feature, even if locking in general is still unfinished?

**Comment by pwithnall** [comment]
> So it sounds like that lock will be sufficient for this feature, even if locking in general is still unfinished?

In order to protect this, you need to have the `summary` and the refs all locked while you generate the summary. `ostree_repo_transaction_set_ref*()` should be locked already. `ostree_repo_set_*ref_immediate()` are not currently locked, and would need locking support.
