### ISSUE TITLE
Separate /var broke in 2018.6

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#1667]
Regression from https://github.com/ostreedev/ostree/pull/1617

We need an insttest covering this.

**Comment by cgwalters** [comment]
Trivial reproducer setup for a separate `/var` in a testing VM:
```
cp -a /var /sysroot/myvar
echo '/sysroot/myvar /var none bind 0 0' >> /etc/fstab
```

(And if you do e.g. `rpm-ostree override replace` to test, don't forget to `rpm-ostree initramfs --enable` like I did)

**Comment by cgwalters** [comment]
Dropping this systemd unit in `/etc/systemd/system` should work around the issue:

```
$ cat > /etc/systemd/system/workaround-ostree-issue-1667.service << EOF
[Unit]
DefaultDependencies=no
Before=ostree-remount.service

[Service]
ExecStart=/bin/sh -c 'if findmnt -s -n -T /var; then echo Enabling workaround; umount /var; systemctl start --no-block var.mount; fi'

[Install]
WantedBy=multi-user.target
EOF
$ systemctl enable workaround-ostree-issue-1667.service
```

**Comment by nexfwall** [comment]
@cgwalters, thank you. Will try it in the evening, then I come back home.

**Comment by akiernan** [comment]
That workaround is fixing the separate `/var` problem for me. The change in #1668 isn't doing it for me though, but given I'm newly trying to use a separate `/var` I'm not sure I'm seeing the original problem.

**Comment by jlebon** [comment]
@akiernan When testing #1668, make sure to also `rpm-ostree initramfs --enable` since the fix happens in the initramfs.

**Comment by jlebon** [comment]
https://bodhi.fedoraproject.org/updates/ostree-2018.6-4.fc28

**Comment by akiernan** [comment]
@jlebon Thanks - it wasn't that, but I think I've found my problem, just testing it and I'll open a new ticket for it.

**Comment by nexfwall** [comment]
[Workaround](https://github.com/ostreedev/ostree/issues/1667#issuecomment-402308008) isn't worked for me. Because of `/var/home` mount, I think.

```
$ systemctl status workaround-ostree-issue-1667.service
● workaround-ostree-issue-1667.service
   Loaded: loaded (/etc/systemd/system/workaround-ostree-issue-1667.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2018-07-04 22:09:05 MSK; 3min 14s ago
  Process: 582 ExecStart=/bin/sh -c if findmnt -s -n -T "/var"; then echo "Enabling workaround"; umount /var; systemctl start --no-block var.mount; fi (code=exited, status=0/SUCCESS)
 Main PID: 582 (code=exited, status=0/SUCCESS)

июл 04 22:09:05 E101-Y52015IKBA sh[582]: /var   /dev/mapper/faw_y52015ikba-var ext4   defaults,discard
июл 04 22:09:05 E101-Y52015IKBA sh[582]: Enabling workaround
июл 04 22:09:05 E101-Y52015IKBA sh[582]: umount: /var: target is busy.
```

**Comment by jlebon** [comment]
We chatted on IRC, though for posterity:
You can download the RPMs from that Bodhi update and do:

```
$ rpm-ostree override replace ostree{,-grub2,-libs}-2018.6-4.fc28.x86_64
$ rpm-ostree initramfs --enable
```

**Comment by nexfwall** [comment]
Yes. Overriding packages fixing the issue completely.
