### ISSUE TITLE
min-free-space-percent '3%' would be exceeded,

### ISSUE THREAD

**Issue by cristifalcas** [ostreedev/ostree#1688]
I'm trying to build an ostree inside a docker container with fedora:27, but I'm getting this error:
```
error: While writing rootfs to mtree: Writing content object: min-free-space-percent '3%' would be exceeded, 34.1 MB more required
```
This is the relevant output:
```
[root@f74cb6435f69 fedora-atomic]# rpm-ostree compose tree --cachedir=/srv/cache --repo=/srv/ostree/$REPONAME fedora-atomic-kubernetes.json
......
Ignored user missing from new passwd file: root
New passwd entry: systemd-coredump
New passwd entry: dnsmasq
New passwd entry: gluster
Ignored user missing from new passwd file: root
New passwd entry: systemd-coredump

Committing: [=============] 100%
error: While writing rootfs to mtree: Writing content object: min-free-space-percent '3%' would be exceeded, 34.1 MB more required
[root@f74cb6435f69 fedora-atomic]# df
Filesystem                1K-blocks    Used Available Use% Mounted on
overlay                    20971520  622044  20349476   3% /
tmpfs                       8211396       0   8211396   0% /dev
tmpfs                       8211396       0   8211396   0% /sys/fs/cgroup
/dev/mapper/atomicos-root   5228544 4092100   1136444  79% /srv/ostree
/dev/mapper/docker-pool00 104802308 8795944  96006364   9% /etc/hosts
shm                           65536       0     65536   0% /dev/shm
```
I don't understand what free space it needs. It looks like it should have enough.

Version:
```
# rpm-ostree --version
rpm-ostree:
 Version: 2018.4
 Git: 15877401ad348c376735e62588a4e73e95f4df33
 Features:
  - compose
```

Best regards

**Comment by jlebon** [comment]
Can you try the compose again while monitoring the free disk usage (e.g. `watch -n 1 df`)? It's possible that the available value you see afterwards is after rpm-ostree cleaning up contexts/tmpdirs etc... 1136444 1K blocks is... ~1G? That might not be enough depending on the size of your compose.

You can also turn off the min free space protection by setting it to `0` in the config, e.g.:

```
echo "min-free-space-percent=0" >> /srv/ostree/$REPONAME/config
```

(Make sure it goes under the main `[core]` group in the config, which is the first and last group usually -- though if you added e.g. remotes, the above won't work directly).

Then you should be able to observe the `ENOSPC` directly.

**Comment by cristifalcas** [comment]
Hi,

So it's was the /srv/ dir that was growing until full. Thank you.

I don't understand why yet the /srv/ is only 5GB instead of 20, but I will
investigate this further.

Best regards,

**Comment by uajain** [comment]
@cristifalcas Did @jlebon answer you question?

In that case this might be closed.

**Comment by cristifalcas** [comment]
Sure. It was a mistake on my part. The /srv/ dir was mounted from the host, which had only 5GB.

Thank you
