### ISSUE TITLE
/var/.updated not deleted on deployment

### ISSUE THREAD

**Issue by akiernan** [ostreedev/ostree#1729]
Trying to use systemd's `ConditionNeedsUpdate=/var` it seems as if ostree-sysroot-deploy.c#L2557 isn't looking in the right directory when it unlinks the file, running through `strace`:

`597   unlinkat(12, "var/.updated", 0)   = -1 ENOENT (No such file or directory)`

whereas the file exists:

```
$ ls -l /var/.updated
-rw-r--r-- 1 root root 190 Jan  1  1970 /var/.updated```

**Comment by akiernan** [comment]
Debugging further, it looks like its an issue with separate `/var`

**Comment by cgwalters** [comment]
> Debugging further, it looks like its an issue with separate /var

Ah, right - we need to do the `unlinkat()` from the view of the *booted* deployment - but only if we're booted.  (Correctly handling `ostree admin --sysroot /path/to/os upgrade` is tricky with `/var` mounts, we would need to either mount it ourself, or perhaps require some external process to do so.  I'm honestly though not aware of anyone today doing upgrades like that)

Hmm.  I wonder if would somehow be cleaner to have our systemd generator for `/var` *reverse* things if it detects a `/var` mount by adding a bind mount from the `/var` device/mount to the `/sysroot/.../var`.

**Comment by cgwalters** [comment]
Working on a patch for this.

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/1730 - if you wouldn't mind reviewing and testing that'd be great!
