### ISSUE TITLE
pull: does `--mirror` along with `--commit-metadata-only` make sense?

### ISSUE THREAD

**Issue by dustymabe** [ostreedev/ostree#1756]
I was trying to pull commit metadata for a ref so I could investigate the package list and it didn't seem to be working. My script was running `ostree pull --mirror --commit-metadata-only onerepo:fedora/28/x86_64/workstation` where onerepo was https://dl.fedoraproject.org/atomic/repo/. 

When I ran it with `--mirror` the `ostree log` showed an old commit:

```
$ ostree log onerepo:fedora/28/x86_64/workstation  | head                                                  
commit 97a646fbd7895e6b2bc0ae6ee117b8be218819917db6fe682eb3303fe8b6ae07
ContentChecksum:  f0776717f6528e3d20a414f47b8572fbcc2c41274ec55a9ae99cb436bb500838                                                                    
Date:  2018-07-30 16:09:46 +0000
Version: 28.20180730.1
(no subject)

<< History beyond this commit not fetched >>
```

after running without `--mirror` it had the new info:

```
$ ostree log onerepo:fedora/28/x86_64/workstation  | head                                                  
commit 44818a6b79461901fcf351536eb127f6a68ab9e4b4054d01aa35a57cc6a34756
ContentChecksum:  ca0fcefdc407b27def8d3e65de950bd278800c437fe898381c7c65606dcc080d                                                                    
Date:  2018-10-12 20:05:43 +0000
Version: 28.20181012.0
(no subject)

<< History beyond this commit not fetched >>

```

Not sure if there is a bug here or I'm doing something dumb, but figured it would be worth clarifying in case there is a bug. My desktop is still on f27 so the ostree version I'm at is: `ostree-2018.6-1.fc27.x86_64`

**Comment by cgwalters** [comment]
When you `pull --mirror`, the written ref is stored in `refs/heads/` - there's no `onerepo:` prefix.  Try `ostree log fedora/28/x86_64/workstation`.

> My desktop is still on f27 so the ostree version I'm at is: ostree-2018.6-1.fc27.x86_64

In this case the version doesn't matter, but you can use ostree from a container right?

**Comment by dustymabe** [comment]
> When you `pull --mirror`, the written ref is stored in `refs/heads/` - there's no `onerepo:` prefix. Try `ostree log fedora/28/x86_64/workstation`.

That was it. Thanks! I knew it was something simple.

> 
> > My desktop is still on f27 so the ostree version I'm at is: ostree-2018.6-1.fc27.x86_64
> 
> In this case the version doesn't matter, but you can use ostree from a container right?

yep. I was just adding that info in case there was a bug that had been fixed since. I'm working to get that machine over to silverblue so I'll be doing more things in a container.
