### ISSUE TITLE
Exec script OSTree post-deploy

### ISSUE THREAD

**Issue by AdrianVovk** [ostreedev/ostree#1792]
Hello!

I was wondering if there is a way to execute a systemd service when I reboot into a new deployment.

I can have a systemd path unit that invokes a target and then have whatever services I want. 

This would be nice to, for example, call bootctl to update the bootloader after an upgrade.

Thanks! Happy holidays!

**Comment by cgwalters** [comment]
See ce58307757c9e42b2d949d1566038174bccd4fe1

**Comment by AdrianVovk** [comment]
Thank you. This is just what I needed!
