### ISSUE TITLE
About ostree-remount

### ISSUE THREAD

**Issue by Thesola10** [ostreedev/ostree#1807]
I'd like to know the specific technical reason behind the fact that `ostree-remount.service` is marked as "Remain after exit", even though the program only fires once to remount the current tree to the latest deployment (as I assume it does).
For context, I am currently transforming an Arch Linux install into an OStree repository, and I use a temporary checkout to install packages using `pacman`, which I then commit into the repo, and then deploy again. I am interested in `ostree-remount`, as it could theoretically allow me to reflect new packages without a reboot.

**Comment by Thesola10** [comment]
To admins, please set the question label and drop the [question] prefix in the title

**Comment by AdrianVovk** [comment]
AFAIK, ostree-remount does nothing to the important parts of the system... (AKA /usr). That is all handled in the initramfs.

**Comment by cgwalters** [comment]
We should add libostree built-in support for live changes; this is totally possible but needs careful design.  See https://github.com/projectatomic/rpm-ostree/issues/639

(Today, libostree is just a hardlink manager; there's not much "mounting" other than bind mounts)

**Comment by Thesola10** [comment]
I see. Currently, I get around the live updates problem by bind-mounting `/usr` across checkouts. Usually works without a hitch, since I keep the bind-mount read-only.

Also, maybe the hardlink system should be hardened by preventing programs from directly rewriting them, or detaching them as soon as a change is detected?

**Comment by cgwalters** [comment]
Just bind mounting `/usr` is currently a bit dangerous as it may leave libostree confused about `/usr/lib/ostree-boot` and the state of kernels.  This bit us in rpm-ostree, see https://github.com/projectatomic/rpm-ostree/issues/1495
