### ISSUE TITLE
Multiple arguments don’t get checked and handled

### ISSUE THREAD

**Issue by fbruetting** [ostreedev/ostree#1816]
`ostree-2019.1-3.fc29.x86_64`

When I enter `sudo ostree admin pin 0 1`, deployment 0 gets pinned, but deployment 1 is not respected at all. I think it would be good if all arguments would be checked for correctness and then either an error should be thrown (because just one argument gets handled), or it should handle all arguments, if they get accepted. Don’t know if this also applies for other ostree commands.

The thing is, when I enter a command and it runs through without throwing an error, I assume that everything is done like expected. And as multiple arguments are widespread, I also would assume that this is handled correctly. Sadly, this isn’t the case. Not a big bug of course, but maybe this could save a deployment which instead might get overwritten some time in the future somewhere, and I just like correct and reliable tools, especially if they administer my system. ;)

**Comment by rfairley** [comment]
Thanks for reporting!

Can reproduce the behavior with the current master. I don't see harm in allowing specifying multiple indices to pin/unpin. Additionally, a message `Deployment INDEX is now pinned` could be printed for each one, and print an error if the pin failed. Same applies for unpinning.

Can check for other commands as well where multiple items could be specified to see if it's a CLI layer change.

**Comment by dustymabe** [comment]
@rfairley - does this seem like a good first issue for someone? If so we can give to a new contributor

**Comment by rfairley** [comment]
@dustymabe yes - the pinning part would be a good first issue. The command handling logic in `src/ostree/ot-admin-builtin-pin.c` would need changing to take multiple args for deployment indices.

From there, a next (separate) issue that builds on that could be to look for other commands where we might also want multiple arg handling.
