### ISSUE TITLE
Clarify security properties of static deltas

### ISSUE THREAD

**Issue by mwleeds** [ostreedev/ostree#1819]
The documentation for `ostree_repo_sign_delta` says `This function is deprecated, sign the summary file instead.` But commit signatures and signed repo metadata are now used instead of summary signatures for repositories which have a collection ID set.

Commit d06163038ff1ca407027d08e0f3c7d04c802810d ensured that the commits in deltas are GPG verified, so there's no security hole here right? I don't understand static deltas well enough to answer that question myself.

**Comment by cgwalters** [comment]
The other half of this was 4c8fc92aa02dbbd474009b61ca54cf49ef29da56

So yeah, deltas now follow the same security properties as other pulls.
