### ISSUE TITLE
Maybe use mmap for summaries

### ISSUE THREAD

**Issue by hughsie** [ostreedev/ostree#1855]
In GNOME Software (using libflatpak, using libostree) we get reports of large memory usage. On my system there's nearly 10Mb of heap memory allocated by `_ostree_repo_load_cache_summary_if_same_sig()` which seems to use `read()` via `glnx_fd_readall_malloc()` via `glnx_fd_readall_bytes()`.

Is there a reason we have to use heap memory rather than mmap'ing the file? GBytes is smart enough to do `g_mapped_file_new()` -> `g_mapped_file_get_bytes()` without actually copying the data. If this sounds interesting of there's not a good technical reason for the heap allocation I can have a go at a PR for this. Thanks.

**Comment by cgwalters** [comment]
We already have internally `ot_fd_readall_or_mmap()`.

**Comment by cgwalters** [comment]
That said, I think it'd be better for gnome-software to not be a persistent process.

**Comment by hughsie** [comment]
> That said, I think it'd be better for gnome-software to not be a persistent process.

I don't disagree, but we don't have systemd user sessions yet, and we're not at the point we can load packagekitd and flatpak in less than one second. We're getting there, but all the bits are not in place yet.
