### ISSUE TITLE
Switch to fuse 3.x

### ISSUE THREAD

**Issue by Keruspe** [ostreedev/ostree#1881]
From the release notes of libfuse 2.9.9: 

```
Note: This is a maintenance release from the 2.9 branch of libfuse. Users are encouraged to transition to the actively developed libfuse 3.x.
```

**Comment by ovitters** [comment]
Hi, any progress on this? Mageia would appreciate if fuse2 was not used anymore. Mixing fuse2 and fuse3 causes some issues. E.g. https://bugs.mageia.org/show_bug.cgi?id=28655. It would be easier if everything was fuse3.

**Comment by cgwalters** [comment]
Ultimately, `rofiles-fuse` is an optional component; it's not strictly related to or required by ostree.  It looks like `flatpak-builder` supports its use, but will fall back if it's not present.

See also https://github.com/ostreedev/ostree/issues/2281 - basically `rofiles-fuse` should be considered deprecated for modern systems that support unprivileged overlayfs mounts.

But yeah I don't care about using modern ostree on e.g. rhel7 anymore so we could indeed do a port.

**Comment by ovitters** [comment]
Ah, good to know! For most distributions I think requiring a new kernel is ok. I'll go for disabling this component, though need to check (ask) if unprivileged overlayfs mounts are enabled by default.

**Comment by cgwalters** [comment]
I may try to move it out of the `ostree` package in Fedora to a separate `ostree-rofiles-fuse` or so.

**Comment by kloczek** [comment]
What about new release? :)
