### ISSUE TITLE
ostree-2019.3 spams terminal with gpg-connect-agent messages for every flatpak operation

### ISSUE THREAD

**Issue by kparal** [ostreedev/ostree#1907]
With `ostree-2019.3-3.fc30.x86_64` I see this:
```
$ flatpak install peek
Looking for matches…
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
Found similar ref(s) for ‘peek’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.uploadedlobster.peek/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
Required runtime for com.uploadedlobster.peek/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.32) found in remote flathub
Do you want to install it? [Y/n]: n
```

With `ostree-2019.2-1.fc30.x86_64` I see this:
```
$ flatpak install peek
Looking for matches…
Found similar ref(s) for ‘peek’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.uploadedlobster.peek/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y
Required runtime for com.uploadedlobster.peek/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.32) found in remote flathub
Do you want to install it? [Y/n]: n
```

Compare for yourself which one looks more readable. The gpg-agent messages are printed out **very** frequently, for a single `flatpak update` command that has "nothing to do", I saw about 20 lines of gpg-agent messages (depends on what's happening in the background, usually it's just 3-6 lines of messages).

This is happening on Fedora 30, but Arch users see it as well:
https://bbs.archlinux.org/viewtopic.php?id=248745

This happens regardless of `gpg-agent` actually running or not running in the background.

**Comment by cgwalters** [comment]
Likely fallout from https://github.com/ostreedev/ostree/pull/1799

**Comment by cgwalters** [comment]
@dbnicholson

**Comment by dbnicholson** [comment]
Sorry, I have a patch for it for a different thing I was working on. I tried to check if it was needed for any current operations, but it didn't seem like it. The issue is that `gpg-agent` doesn't get launched for all gpgme operation and `gpg-connect-agent` helpfully tells you about it.

Anyways, I'll split my patch out to a separate PR. Sorry for not sending it when I first noticed it.
