### ISSUE TITLE
Layered initramfs

### ISSUE THREAD

**Issue by darkmuggle** [ostreedev/ostree#1936]
For CoreOS we have need for networking in the Initramfs for encrypted disks with Clevis/Tang unlock. The problem, though, is that we cannot reliably assume that the DHCP, as the user may have on-disk networking. In talking with @cgwalters the idea of having a layered Initramfs that provides certain files (such as Network configuration), would help to solve this use case and other others.

**Comment by cgwalters** [comment]
Today libostree doesn't know how to build initramfs images, rpm-ostree does.  Moving to https://github.com/coreos/rpm-ostree/issues/1930
