### ISSUE TITLE
ostree-trivial-httpd --daemon --autoexit no longer works

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#1941]
I'm not sure when this started happening, but `ostree-trivial-httpd` no longer automatically exits when run with `--daemon --autoexit` as is done throughout the test suite. Not a big issue since this is a test program, but it leaves around a bunch of daemons. If you run the test suite repeatedly, eventually you'll hit a file limit and get weird failures.

I poked around at this for a while. It seems this has something to do with the forking since `--autoexit` works when not using `--daemon`. I added some logging in the file monitor handler and it never receives any events with `--daemon`. I played around with moving the `fork()` earlier so that both the soup server and the file monitor would use the same thread default context. The soup server was still able to handle requests but still nothing on the file monitor.

Reproducer from a built checkout:
```
rm -rf tmp && mkdir tmp && ./ostree-trivial-httpd -d --autoexit --log-file=log tmp
rm -rf tmp
cat log
```
You'll see that there's no `Directory removed, exiting` message. Likewise `pgrep -f ostree-trivial-httpd` will show the running process.

Any ideas?

**Comment by pwithnall** [comment]
Is it possible to bisect to find when it started happening?

The [GLib documentation](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#mainloop-states) says that fork-without-exec is not compatible with the continued operation of a `GMainContext`. I don’t know the details for this (it predates me).

If you were going to move the `fork()` call earlier, your best bet would be before *any* GLib calls are made, so it’s before any `GMainContext` is constructed. But this is something I’ve never had to deal with before so I could be completely wrong.

**Comment by dbnicholson** [comment]
Well, I figured out one issue. When `--log-file` is specified to a real file, then a `GFileOutputStream` is opened before the fork. From what I can tell, this causes the worker context to be created in glib, which then starts a thread to iterate the context. When the parent exits after the fork, this thread is gone, so there's nothing iterating the worker context.

I wrote a test program in https://gist.github.com/dbnicholson/15f401935d5b34dd3bac9ea3fc069918 that does many of the same things as `ostree-trivial-httpd`. However, I added a `--log-after-fork` option that delays opening the log file until after the fork.

Here's running in non-daemon mode with `rmdir tmp` from another shell:
```
$ mkdir -p tmp && ./monitor-bug tmp 
Monitoring 'tmp'
Received event 2
Directory removed, exiting
$ mkdir -p tmp && ./monitor-bug -l log tmp 
$ cat log 
Monitoring 'tmp'
Received event 2
Directory removed, exiting
```
Now in daemon mode with logging to stdout.
```
$ mkdir -p tmp && ./monitor-bug -d -p pid tmp && rmdir tmp
Monitoring 'tmp'
Received event 2
Directory removed, exiting
```
In daemon mode logging to a file:
```
$ mkdir -p tmp && ./monitor-bug -d -p pid -l log tmp && rmdir tmp
$ cat log 
Monitoring 'tmp'
```
It didn't exit. For reasons I don't totally understand, `SIGKILL` is needed to kill it.
```
$ pgrep -a -F pid
26812 ./monitor-bug -d -p pid -l log tmp
$ pkill -F pid
$ pgrep -a -F pid
26812 ./monitor-bug -d -p pid -l log tmp
$ pkill -9 -F pid
$ pgrep -a -F pid
```
Finally, with the log file opening delayed until after the fork.
```
$ mkdir -p tmp && ./monitor-bug -d -p pid -l log --log-after-fork tmp && rmdir tmp
$ cat log 
Monitoring 'tmp'
Received event 2
Directory removed, exiting
$ pgrep -a -F pid
```
So, I think `ostree-trivial-httpd` can be changed so that the log file is opened after the fork. There's only one issue there - if the log file can't be opened then the parent won't exit with an error. Probably for a test utility like this it doesn't matter, but you could probably open a pipe and have the parent wait until the child sends back an exit value after the post-fork setup tasks.

**Comment by dbnicholson** [comment]
And finally, when I was back to playing with `ostree-trivial-httpd`, for some reason the monitoring doesn't work at all with an empty directory.
```
$ rm -rf tmp && mkdir -p tmp && ./ostree-trivial-httpd --autoexit tmp &
[1] 27478
$ rm -rf tmp/
[ 4:55 PM dan:~/src/ostree (upstream)]
$ jobs
[1]+  Running                 rm -i -rf tmp && mkdir -p tmp && ./ostree-trivial-httpd --autoexit tmp &
$ kill %1
[1]+  Terminated              rm -i -rf tmp && mkdir -p tmp && ./ostree-trivial-httpd --autoexit tmp
```
With a file in the directory:
```
$ rm -rf tmp && mkdir -p tmp && touch tmp/foo && ./ostree-trivial-httpd --autoexit tmp &
[1] 27537
$ rm -rf tmp/
[1]+  Done                    rm -i -rf tmp && mkdir -p tmp && touch tmp/foo && ./ostree-trivial-httpd --autoexit tmp
```
I don't know what the deal is there.

**Comment by cgwalters** [comment]
>  if the log file can't be opened then the parent won't exit with an error. 

Parent can pass the fd for the logfile to the child, right?

**Comment by dbnicholson** [comment]
> > if the log file can't be opened then the parent won't exit with an error.
> 
> Parent can pass the fd for the logfile to the child, right?

The fd is still open in the child. The issue is the use of `GFile` and `GOutputStream`, though. It could be switched to standard read/write, though.

Anyways, #1948 fixes it the way I described by forking earlier and having the parent wait on a pipe until the setup is done.
