### ISSUE TITLE
Tests fail when C.UTF-8 locale is unavailable

### ISSUE THREAD

**Issue by akiernan** [ostreedev/ostree#1964]
I've been getting the test suite running in OpenEmbedded and the patches carried by other distros to add C.UTF-8 to glibc don't exist there.

The test suite then fails because we end up hitting:

```
    export LC_ALL=C
```

https://github.com/ostreedev/ostree/blob/master/tests/libtest-core.sh#L45

which causes tests like `test-fsck-collections.sh` to fail because we don't generate left and right single quotes for tests such as

```
assert_file_has_content fsck-error "Commit has no requested ref ‘new-ref’ in ref binding metadata (‘ref1’)"
```

The `LC_ALL=C` default seems like it's just wrong, but I'm not sure what the best approach here is...

Options I can immediately see:

* delete the whole locale thing from `libtest-core.sh` altogether
* check for some additional locales like `en_US.UTF-8`

**Comment by cgwalters** [comment]
> check for some additional locales like en_US.UTF-8

I like this option.

**Comment by akiernan** [comment]
#1965

**Comment by cgwalters** [comment]
This was fixed I believe, thanks!
