### ISSUE TITLE
1019.5: ostree isn't LTO ready (fails on linking)

### ISSUE THREAD

**Issue by kloczek** [ostreedev/ostree#1979]
When LTO is not in use everything is fine

<pre>[tkloczko@barrel libostree-2019.5]$ make
make  all-recursive
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libostree-2019.5&apos;
Making all in .
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libostree-2019.5&apos;
CPPFLAGS=&quot;&quot; CFLAGS=&quot;-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none&quot; LDFLAGS=&quot;-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin&quot; CC=&quot;gcc&quot; PKG_CONFIG=&quot;/usr/bin/x86_64-redhat-linux-gnu-pkg-config&quot; GI_HOST_OS=&quot;&quot; DLLTOOL=&quot;false&quot; CC=gcc /usr/bin/g-ir-scanner   --namespace=OSTree --nsversion=1.0 --libtool=&quot;/bin/sh ./libtool&quot;  --include=Gio-2.0 --pkg-export=ostree-1   --library=libostree-1.la --warn-all --identifier-prefix=Ostree --symbol-prefix=ostree  --cflags-begin -std=gnu99 -fno-strict-aliasing -pipe -Wall -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=format=2 -Werror=format-security -Werror=format-nonliteral -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=switch -Werror=overflow -Werror=int-conversion -Werror=parentheses -Werror=undef -Werror=incompatible-pointer-types -Werror=misleading-indentation -Werror=missing-include-dirs -Werror=aggregate-return -Wstrict-aliasing=2 -Werror=unused-result -I./bsdiff -I./libglnx -I./src/libotutil -I./src/libostree -I./src/libostree -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -fvisibility=hidden &apos;-D_OSTREE_PUBLIC=__attribute__((visibility(&quot;default&quot;))) extern&apos;      -I/usr/include/libmount    --cflags-end  src/libostree/ostree.h src/libostree/ostree-async-progress.h src/libostree/ostree-autocleanups.h src/libostree/ostree-core.h src/libostree/ostree-dummy-enumtypes.h src/libostree/ostree-mutable-tree.h src/libostree/ostree-repo.h src/libostree/ostree-types.h src/libostree/ostree-repo-file.h src/libostree/ostree-diff.h src/libostree/ostree-gpg-verify-result.h src/libostree/ostree-sepolicy.h src/libostree/ostree-sysroot.h src/libostree/ostree-sysroot-upgrader.h src/libostree/ostree-deployment.h src/libostree/ostree-bootconfig-parser.h src/libostree/ostree-repo-deprecated.h src/libostree/ostree-ref.h src/libostree/ostree-remote.h src/libostree/ostree-repo-finder.h src/libostree/ostree-repo-finder-avahi.h src/libostree/ostree-repo-finder-config.h src/libostree/ostree-repo-finder-mount.h src/libostree/ostree-repo-finder-override.h src/libostree/ostree-kernel-args.h src/libostree/ostree-version.h src/libostree/ostree-async-progress.c src/libostree/ostree-cmdprivate.h src/libostree/ostree-cmdprivate.c src/libostree/ostree-core.c src/libostree/ostree-dummy-enumtypes.c src/libostree/ostree-checksum-input-stream.c src/libostree/ostree-checksum-input-stream.h src/libostree/ostree-chain-input-stream.c src/libostree/ostree-chain-input-stream.h src/libostree/ostree-lzma-common.c src/libostree/ostree-lzma-common.h src/libostree/ostree-lzma-compressor.c src/libostree/ostree-lzma-compressor.h src/libostree/ostree-lzma-decompressor.c src/libostree/ostree-lzma-decompressor.h src/libostree/ostree-rollsum.h src/libostree/ostree-rollsum.c src/libostree/ostree-varint.h src/libostree/ostree-varint.c src/libostree/ostree-linuxfsutil.h src/libostree/ostree-linuxfsutil.c src/libostree/ostree-diff.c src/libostree/ostree-mutable-tree.c src/libostree/ostree-ref.c src/libostree/ostree-remote.c src/libostree/ostree-repo.c src/libostree/ostree-repo-checkout.c src/libostree/ostree-repo-commit.c src/libostree/ostree-repo-pull.c src/libostree/ostree-repo-libarchive.c src/libostree/ostree-repo-prune.c src/libostree/ostree-repo-refs.c src/libostree/ostree-repo-traverse.c src/libostree/ostree-repo-file.c src/libostree/ostree-repo-file-enumerator.c src/libostree/ostree-repo-file-enumerator.h src/libostree/ostree-sepolicy.c src/libostree/ostree-sysroot.c src/libostree/ostree-sysroot-cleanup.c src/libostree/ostree-sysroot-deploy.c src/libostree/ostree-sysroot-upgrader.c src/libostree/ostree-impl-system-generator.c src/libostree/ostree-bootconfig-parser.c src/libostree/ostree-deployment.c src/libostree/ostree-bootloader.h src/libostree/ostree-bootloader.c src/libostree/ostree-bootloader-grub2.h src/libostree/ostree-bootloader-grub2.c src/libostree/ostree-bootloader-zipl.h src/libostree/ostree-bootloader-zipl.c src/libostree/ostree-bootloader-syslinux.h src/libostree/ostree-bootloader-syslinux.c src/libostree/ostree-bootloader-uboot.h src/libostree/ostree-bootloader-uboot.c src/libostree/ostree-repo-static-delta-core.c src/libostree/ostree-repo-static-delta-processing.c src/libostree/ostree-repo-static-delta-compilation.c src/libostree/ostree-repo-static-delta-compilation-analysis.c src/libostree/ostree-bloom.c src/libostree/ostree-repo-finder.c src/libostree/ostree-repo-finder-avahi.c src/libostree/ostree-repo-finder-config.c src/libostree/ostree-repo-finder-mount.c src/libostree/ostree-repo-finder-override.c src/libostree/ostree-kernel-args.c src/libostree/ostree-libarchive-input-stream.h src/libostree/ostree-libarchive-input-stream.c src/libostree/ostree-tls-cert-interaction.c src/libostree/ostree-tls-cert-interaction.h src/libostree/ostree-gpg-verifier.c src/libostree/ostree-gpg-verifier.h src/libostree/ostree-gpg-verify-result.c src/libostree/ostree-fetcher.h src/libostree/ostree-fetcher-util.h src/libostree/ostree-fetcher-util.c src/libostree/ostree-fetcher-uri.c src/libostree/ostree-metalink.h src/libostree/ostree-metalink.c src/libostree/ostree-fetcher-curl.c src/libostree/ostree-soup-uri.c src/libostree/ostree-soup-form.c libostree-1.la Makefile --output OSTree-1.0.gir
src/libostree/ostree-repo-deprecated.h:28: Warning: OSTree: symbol=&apos;G_GNUC_DEPRECATED_FOR&apos;: Skipping foreign symbol from namespace Gio
g-ir-scanner: link: /bin/sh ./libtool --mode=link --tag=CC gcc -o /home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/OSTree-1.0 -export-dynamic -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none /home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/OSTree-1.0.o -L. libostree-1.la -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -lglib-2.0 -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin
libtool: link: gcc -o /home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/.libs/OSTree-1.0 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none /home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/OSTree-1.0.o -Wl,--export-dynamic -pthread -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--export-dynamic  -L. ./.libs/libostree-1.so -L/usr/lib64 -lgpg-error -lgpgme -llzma -lz -lcrypto -larchive -lsystemd -lcurl -lmount -lselinux -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -pthread
Invalid GType function: &apos;ostree_async_progress_get_type&apos;
Failed to find symbol &apos;ostree_async_progress_get_type&apos;
Command &apos;[&apos;/home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/OSTree-1.0&apos;, &apos;--introspect-dump=/home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/functions.txt,/home/tkloczko/rpmbuild/BUILD/libostree-2019.5/tmp-introspectygdpfghe/dump.xml&apos;]&apos; returned non-zero exit status 1.
make[2]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:156: OSTree-1.0.gir] Error 1
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libostree-2019.5&apos;
make[1]: *** [Makefile:7369: all-recursive] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libostree-2019.5&apos;
make: *** [Makefile:3073: all] Error 2
</pre>

**Comment by cgwalters** [comment]
Hm, this might be a generic issue with anything using gobject-introspection.  Though, that error is odd. 
Oh, trying it locally there are other errors; I think we may be relying on "underlinking" and it's actually the `-Wl,-z,now` in combination with `-flto` that's getting us.

Will investigate more; for reference the reproducer here looks like:

```
$ env CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none" LDFLAGS="-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin" CC="gcc" ./autogen.sh --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc --with-openssl --with-curl
$ make
```

**Comment by cgwalters** [comment]
Googling the error message led me to [this post](https://www.reddit.com/r/Gentoo/comments/6b1dlc/plugin_needed_to_handle_lto_object_and_correct/) and using `AR=gcc-ar NM=gcc-nm RANLIB=gcc-ranlib` too fixes this for me.

**Comment by cgwalters** [comment]
So this may be something like `g-ir-scanner` not picking up tooling overrides?  There's a related mess here with g-i using the distutils compiler wrappers which often makes it want to prefer the tooling from how g-i itself was built.

**Comment by kloczek** [comment]
> Googling the error message led me to [this post](https://www.reddit.com/r/Gentoo/comments/6b1dlc/plugin_needed_to_handle_lto_object_and_correct/) and using `AR=gcc-ar NM=gcc-nm RANLIB=gcc-ranlib` too fixes this for me - _edit_ with `--disable-introspection`.

Issue is that I'm using those variables when I'm using LTO:
Here is exact set ov variables used as settings which I'm injecting in env variables.
```
$ rpm -E %set_build_flags

        export CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none}";
        export CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none}";
        export FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none}";
        export FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none}";
        export LDFLAGS="${LDFLAGS:--Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin}";
        export AR="/usr/bin/gcc-ar" RANLIB="/usr/bin/gcc-ranlib" NM="/usr/bin/gcc-nm";
        export CC="gcc" CXX="g++"
```

**Comment by kloczek** [comment]
Closing.
Looks like latest version is OK.
