### ISSUE TITLE
grub finding deployment

### ISSUE THREAD

**Issue by damianatorrpm** [ostreedev/ostree#1982]
the menuentry in /boot/grub2/grub.cfg looks like this:
```
linux16 /ostree/$deployment/vmlinuz-5.3.14-300.fc31.x86_64 resume=UUID=swap_uuid rhgb quiet root=UUID=root_uuid ostree=/ostree/boot.1/$os/$deployment/1 mitigations=off iommu=soft
initrd16 /ostree/$deployment/initramfs-5.3.14-300.fc31.x86_64.img
```
```
# ls /ostree
boot.1  boot.1.1  deploy  repo
```
How does grub know to look into boot.1 directory for $deployment ? 
(Good thing it does) Why does this work?

**Comment by cgwalters** [comment]
Because ostree writes the `ostree=` entry in the kernel arguments when it's generating the bootloader configs.

(Everything is OK?  Any reason to keep this issue open?)

**Comment by damianatorrpm** [comment]
No reason to keep this open (perhaps I should direct a similar question rather to the mailing list next time?)

**Comment by damianatorrpm** [comment]
Add a bit more details here (there is no problem with ostree in this case).
Anaconda for example is not working too well in regards of following non automatic partitioning etc.
Also it can not install a different image except if using kickstart for example.

So I got a deployment from desktop installation to usb stick.
Grub works not 100% properly (installed via grub2-install since:)
```
bootver=$(readlink $NEW_SYSROOT/boot/loader)
_OSTREE_GRUB2_BOOTVERSION=${bootver#*.} ostree admin instutil grub2-generate
```
`grub2.c:172:_ostree_bootloader_grub2_generate_config: assertion failed: (grub2_boot_device_id != NULL)`

grub shows up and has this argument
` ostree=/ostree/boot.1/$os/$deployment/1
`

although when trying to boot the entry it complains that it can not find the kernel which must be loaded first and is not in that directory 

changing:
```
linux16 /ostree/$deployment/vmlinuz-5.3.14-300.fc31.x86_64 
initrd16 /ostree/$deployment/initramfs-5.3.14-300.fc31.x86_64.img
```

to:

```
linux16 /boot/ostree/$deployment/vmlinuz-5.3.14-300.fc31.x86_64 
initrd16 /boot/ostree/$deployment/initramfs-5.3.14-300.fc31.x86_64.img
```
and leaving the ostree= kernel arg intact boots it up though

**Comment by damianatorrpm** [comment]
export GRUB_ENABLE_BLSCFG=true
After doing this during grub install the entries changed slightly =>
the kernel and initrd had now the prefix $(root)/
At that moment I realized that the kernel and initrd files on the
desktop are on the boot partition which is required by anaconda IIRC
so the root partition on the desktop install, actually has these files
(since it's a different partition but mounted into / at runtime as
/boot)

On the created stick I have no boot partition hence it cannot find it
by default.

So my question changes => Is this a bug?
grub2-mkconfig or the ostree grub.d magic should recognize not having
a separate boot partition and adjust the entries accordingly.

**Comment by jlebon** [comment]
Ahh didn't connect this issue with the mailing list thread until now. Cross-referencing: https://mail.gnome.org/archives/ostree-list/2019-December/msg00001.html

I replied to you there: https://mail.gnome.org/archives/ostree-list/2019-December/msg00008.html.

Let's try to keep this conversation in one place? :)

**Comment by damianatorrpm** [comment]
@jlebon Jonathan Thank you for the links!
Closing as duplicate. https://github.com/ostreedev/ostree/issues/1452
