### ISSUE TITLE
docs: state somewhere that remotely pulled commits will be assigned with ref <remote>:<branch>

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2010]
I called the command:

```
$ ostree pull origin foo
```

and was surprised that i couldn't find the newly downloaded commits after invoking:

```
$ ostree log foo
```

it's confusing.

Finally, i discovered that there is a new ref created: `origin:foo` under which i could find the commit.

It's not described in man page or anywhere. It would be good to document this.

**Comment by cgwalters** [comment]
Right, you use `pull --mirror` to avoid this.  This behavior is like what `git` does FWIW.

**Comment by clime** [comment]
Yes, that's possible, anyway, I created this PR https://github.com/ostreedev/ostree/pull/2012 to add some info about this. Hope, it's ok.

**Comment by clime** [comment]
This is now resolved by PR #2012 Thank you for merging!
