### ISSUE TITLE
why commits contain info from which branch they come from?

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2023]
Hello,

when I try to apply to pull commit which was originally from branch foo into branch master, I get the following error (this happened during upgrade):

```
$ sudo ostree admin upgrade
error: Commit 1e3ce300a8eb401b3c8f807f0eaf5fcf7283fffd76c8ecd57af4099ff6a9433c: Commit has no requested ref 'master' in ref binding metadata ('foo')
```

It seems commits contain branch name inside their metadata and that prevents pulling them into branch of different name?

I am interepretting things correctly? I wouldn't expect this to be the case.

**Comment by clime** [comment]
Also, how can I display the commit metadata so that I can see what branch each commit is "attached" too? When I `cat` it, I mostly see only binary.

**Comment by cgwalters** [comment]
It's to prevent "side-grade" attacks.

> Also, how can I display the commit metadata so that I can see what branch each commit is "attached" too?

`ostree show --raw` and `ostree show --print-metdata-key` - more is available via the C API.

**Comment by cgwalters** [comment]
If you don't want this behavior, use `ostree commit --no-bindings` on the server side; we should also expose a client side option to ignore it (it's in the API though).

**Comment by clime** [comment]
> If you don't want this behavior, use `ostree commit --no-bindings` on the server side; we should also expose a client side option to ignore it (it's in the API though).

Great, thank you! And the commands above work for me as well!

**Comment by srd424** [comment]
For anyone else who stumbles on this issue, I note `ostree pull-local` (now?) has a `--disable-verify-bindings` option too, which helps if you've got an existing set of commits.

**Comment by dbnicholson** [comment]
I added that in one of the 2021 releases because we had lots of old commits from before ref bindings existed and I was trying to migrate them to a different repo.
