### ISSUE TITLE
custom title in boot loader entries

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2031]
Hello,

is it possible to specify what title should look like in the generated grub entries under /boot/loader/entries/. I would like to add a custom branding there but it is not possible because `sudo ostree admin upgrade` always overwrites all the entires there and it resets the title for each of them.

Is there any option to customize the generated title?

Thank you

**Comment by jlebon** [comment]
If you're doing a derivative with e.g. its own name, you likely want to change `/etc/os-release`, which is where libostree sources the OS name from when creating the bootloader entries.

**Comment by clime** [comment]
Ah, how could I missed that...Thank you very much!

**Comment by clime** [comment]
Sorry, I will reopen just for one more question.

I would like to also get ostree commit hash into the title. Is there a way to do that?

**Comment by jlebon** [comment]
Not directly. OSTree emphasizes the version string instead since that's much more meaningful to humans than commit hashes. :)

**Comment by clime** [comment]
Ok, thank you! I think this should be possible but I can live without it.
