### ISSUE TITLE
ability to compare commit in tree against a directory content

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2032]
Hello,

is there an option to compare a commit in ostree repo against a checked-out directory. I would like to see the "staged" changes before I actually do the commit, when doing changes manually.

I am asking mainly out of curiosity - if there is such a feature already (an I overlooked it) or if not, is something like that planned to be implemented?

Thank you.

**Comment by jlebon** [comment]
Check out `ostree-diff(1)`.

**Comment by clime** [comment]
It's not clear for the man pages that the last argument needs to be e.g. prefixed with `./` to be recognized as a directory and not as ref. E.g.

```
$ ostree diff master dir
error: Refspec 'dir not found
```

whereas:
```
$ ostree diff master ./dir
```
works.

It's nice that you send me to the command that i already examined before but the documentation there isn't the best really. But glad the functionality is there, anyway.

**Comment by jlebon** [comment]
Agreed documentation could be improved. I opened https://github.com/ostreedev/ostree/pull/2034.

**Comment by clime** [comment]
Great, thank you very much!
