### ISSUE TITLE
Parent commits pulled via `--depth=N` left as partial

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2035]
I have tarballed ostree repository in archive mode with a few commits. When I try to pull from that repository, `state/*.commitpartial` files are created for the pulled commits. Why?

When I remove the `.commitpartial` files, `ostree fsck` succeeds.

**Comment by clime** [comment]
Actually, the one commit that is missing among the `state/*.commitpartial` files is the commit that i am pulling. But the ones that got pulled addittionally by `--depth=` switched are put there.

So the problem likely is that this code here: https://github.com/ostreedev/ostree/blob/master/src/libostree/ostree-repo-pull.c#L4717 does not consider that commits can also be pulled through ingeritance (only my guess :)).

**Comment by jlebon** [comment]
Thanks, good catch! Fixed in: https://github.com/ostreedev/ostree/pull/2036.

**Comment by clime** [comment]
Wow, that was fast! Thanks!

**Comment by clime** [comment]
This might possibly be the same problem: https://github.com/ostreedev/ostree/issues/2011
Although, I am not pulling a specific commit_id there like I did in this case. It still looks your fix could solve that case as well.
