### ISSUE TITLE
/var/ template

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2043]
Hello, is there a `/var` template - i.e. what directories should be created under `/var/` when a new sysroot is created?

How do I ensure that e.g. `/var/log/httpd` exists? httpd is failing if the directory does not exist. Is there a recommended solution for this problem if there isn't the `/var/` template?

Thank you :)
clime

**Comment by clime** [comment]
I can see `systemd-tmpfiles` are the solution.

**Comment by cgwalters** [comment]
See also https://github.com/coreos/rpm-ostree/blob/469e6e963a0b0874d29d529022541afa4062fe36/src/libpriv/rpmostree-importer.c#L687
