### ISSUE TITLE
Is it ok to have /etc -> /usr/etc symlink in a tree?

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2046]
Hello,

right now when I want to manually work with the tree (e.g. install packages), I always need to first create `/etc -> /usr/etc` symlink and then I delete it before commiting. Can I just leave it in the tree so that it is present upon a next checkout? Is it safe to leave it there with respect to deployments?

**Comment by jlebon** [comment]
Yeah, rpm-ostree composes encounter this too and simplify just keeps renaming `/usr/etc` to `/etc` and back.

> Can I just leave it in the tree so that it is present upon a next checkout?

You can try it and find out. :)  It's likely going to throw off the ostree deploy code which expects `/etc` to not exist before checking out `/usr/etc` to `/etc`.

**Comment by clime** [comment]
> Yeah, rpm-ostree composes encounter this too and simplify just keeps renaming `/usr/etc` to `/etc` and back.
> 
> > Can I just leave it in the tree so that it is present upon a next checkout?
> 
> You can try it and find out. :) It's likely going to throw off the ostree deploy code which expects `/etc` to not exist before checking out `/usr/etc` to `/etc`.

Yes, the error is:

```
error: Preparing /etc: Tree contain contains both /etc/ and /usr/etc/
```

Alright,good to now it is just not possible.
