### ISSUE TITLE
Delta pulls broken when repo has commitpartial

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#2053]
If we're pulling a commit using static deltas, and for some reason we have a commitpartial for the pulled commit, then when we save the commit from the static delta superblock and scan it we will trigger the scanning of the root dirtree and dirmeta in scan_commit_object() due to the is_partial check. 

This is not going to *break* anything, but it will mean we will download everything twice, both as delta parts and separate objects.

I think we need to disable the dirmeta/dirtree scanning if the commit came from the delta.

**Comment by alexlarsson** [comment]
For various reasons this was triggered in flatpak causing https://github.com/flatpak/flatpak/pull/3524

**Comment by jlebon** [comment]
Threw something up in https://github.com/ostreedev/ostree/pull/2054.
