### ISSUE TITLE
OSTree deploy writing grub config fails with 0 deployments

### ISSUE THREAD

**Issue by ninja18** [ostreedev/ostree#2124]
#1774 
This is the same problem as specified in this [issue](https://github.com/ostreedev/ostree/issues/1774) but it still looking for existing deployment instead of using the pending deployment to write the grub config

```
OT: Preparing transaction in repository 0x5640eeedf000
OT: Pushing lock non-blocking with timeout 30
OT: Creating repo lock table
OT: Opening repo lock file
OT: Push lock: state=unlocked, depth=0
OT: Locking repo shared
OT: Using new tmpdir staging-8a1f1569-0bb4-4ccb-9320-85ac3d360450-Ssg6VE
OT: Committing transaction in repository 0x5640eeedf000
OT: txn commit staging-8a1f1569-0bb4-4ccb-9320-85ac3d360450-Ssg6VE
OT: Popping lock non-blocking with timeout 30
OT: Pop lock: state=shared, depth=1
OT: Unlocking repo
Relabeling /var (no stamp file 'var/.ostree-selabeled' found)
OT: boot is ro: no
OT: Using bootloader: OstreeBootloaderGrub2
**
OSTree:ERROR:src/libostree/ostree-bootloader-grub2.c:366:_ostree_bootloader_grub2_write_config: assertion failed (deployments->len > 0): (0 > 0)
```
Note:
The ostree is built for debian using [deb-ostree-builder](https://github.com/dbnicholson/deb-ostree-builder)

**Comment by cgwalters** [comment]
The ideal is that you use the GRUB blsconfig patches, then set `bootloader=none`.  Then OSTree never tries to run `grub2-mkconfig`.  That's how https://github.com/coreos/coreos-assembler/blob/master/src/create_disk.sh works.

**Comment by ninja18** [comment]
Can you point us to the `GRUB blsconfig patches`? 

What we have tried so far
In https://github.com/dbnicholson/deb-ostree-builder/blob/master/create-deployment (which is being used to generate our debian based deployment) we have removed the grub.cfg file creation part. After that the ostree deploy command  in the script seems to finish.

But we still need to generate a grub config. Even if we manually create grub.cfg for test purpose the UUID becomes and issue. Do you have any pointers on how to generate  the grub config for the ostree deploy that happens?

**Comment by ninja18** [comment]
Bit more context, we are trying to get a debian based ostree image out.

**Comment by rfairley** [comment]
@ninja18, which version of OSTree are you using to create the deployment? The version may simply not have the patch in #1831 added, as the assertion in the log in the report is on line 366 but the assertion in [current master is on 364](https://github.com/ostreedev/ostree/blob/a128eb551a8ffbb9c079d5b628afb907e14fd081/src/libostree/ostree-bootloader-grub2.c#L364), as well as the different variable name. Updating to a newer version may fix things in the short term.

Agree overall that `bootloader=none` as Colin mentioned is the encouraged way to go now, to avoid the expensive scanning with `os-prober` when `grub2-mkconfig` is run.

**Comment by ninja18** [comment]
@cgwalters We tried static grub config but root uuid was an issue. We also tried instead of grub mkconfig, we used ostree-grub-generator and It failed.

@rfairley  We tried with ostree-2019.x and ostree-2020.x Below is the log from ostree-2020. 
```
 ostree admin -v --sysroot=/tmp/ostree-deploy.uyqcCkgc3h deploy --os=debian --karg=root=UUID=cd25b2a6-cfff-4844-a767-905cae31f378 --karg=rw --karg=splash --karg=plymouth.ignore-serial-consoles --karg=quiet debian:unstable/amd64
OT: Preparing transaction in repository 0x55f7021e8140
OT: Pushing lock non-blocking with timeout 30
OT: Creating repo lock table
OT: Opening repo lock file
OT: Push lock: state=unlocked, depth=0
OT: Locking repo shared
OT: Using new tmpdir staging-0323aafb-c4d6-4a8b-98a8-b7e44e16deea-Wq1Ssu
OT: Committing transaction in repository 0x55f7021e8140
OT: txn commit staging-0323aafb-c4d6-4a8b-98a8-b7e44e16deea-Wq1Ssu
OT: Popping lock non-blocking with timeout 30
OT: Pop lock: state=shared, depth=1
OT: Unlocking repo
Relabeling /var (no stamp file 'var/.ostree-selabeled' found)
OT: boot is ro: no
OT: Using bootloader configuration: auto
OT: Using bootloader: OstreeBootloaderGrub2
OT: Using grub2-mkconfig chroot: /tmp/ostree-deploy.uyqcCkgc3h/ostree/deploy/debian/deploy/0ac4d92b424c04b2f7d49f550cab787c2884196b87c16ff0e26f2e33a4e7eead.0

OT: Free lock: state=unlocked, depth=0
OT: Closing repo lock file
OT: Free lock table
error: Bootloader write config: /usr/sbin/grub-mkconfig: Child process exited with code 1
```
Is there a way to get the logs of child process more verbosely?

**Comment by ninja18** [comment]
we were able to get a bootable ostree, once we switched from initramfs-tools to dracut for initramfs generation. Thanks for the help!

**Comment by bearrito** [comment]
@ninja18 Do you have on hand the scripts/code you used to get this working. I've been working off and on a while trying to get this working and never have seen a full worked example that includeds image (qcow/raw) image generation.

**Comment by bearrito** [comment]
@ninja18 This is very helpful.
I was unfamiliar with freedom-maker thanks for introducing me to that.

Few quick questions

In the below line, I'm assuming this is a call to `subprocess.run`. I can see from looking at https://salsa.debian.org/freedombox-team/freedom-maker/-/blob/master/freedommaker/internal.py that state is a member variable of the builder function, so that makes sense  What is the `target`?  They vanilla deb-ostree-builder/create-deployment doesn't take an arg. Is target a filepath? 

```
    run(['/home/user/deb-ostree-builder/create-deployment', target,get_uuid_of_device(state['devices']['root'])], ignore_fail=True)
```
