### ISSUE TITLE
[Question] 'Failed to start User Manager for UID 1000' after deploying a new commit

### ISSUE THREAD

**Issue by junjiequ** [ostreedev/ostree#2140]
Hi there,

I have been puzzled by an issue for couple of days.  Here is the case:

I have an OSTree commit generated by the Fedora coreos-assembler : it's an archive mode repo containing a single commit and ref.
Along side this commit, the coreos bare machine image was used to install on the client machine.
The client machine works just fine with the proper ignition file input.

Now I would like to use that ostree repo to add some customization on top and make a new commit out of it (in the form of a separated repo tar file). 
The final goal was to deploy this new commit on the client machine with the os installed above. 

I was able to deploy this commit after pulling the commit from the 2nd repo. The deployment folder under `ostree/deploy/fedora-cores/deploy/[commit].d` looks "good" for me.

But when I rebooted into this deployment, I am stuck at the login prompt, even though I used the correct username/password , SSH doesn't work neither.

So I have to revert back to the previous deployment, where I could dig around the system journal to get some useful information.

Below is a snippet from `journalctl -b -1`

```diff
Jun 22 15:52:19 systemd[1]: Created slice User Slice of UID 1000.
Jun 22 15:52:19 systemd[1]: Starting User Runtime Directory /run/user/1000...
Jun 22 15:52:19 systemd-logind[753]: New session 3 of user core.
Jun 22 15:52:19 systemd[1]: Finished User Runtime Directory /run/user/1000.
Jun 22 15:52:19 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='unit=user-runtime-dir@1000 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 22 15:52:19 systemd[1]: Starting User Manager for UID 1000...
Jun 22 15:52:19 audit[860]: USER_ACCT pid=860 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='op=PAM:accounting grantors=pam_unix acct="core" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 22 15:52:19 audit[860]: CRED_ACQ pid=860 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='op=PAM:setcred grantors=? acct="core" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jun 22 15:52:19 audit[860]: USER_ROLE_CHANGE pid=860 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='pam: default-context=unconfined_u:unconfined_r:unconfined_t:s0 selected-context=unconfined_u:unconfined_r:unconfined_t:s0 exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 22 15:52:19 systemd[860]: pam_unix(systemd-user:session): session opened for user core by (uid=0)
Jun 22 15:52:19 audit[860]: USER_START pid=860 uid=0 auid=1000 ses=4 subj=system_u:system_r:kernel_t:s0 msg='op=PAM:session_open grantors=pam_selinux,pam_selinux,pam_loginuid,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="core" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 22 15:52:19 audit[860]: AVC avc:  denied  { transition } for  pid=860 comm="(systemd)" path="/usr/lib/systemd/systemd" dev="sda4" ino=98798134 scontext=system_u:system_r:kernel_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0 tclass=process permissive=0
Jun 22 15:52:19 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='unit=user@1000 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
- Jun 22 15:52:19 systemd[1]: user@1000.service: Main process exited, code=exited, status=203/EXEC
- Jun 22 15:52:19 systemd[1]: user@1000.service: Failed with result 'exit-code'.
- Jun 22 15:52:19 systemd[1]: Failed to start User Manager for UID 1000.
Jun 22 15:52:19 systemd[1]: Started Session 3 of user core.
Jun 22 15:52:19 systemd[1]: session-3.scope: Succeeded.
Jun 22 15:52:19 systemd-logind[753]: Session 3 logged out. Waiting for processes to exit.
Jun 22 15:52:19 systemd[1]: Stopping User Runtime Directory /run/user/1000...
Jun 22 15:52:19 systemd-logind[753]: Removed session 3.
Jun 22 15:52:19 systemd[1]: run-user-1000.mount: Succeeded.
Jun 22 15:52:19 systemd[1]: user-runtime-dir@1000.service: Succeeded.
Jun 22 15:52:19 systemd[1]: Stopped User Runtime Directory /run/user/1000.
Jun 22 15:52:19 systemd[1]: Removed slice User Slice of UID 1000.
```

I could only guess that it is a permission related issue - but I am totally out of idea how to track it down.

I do have customized service unit files added in the new commit. They are placed under the `/usr/lib/systed/system` directory. The ownership and permission from the deploy directory showed that they are `root:root` 644.

Any suggest/hint on where/what to look into to solve this error? 
Anything is welcome and appreciated. 

Thanks!

**Comment by jlebon** [comment]
How are you generating the new OSTree commit? There's an AVC denial which could point to mislabeled files. Are you sure the new files are properly labeled? If using `ostree commit`, check out `--selinux-policy-from-base` (https://github.com/ostreedev/ostree/pull/2041).

**Comment by junjiequ** [comment]
@jlebon Many thanks for hint - I did not check that - or I don't event know that it was selinux related. Thanks for the input, new knowledge learned ;-) 

Indeed I am using `ostree commit` to generate the commit, but without the --selinux-policy-from-base. 

I will give it a try and report back.

**Comment by junjiequ** [comment]
@jlebon, a stupid question from my side: this `--selinux-policy-from-base` hasn't been shipped in any release yet right?

**Comment by jlebon** [comment]
Ahh yeah, you're right. You could either build git master, or otherwise you can use `--selinux-policy` instead for now pointing at a checkout of the base commit.

**Comment by junjiequ** [comment]
> `--selinux-policy` instead for now pointing at a checkout of the base commit

Thanks for the great suggestion. It fixed the issue. 🍻👍

Closing it now.
