### ISSUE TITLE
Avoid need to download remote config when pulling

### ISSUE THREAD

**Issue by pwithnall** [ostreedev/ostree#2165]
The code around [lines 3748–3768 of `ostree-repo-pull.c`](https://github.com/ostreedev/ostree/blob/master/src/libostree/ostree-repo-pull.c#L3748-L3768) requires downloading the `config` file from a remote to check two options:
 - `core.mode`, which it just does to abort if the mode isn’t `OSTREE_REPO_MODE_ARCHIVE`
 - `core.tombstone-commits` (a boolean)

Checking these two options means that `config` gets pulled by every client on every pull they do. On high latency or lossy connections, this adds noticeable time to a pull. It all seems a bit unnecessary.

Would it be possible to copy those options into the `summary` file, so that they can be checked using the copy of that which the client has already downloaded (or loaded from a cache)? Or is there some design reason for downloading `config` which I’m missing?

**Comment by cgwalters** [comment]
Totally agree, this is just a legacy thing we should get rid of indeed.

**Comment by pwithnall** [comment]
Fix available in #2167
