### ISSUE TITLE
libostree configure failed due to configure: error: Need GPGME_PTHREAD version 1.1.8 or later

### ISSUE THREAD

**Issue by adlingepa** [ostreedev/ostree#2201]
$ ./configure --prefix=${PWD}/buildostree
./configure: line 1030: STAGING_DIR: command not found
./configure: line 1030: LIBOSTREE_CONF_OPTS: command not found
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for bison... bison -y
checking if gcc supports flag -pipe in envvar CFLAGS... yes
checking if gcc supports flag -Wall in envvar CFLAGS... yes
checking if gcc supports flag -Werror=empty-body in envvar CFLAGS... yes
checking if gcc supports flag -Werror=strict-prototypes in envvar CFLAGS... yes
checking if gcc supports flag -Werror=missing-prototypes in envvar CFLAGS... yes
checking if gcc supports flag -Werror=implicit-function-declaration in envvar CFLAGS... yes
checking if gcc supports flag -Werror=format=2 -Werror=format-security -Werror=format-nonliteral in envvar CFLAGS... yes
checking if gcc supports flag -Werror=pointer-arith in envvar CFLAGS... yes
checking if gcc supports flag -Werror=init-self in envvar CFLAGS... yes
checking if gcc supports flag -Werror=missing-declarations in envvar CFLAGS... yes
checking if gcc supports flag -Werror=return-type in envvar CFLAGS... yes
checking if gcc supports flag -Werror=switch in envvar CFLAGS... yes
checking if gcc supports flag -Werror=overflow in envvar CFLAGS... yes
checking if gcc supports flag -Werror=int-conversion in envvar CFLAGS... yes
checking if gcc supports flag -Werror=parentheses in envvar CFLAGS... yes
checking if gcc supports flag -Werror=undef in envvar CFLAGS... yes
checking if gcc supports flag -Werror=incompatible-pointer-types in envvar CFLAGS... yes
checking if gcc supports flag -Werror=misleading-indentation in envvar CFLAGS... yes
checking if gcc supports flag -Werror=missing-include-dirs in envvar CFLAGS... yes
checking if gcc supports flag -Werror=aggregate-return in envvar CFLAGS... yes
checking if gcc supports flag -Wstrict-aliasing=2 in envvar CFLAGS... yes
checking if gcc supports flag -Werror=unused-result in envvar CFLAGS... yes
checking for -fsanitize=address in CFLAGS... no
checking for -fsanitize=thread in CFLAGS... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether renameat2 is declared... no
checking whether memfd_create is declared... yes
checking whether copy_file_range is declared... yes
checking for nanotime... no
checking for clock_gettime... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.0.0... yes (version 2.56.4)
checking for OT_DEP_GIO_UNIX... yes
checking for OT_DEP_LZMA... yes
checking for OT_DEP_ZLIB... yes
checking for OT_DEP_E2P... yes
checking for libsoup-2.4 >= 2.39.1... no
checking for OT_DEP_GPGME... no
configure: error: Need GPGME_PTHREAD version 1.1.8 or later

**Comment by lucab** [comment]
Thanks for the report. It looks like your build environment may be missing the development bits for the GPGME library. Depending on which distribution you are on, the package to install may be called like `gpgme-devel` or `libgpgme-dev` or something similar.

**Comment by lucab** [comment]
No further feedback in a couple of months, I'm tentatively closing this.
