### ISSUE TITLE
docs: Readthedocs documentation is very outdated

### ISSUE THREAD

**Issue by pheki** [ostreedev/ostree#2206]
The ReadTheDocs page is still pointing to `rust-libostree` instead of `ostree-rs`, which was fixed more than a year ago ([PR](https://github.com/ostreedev/ostree/pull/1860), [commit](https://github.com/ostreedev/ostree/commit/01c471a6f333a0ef032fa85c30fe0f6a990ed9af)).

It looks like the docs were last built [1y9m ago](https://readthedocs.org/projects/ostree/) , maybe a [webhook](https://docs.readthedocs.io/en/stable/webhooks.html) could be created?

Thanks for this project :)

**Comment by travier** [comment]
I'm currently working on converting the docs to GitHub Pages and will open a PR really soon. They will be auto-published on every commit on master so they will never go stale anymore.

**Comment by pheki** [comment]
That's great! Thanks a lot for quick response 😄

**Comment by pheki** [comment]
Please note that [readthedocs](https://ostree.readthedocs.io/en/latest/manual/introduction/) [pages](https://ostree.readthedocs.io/en/latest/) are still first on search engines (at least DDG and google) and probably at many bookmarks, and they're still outdated / not pointing to the updated docs.

I saw @cgwalters and @travier discussing this in #2207. Shouldn't this be reopened?

**Comment by travier** [comment]
Made https://github.com/travier/ostree/tree/for-readthedocs from https://stackoverflow.com/questions/40501719/how-to-redirect-readthedocs-web-pages-to-other-website but it is untested.

**Comment by cgwalters** [comment]
OK I am out today but remind me Monday, let's get that pushed as a branch in the main git repo and I'll try to figure out how to do this with the readthedocs UI.

**Comment by cgwalters** [comment]
Actually done now, pushed that branch to the main repo and finally found the very obscure knob in the readthedocs UI to make a different branch the default...let's see.

**Comment by travier** [comment]
Maybe with a `docs` sub folder? I have updated my branch

**Comment by cgwalters** [comment]
Looks like that worked!  I had to force-refresh in my browser to bypass caching.

Thanks a lot!!
