### ISSUE TITLE
Flatpak wants a new OSTree release

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#2238]
Flatpak master depends on ostree master, and I would like to do a flatpak 1.9.1 release so the new repo scalability work is easier to test. 

But I don't want to rely on an unreleased OSTree version, so it would be nice if we can have a 2020.8 release soon.

**Comment by lucab** [comment]
I'll take care of it this week, I've started with some CI refreshes at https://github.com/ostreedev/ostree/pull/2239.

**Comment by alexlarsson** [comment]
@lucab Thanks!
