### ISSUE TITLE
Consider combining summary.idx with summary.idx.sig

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#2250]
Originally <https://github.com/flatpak/flatpak/issues/3983> - at the time I opened that issue, I hadn't realised this was a piece of libostree-level design.

The new summary design has a top-level metadata file, `summary.idx`, and a detached signature, `summary.idx.sig`. This means libostree needs code (and test coverage) to cope with mirrors/proxies/CDNs briefly serving the old summary and the new signature, or vice versa.

The apt package manager used to have a similar design for the top-level index of a repository: in our case the filenames are `Release`, analogous to `summary.idx`, and `Release.gpg`, analogous to `summary.idx.sig`. Debian/Ubuntu have had trouble in the past with the cache lifetime of the `Release` file and the cache lifetime of the signature getting out of sync, leading to failed signature verification. As a result, recent apt tooling combines them into the same file, `InRelease`. In apt it's a "clearsigned" GPG message as produced by `gpg --clearsign -a`, similar to traditional non-MIME email signing, which means non-GPG-capable tools can still strip the GPG headers and read the actual content, but a binary GPG message as produced by `gpg -s` would be a reasonable alternative.

Perhaps libostree should do similarly? This would mean that when the summary index is updated, CDNs and web proxies that might have been caching it would atomically switch from the old index to the new index, with no period in which it might be serving the old index with the new signature or vice versa. Depending on CDN/proxy cache lifetime, the old index might hang around for a short time after it should have expired, but when it *does* switch, the switch will be atomic.

If this change happens, it should probably happen soon, so that repository providers don't have to keep serving `summary.idx.sig` forever.

For example, for Debian unstable, the apt repository contains:

* top-level index, analogous to `summary.idx`, used by old clients: https://deb.debian.org/debian/dists/unstable/Release
* detached signature, analogous to `summary.idx.sig`, used by old clients: https://deb.debian.org/debian/dists/unstable/Release.gpg
* combined file with both, analogous to what I'm suggesting here, used instead by new clients: https://deb.debian.org/debian/dists/unstable/InRelease

These are the only files in a modern apt archive for which the path needs to be hard-coded: they have `Acquire-By-Hash: yes`, to opt in to making apt use content-addressed storage to download the various `Packages` and `Sources` files by their hash, allowing smooth CDN/mirror updates in which we upload the new content, change the `Release` file atomically, wait for a while, and only delete the expired files referenced by the old `Release` file after some time has passed. I believe this is another way in which they are analogous to libostree's `summary.idx` and `summary.idx.sig`.

**Comment by smcv** [comment]
I suppose an alternative way to get a similar benefit would be to move or copy `summary.idx.sig` to a filename that is based on a hash of `summary.idx`, so that clients would do this:

* download `summary.idx` (untrusted)
* hash the untrusted contents of `summary.idx` (it doesn't even have to be a particularly strong hash): let's say we get hash `1234567890abcdef`
* download `summary-1234567890abcdef.idx.sig` (untrusted)
* validate `summary.idx` against that signature
* if the signature is considered valid, we can now trust `summary.idx`

and repo providers would do this:

* upload all new objects
* hash trusted contents of new `summary.idx`, let's say the result is `1234567890abcdef`
* upload `summary-1234567890abcdef.idx.sig`
* upload `summary.idx`, atomically replacing old summary
* wait a while
* remove all signatures older than some threshold time
* remove unreferenced objects

In that scheme, an attacker who can interfere with network traffic or the repo can do a downgrade attack in which they downgrade `summary.idx` to any version whose signature would still be considered valid, by remembering the signature that was served along with that version - but I think they could do that already, so there is no new attack here?

**Comment by alexlarsson** [comment]
@smcv The summary index is flatpak only actually.
