### ISSUE TITLE
Better support for shipping ostree-as-container

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#2251]
Basically: let's make it easy to ship and manage ostree commits via container images.

This is not at all a new issue; Alex did some prototype work on this originally proposed for ostree, and that code ended up in flatpak.  One way to look at this is to generalize the flatpak code to also handle the "ostree-for-OS" case, and also to support running them as a webserver.

More background: https://github.com/openshift/os/issues/382

# Proposal: ostree-releng oscontainer --repo=repo --ref=exampleos/x86_64/bar --output localhost/exampleos:bar`

## ostree-releng

This would be a successor to https://github.com/ostreedev/ostree-releng-scripts written in Rust, using the https://crates.io/crates/ostree bindings.  It could be consumed via CLI via tooling such as osbuild and coreos-assembler.

We would keep the ostreedev/ostree git repo as closer to a shared library with basic tools.

## ostcontainer command

`ostree-releng oscontainer --repo=repo --ref=exampleos/x86_64/bar --output localhost/exampleos:bar`

This would generate a build in a containers/image compatible way that contained the ostree commit.
However, it would be able to run in two ways:

 - If no command is provided, it would default to `bash` and the filesystem would look ostree-like (e.g. `/home` -> `/var/home`) but otherwise be a mostly stock container
 - If `/usr/local/bin/serve-http` is the `CMD`, it would expose a webserver that would speak plain OSTree repository protocol.  For example

## Webserver API

`/repo` would be the raw OSTree repo, that could e.g. contain GPG signatures and static deltas too
`/meta.json` would be a "cloud native" friendly JSON format that looks much like the coreos-assembler `composemeta.json` today ([example](https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201104.3.0/x86_64/commitmeta.json)).

## Directly consuming the ostcontainer as an update source

This would involve using https://github.com/flatpak/flatpak/blob/master/common/flatpak-oci-registry.c
See https://github.com/flatpak/flatpak/pull/3606

We could lift and reuse that code as is, though it currently depends on libsoup (not the end of the world but we just dropped it from fwupd).

## Sharing code with flatpak

Would flatpak be open to including Rust code?

Maybe to start we just lift the existing flatpak code into a "git submodule"-able library like libglnx?

**Comment by cgwalters** [comment]
cc @alexlarsson

**Comment by alexlarsson** [comment]
I'm a huge fan of rust in general, but for flatpak I don't think its a good fit. Flatpak is naturally a point of injecting more modern things into a potentially old/limited host. So I try to minimize build dependencies for flatpak (i.e. build with old glib, no meson, etc).

Sharing the OCI code would be fine though. Its rather isolated, so doing so shouldn't be that hard.

**Comment by cgwalters** [comment]
Probably too we should normalize support for archive-ostree-repo-in-tarball because it's easy to understand; it's what coreos-assembler does today.

**Comment by cgwalters** [comment]
OK https://github.com/cgwalters/ostree-container now exists and works.

**Comment by dbnicholson** [comment]
This is very interesting. At Endless we wanted to have a container to use in toolbox but without specifying a different way to construct the contents from the actual OS. We have a builder that just takes a minimal ostree, does a checkout, preps `/etc` similar to a deployment, and then creates a tarball of it to import into docker or podman.

This sounds much more streamlined. Would this cover the `/etc` conversion part?

**Comment by cgwalters** [comment]
Yes, ostree-container moves `/usr/etc` to `/etc` today when creating the tarball.  (But all the pristine metadata is stored in the `/sysroot/ostree/repo` stream in the tarball, so when you extract the ostree commit it's still `/usr/etc`; the tarball data stream is really mostly just used to store file content)

**Comment by cgwalters** [comment]
OK, closing this as the code now lives in https://github.com/ostreedev/ostree-rs-ext
