### ISSUE TITLE
Make repo locking API public

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#2286]
Back in #1292 and temporarily in it's slimmer cousin #1555 the repo locking APIs were public. I think it would be useful to have the API public, particularly for cases when you're going to do repo maintenance and want to ensure no one else is modifying the repo. On our Endless ostree server I've wanted this many times for doing unusual operations on repos to the point that I basically copied the whole locking scheme into python and our tooling relies on that to work.

Now we have a use case similar to https://raw.githubusercontent.com/endlessm/eos-meta/master/eos-tech-support/eos-fix-ostree-repo where we want to make dangerous changes on client repos. In particular, we want to undo the dubious decision we made many years ago to have flatpak use `/ostree/repo` as its repo. In order to split these up reliably we really want to make sure none of our various ostree programs (gnome-software and eos-updater primarily) can alter the repo while the surgery is happening.

Anyways, I think the locking has proven to be robust, although I do share your concern about deadlocking when there are multiple threads in play. I don't know what to do about it besides tell apps to be careful with exclusive locks, though.

What do you think?

**Comment by cgwalters** [comment]
Yeah, I think exposing the APIs makes sense.
