### ISSUE TITLE
ostree.repo gpgkeypath does not support https

### ISSUE THREAD

**Issue by xuchunmei000** [ostreedev/ostree#2299]
does ostree.repo gpgkeypath support https like yum/dnf repo:

```
# cat /etc/yum.repos.d/docker-ce.repo
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/centos/8/x86_64/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg
```

**Comment by cgwalters** [comment]
No; IMO this is kind of an anti-pattern.  Some recent discussion on this at 
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/3CGIH5B66JIB32RF5DKUEMJFH7JNFW7R/
for example.

Why do you want this?

ostree supports importing a key at `ostree remote add` time.

**Comment by xuchunmei000** [comment]
> No; IMO this is kind of an anti-pattern. Some recent discussion on this at
> https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/3CGIH5B66JIB32RF5DKUEMJFH7JNFW7R/
> for example.
> 
> Why do you want this?
> 
> ostree supports importing a key at `ostree remote add` time.

ok, got it.
