### ISSUE TITLE
ostree-mkinitcpio.conf is missing in source tarball

### ISSUE THREAD

**Issue by dvzrv** [ostreedev/ostree#2312]
Hi! I package ostree for Arch Linux.
In the custom source tarball the `src/boot/mkinitcpio/ostree-mkinitcpio.conf` file is missing which makes the build fail:

```
make[2]: *** No rule to make target 'src/boot/mkinitcpio/ostree-mkinitcpio.conf', needed by 'all-am'.  Stop. 
```

Please include the file and craft another release! :)

**Comment by cgwalters** [comment]
Thanks for the report; PR in https://github.com/ostreedev/ostree/pull/2321
