### ISSUE TITLE
BUG: Upgrade to ostree 2021.1-1 breaks rootless docker

### ISSUE THREAD

**Issue by abcalphabet** [ostreedev/ostree#2322]
After upgrading to `ostree 2021.1-1` and trying to start a rootless-docker container with `vfs` as the `storage-system`, it fails with the following error message:

```
Cannot start service consul: OCI runtime create failed: 
container_linux.go:367: starting container process caused: 
process_linux.go:495: container init caused: 
rootfs_linux.go:60: mounting "cgroup" to rootfs at "/sys/fs/cgroup" caused: invalid argument: unknown
```
Once `ostree` is downgraded to `2020.8-1` this error disappears and everything works as normal.

OS: `Arch Linux x86_64`
Kernel: `5.11.11-arch1-1`
`docker`: `1:20.10.5-1`
`docker-rootless-extras-bin`: `20.10.3-1`

**Comment by lucab** [comment]
Thanks for the report. However the error message seems to point in the direction of something having changed in your distribution regarding cgroups mounting. This is unlikely to be dependant on the ostree upgrade (although it may be related to other shared dependencies being updated at the same time). I'd recommend to file a bug to your distribution to investigate what's going on.

**Comment by abcalphabet** [comment]
[Arch linux bug report ](https://bugs.archlinux.org/task/70316)

**Comment by abcalphabet** [comment]
Problem was caused by systemd introducing cgroups v2 along with ostree being updated simultaneously.
