### ISSUE TITLE
error: Cleaning deployments

### ISSUE THREAD

**Issue by vilmasvensson** [ostreedev/ostree#2328]
Hi,

After an unsuccessful rebase using `rpm-ostree` I have a faulty deployment which can't be removed by ostree.
Using `ostree admin cleanup` returns:

```sh
error: Cleaning deployments: Removing ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0: unlinkat(41_custom): File exists
```

After this error the entire system becomes read-only and running an ostree command again returns:

```sh
error: Remounting /sysroot read-write: Invalid argument
```

**Comment by travier** [comment]
From https://discussion.fedoraproject.org/t/remove-corrupt-deployment/28534

**Comment by lucab** [comment]
Thanks for the report, that's a very funky error. Can you maybe trace that down to a specific path? Something like `sudo find /ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0 -name 41_custom` may work.
If such an entry still exists, it would be helpful to know what `stat` / `ls` or similar say about it.

**Comment by dbnicholson** [comment]
Just a hunch, but that looks to me like the name of a grub config file like `/etc/grub.d/41_custom` (although maybe it's a different path on a fedora host). I still don't understand how `unlinkat()` can return `EEXIST`, though.

**Comment by vilmasvensson** [comment]
Indeed it is a grub file:

```
> sudo find /ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0 -name 41_custom 
[sudo] password for vilma: 
/ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0/usr/etc/grub.d/41_custom
/ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0/etc/grub.d/41_custom
```

```
sudo stat /ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0/etc/grub.d/41_custom
  File: /ostree/deploy/fedora/deploy/f8d150dca32af60fbbc0a4d6c3ed0022e76cfbd1ea050aede1966cf0d7854e9c.0/etc/grub.d/41_custom
  Size: 220       	Blocks: 8          IO Block: 4096   regular file
Device: 21h/33d	Inode: 9242743     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:etc_t:s0
Access: 2021-03-23 20:11:38.863743691 +0100
Modify: 2021-03-21 00:57:19.391373104 +0100
Change: 2021-03-21 00:57:19.391373104 +0100
 Birth: 2021-03-21 00:57:19.391373104 +0100
```

I came across [this](https://discussion.fedoraproject.org/t/repair-existing-ostree-or-completely-remove-and-start-again/960/7) while searching and thought it might be related.

**Comment by jlebon** [comment]
Can you try using `strace` to run `ostree admin cleanup`? Would be good to sanity-check that it's truly `unlinkat` which is failing with `EEXIST` and not just some weird error-handling going on in libglnx making it seem like it.

**Comment by vilmasvensson** [comment]
Sorry for the inactivity. I built `strace` from source as I can't overlay packages. Here's the [full output](https://pastebin.com/qRiETU4q) of `strace ostree admin cleanup`.

**Comment by vilmasvensson** [comment]
Here's the relevant part:

```sh
...
openat(13, "grub.d", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 14
fstat(14, {st_mode=S_IFDIR|0700, st_size=376, ...}) = 0
fcntl(14, F_GETFL)                      = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
fcntl(14, F_SETFD, FD_CLOEXEC)          = 0
getdents64(14, 0x55c251c3ced0 /* 17 entries */, 32768) = 584
unlinkat(14, "00_header", 0)            = 0
unlinkat(14, "01_users", 0)             = 0
unlinkat(14, "08_fallback_counting", 0) = 0
unlinkat(14, "10_linux", 0)             = 0
unlinkat(14, "10_reset_boot_success", 0) = 0
unlinkat(14, "12_menu_auto_hide", 0)    = 0
unlinkat(14, "14_menu_show_once", 0)    = 0
unlinkat(14, "15_ostree", 0)            = 0
unlinkat(14, "20_linux_xen", 0)         = 0
unlinkat(14, "20_ppc_terminfo", 0)      = 0
unlinkat(14, "30_os-prober", 0)         = 0
unlinkat(14, "30_uefi-firmware", 0)     = 0
unlinkat(14, "40_custom", 0)            = 0
unlinkat(14, "41_custom", 0)            = -1 EEXIST (File exists)
openat(AT_FDCWD, "/usr/lib64/charset.alias", O_RDONLY) = -1 ENOENT (No such file or directory)
close(14)
...
```

Only mention of `EEXIST` I can find is in `man "unlink(3p)"` which is the POSIX Programmer's Manual:

```man
EEXIST or ENOTEMPTY
              The flag parameter has the AT_REMOVEDIR bit set and the path ar‐
              gument names a directory that is  not  an  empty  directory,  or
              there are hard links to the directory other than dot or a single
              entry in dot-dot.
```

`unlinkat()` shouldn't be able to return this error. I'm starting to wonder if I should just reinstall, or can I remove the file manually?

**Comment by lucab** [comment]
@vilmasvensson for reference, can you maybe note down 1) kernel version 2) glibc version 3) ostree version 4) which kind of filesystem is this 4) whether there are any weird kernel messages showing up at the same time, please?

**Comment by cgwalters** [comment]
Right, I'd look at e.g. `dmesg` for messages from the filesystem about corruption.

**Comment by vilmasvensson** [comment]
1. linux: `5.11.8-200.fc33.x86_64`
2. glibc: `2.32`
3. libostree: `2020.8`
4. filesystem: `btrfs`

I should've checked this sooner but the problem is indeed filesystem corruption, here's the output from `brtfs check /dev/nvme0n1p3`:

```sh
Opening filesystem to check...
Checking filesystem on /dev/nvme0n1p3
UUID: 95e0f8f7-64da-4a38-af94-0b6ebaebe7a2
[1/7] checking root items
[2/7] checking extents
[3/7] checking free space cache
[4/7] checking fs roots
root 257 inode 536 errors 200, dir isize wrong
	unresolved ref dir 9220246 index 11 namelen 9 name 41_custom filetype 1 errors 2, no dir index
root 257 inode 313102 errors 2000, link count wrong
	unresolved ref dir 536 index 0 namelen 67 name 5d24d078794c49929156288b701f7baaee20734e3cc6b4b1fe9d3e08018097.file filetype 1 errors 6, no dir index, no inode ref
	unresolved ref dir 10388658 index 8 namelen 6 name az.xml filetype 1 errors 0
root 257 inode 9220246 errors 200, dir isize wrong
ERROR: errors found in fs roots
found 141954486272 bytes used, error(s) found
total csum bytes: 134363460
total tree bytes: 1146093568
total fs tree bytes: 934445056
total extent tree bytes: 45891584
btree space waste bytes: 234897471
file data blocks allocated: 159106420736
 referenced 139727814656
```

**Comment by cgwalters** [comment]
OK, I hope you're able to recover your data!  It looks like there isn't an ostree bug here, so closing.  Feel free to reopen if you think otherwise.

**Comment by vilmasvensson** [comment]
Thank you! I hope so too.
