### ISSUE TITLE
Enhance OstreeKernelArgs API for easier idempotent append and delete operations

### ISSUE THREAD

**Issue by jlebon** [ostreedev/ostree#2329]
For doing https://github.com/coreos/rpm-ostree/issues/2709, it'd be nice if `OstreeKernelArgs` supported e.g. `ostree_kernel_args_append_if_missing` and `ostree_kernel_args_delete_if_present`.

Or... maybe we just want a `ostree_kernel_args_contains` for now which is more general and avoids having to expose the underlying data structures.

**Comment by Razaloc** [comment]
Can I start working on this ?

**Comment by jlebon** [comment]
Yes, go right ahead! :)

**Comment by Razaloc** [comment]
I hope that's fine if I give it another try.

**Comment by dbnicholson** [comment]
> I've seen `ostree_kernel_args_append_if_missing` already exist so I've followed it and the documentation to make `ostree_kernel_args_contains`. Do we also want a `ostree_kernel_args_delete_if_present` ?

To me it's not worth it since it's so simple to provide the logic yourself with `ostree_kernel_args_contains`. Might be nice as a convenience, though.

**Comment by dbnicholson** [comment]
> > I've seen `ostree_kernel_args_append_if_missing` already exist so I've followed it and the documentation to make `ostree_kernel_args_contains`. Do we also want a `ostree_kernel_args_delete_if_present` ?
> 
> To me it's not worth it since it's so simple to provide the logic yourself with `ostree_kernel_args_contains`. Might be nice as a convenience, though.

I came full circle on this. Since `ostree_kernel_args_append_if_missing` already exists, it would be unusual if `ostree_kernel_args_delete_if_present` didn't exist even if it's completely simple. If you're up for it, could you open a PR to add it?

**Comment by Razaloc** [comment]
Sure, I'm on it !
