### ISSUE TITLE
Wrong locking during more complex prunes

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#2337]
While doing some research into pruning I noticed that in ot-builtin-prune.c, if we take the more complex path that uses `ostree_repo_prune_from_reachable()` the exclusive repo lock is only held inside `ostree_repo_prune_from_reachable()`, so we compute the reachable set outside the lock. 

If this where to race with a commit operation that created a new commit which we didn't traverse then it would be pruned away.

**Comment by cgwalters** [comment]
Yeah, I think you're right.  We clearly need a test that tries to reproduce this race.  Also, fixing this would require fixing https://github.com/ostreedev/ostree/issues/2286

**Comment by jlebon** [comment]
Oh hey, this is fixed by https://github.com/ostreedev/ostree/pull/2808!
