### ISSUE TITLE
TLS support is not available (on NixOS)

### ISSUE THREAD

**Issue by Radvendii** [ostreedev/ostree#2347]
I can use flatpak fine, but when I try to manually download flatpak runtimes using ostree, I get "TLS support is not available" error;
```sh
$ mkdir foo
$ ostree --repo=foo init
$ ostree --repo=foo remote add flathub https://dl.flathub.org/repo/
$ ostree --repo=foo pull flathub org.freedesktop.Sdk/x86_64/20.08
error: TLS support is not available
```
I am opening this issue here as well as https://github.com/NixOS/nixpkgs/issues/119634 because I don't know if the problem is in NixOS or ostree. It's strange given that flatpak is able to do essentially the same operation using the same version of ostree.

**Comment by Radvendii** [comment]
It seems that this is a NixOS problem indeed. GIO_MODULE_DIR isn't being set properly.

**Comment by cgwalters** [comment]
Looks like this will be fixed by https://github.com/NixOS/nixpkgs/pull/119661 - closing here.
