### ISSUE TITLE
Regression in tests/test-gpg-signed-commit.sh with GnuPG 2.3

### ISSUE THREAD

**Issue by cbiedl** [ostreedev/ostree#2359]
Greetings,

rebuilding ostree using the recently released GnuPG 2.3 version caused failures in tests/test-gpg-signed-commit.sh:

    ERROR: tests/test-gpg-signed-commit.sh - too few tests run (expected 9, got 4)
    ERROR: tests/test-gpg-signed-commit.sh - exited with status 1

It seems - I might be wrong - GnuPG changed the output slightly, and ostree can not handle that. Could you please check?

This first showed up in the Debian autopkgtest of ostree (URL might not be stable): https://ci.debian.net/data/autopkgtest/unstable/i386/o/ostree/12266734/log.gz

Test was done using the versions in Debian unstable (2020.8-2) and experimental (2021.2-2), and according to git, no changes have been made to that test since then.

Failing test is tests/test-gpg-signed-commit.sh:240:

    assert_not_file_has_content test2-show 'Key expired'

The content of test2-show in my tests were

Using GnuPG 2.2.27 (pass):

    commit 8e0d719f8d3efb5e6e13cb02be7738a48730f8f27a9029dd9e7905f658467aef
    Parent:  a873c6d18c6e6d9da6bef54c5a93ccb62e14e6236a69ba5c37fed5146b784bf5
    ContentChecksum:  836bef3087db7055f34240586910fdb8c65d5d8b7f0587d6d2b9e83ba81933bd
    Date:  2021-05-12 11:27:29 +0000

        A GPG signed commit

        Signed commit body

    Found 2 signatures:

      Signature made Wed May 12 13:27:30 2021 using RSA key ID B3B25CA8394773D9
      Good signature from "Test Key 1 <>"

      Signature made Wed May 12 13:27:30 2021 using RSA key ID 276132F419CFFB80
      BAD signature from "Test Key 2 <>"
      Primary key ID BBC53D20DC671DE2
      Primary key expired Wed May 12 13:27:33 2021

Using GnuPG 2.3.1 (fail):

    commit b45b54b1a1a2ce0af29c53534c978b3ba617d99706c3e23bef42ddd31875a23e
    Parent:  0338445b23b4278306bad18f79c76d69964b58e0ddde84c650234298ddfc65b8
    ContentChecksum:  836bef3087db7055f34240586910fdb8c65d5d8b7f0587d6d2b9e83ba81933bd
    Date:  2021-05-12 11:16:39 +0000

        A GPG signed commit

        Signed commit body

    Found 2 signatures:

      Signature made Wed May 12 13:16:39 2021 using RSA key ID 261065D89A71DC82
      Good signature from "Test Key 1 <>"

      Signature made Wed May 12 13:16:39 2021 using RSA key ID 7659DCE5BD57EF22
      BAD signature from "Test Key 2 <>"
      Primary key ID E2DBCAA1E6D1F3E3
      Key expired Wed May 12 13:16:42 2021
      Primary key expired Wed May 12 13:16:42 2021

The last-but-one line triggers the failure.

Stating the (hopefully) obvious, the textual output format of GnuPG should not be considered stable. For machine-readable output, please consider using the --with-colons option of GnuPG.

In case you think this is actually a regression in GnuPG, please let me know, I'll be happy to forward that to upstream. Alternatively, feel free to create an issue at https://dev.gnupg.org/ on your own.

Kind regards,

Christoph (uploader of gnupg 2.3.1 in Debian)

**Comment by dbnicholson** [comment]
Thanks. This is just in the test suite, so I don't expect to try to parse the colons output. This is a regex, though, so I think it should be easy enough to make it accept both old and new output.

I need to look at this test and remember what it's expecting there.

**Comment by dbnicholson** [comment]
The strings actually come from ostree mapping gpgme signature and key attributes to error messages. Hmm, this actually suggests that something changed in gnupg or gpgme. In that test, there's a primary and subkey. The primary key has been expired while the subkey hasn't. With older gnupg, the primary key would be reported as expired but the subkey wouldn't. Now it's reporting both as expired.

I think that makes logical sense - if the primary key has expired then the subkey is also expired. What it actually does is set the primary key to expired by doing `gpg --quick-set-expire <primary fingerpring> seconds=1`. Does newer gnupg transmit this expiration down to the subkey? With gnupg 2.2.27, that doesn't seem to be the case:
```
$ gpg --homedir gnupg --batch --generate-key <<"EOF"
Key-Type: RSA
Key-Length: 2048
Key-Usage: sign
Subkey-Type: RSA
Subkey-Length: 2048
Subkey-Usage: sign
Name-Real: Test Key 2
Expire-Date: 0
%no-protection
%transient-key
%commit
EOF
$ gpg --homedir gnupg -K --with-colons
sec:u:2048:1:069312C2A4269262:1620839778:::u:::scSC:::+:::23::0:
fpr:::::::::6CBACDE1478C33E77678066E069312C2A4269262:
grp:::::::::005C6270DB30EEFE777C4262C44EAE1F54F2191A:
uid:u::::1620839778::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:u:2048:1:A4AF19362FE663B9:1620839778::::::s:::+:::23:
fpr:::::::::8CB20233A629483DD94C0914A4AF19362FE663B9:
grp:::::::::12837F7EDE65F457821A62045A121C1F0DC56052:
$ primary=6CBACDE1478C33E77678066E069312C2A4269262
$ subkey=8CB20233A629483DD94C0914A4AF19362FE663B9
$ gpg --homedir gnupg --quick-set-expire "$primary" seconds=1
$ gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec:e:2048:1:069312C2A4269262:1620839778:1620839916::u:::sc:::+:::23::0:
fpr:::::::::6CBACDE1478C33E77678066E069312C2A4269262:
grp:::::::::005C6270DB30EEFE777C4262C44EAE1F54F2191A:
uid:e::::1620839915::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:e:2048:1:A4AF19362FE663B9:1620839778::::::s:::+:::23:
fpr:::::::::8CB20233A629483DD94C0914A4AF19362FE663B9:
grp:::::::::12837F7EDE65F457821A62045A121C1F0DC56052:
```
The primary key has an expiration timestamp but not the subkey. So, either `--quick-set-expire` is now adding the expiration timestamp to the subkey or gpgme is setting `expires` on a [gpgme_subkey_t](https://www.gnupg.org/documentation/manuals/gpgme/Key-objects.html) when it has no expiration date but its primary key does.

Ultimately I don't think it really matters as the signature will not be considered valid if the primary key is expired, but it would be good to know what changed before adjusting the test suite (or ostree itself).

**Comment by cbiedl** [comment]
Thanks for your swift reaction, I've asked GnuPG upstream for clarification.

**Comment by dbnicholson** [comment]
Sure. Since you have the newer gpg, could you run the commands above and see if the subkey has an expiration timestamp?

**Comment by cbiedl** [comment]
Looks indeed like it.

Using GnuPG 2.2.27
```
gpg: key CDDFE6B8C475F563 marked as ultimately trusted
gpg: directory '/tmp/reprod/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/tmp/reprod/gnupg/openpgp-revocs.d/486C9676B04B95E3D32C3691CDDFE6B8C475F56
3.rev'

$ gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec:u:2048:1:CDDFE6B8C475F563:1621423688:::u:::scSC:::+:::23::0:
fpr:::::::::486C9676B04B95E3D32C3691CDDFE6B8C475F563:
grp:::::::::288B05468D6AE5DC6AC8C285FF4DD40C7C18BD2C:
uid:u::::1621423688::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:u:2048:1:6F80256E86B21ABC:1621423688::::::s:::+:::23:
fpr:::::::::3B02AA8F749DCFA7469B43936F80256E86B21ABC:
grp:::::::::0BF6D9F55DCDC606EFE2E5218BD32B9F0F81676C:
$ primary=486C9676B04B95E3D32C3691CDDFE6B8C475F563
$ subkey=3B02AA8F749DCFA7469B43936F80256E86B21ABC
$ gpg --homedir gnupg --quick-set-expire "$primary" seconds=1
$ gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec:e:2048:1:CDDFE6B8C475F563:1621423688:1621424054::u:::sc:::+:::23::0:
fpr:::::::::486C9676B04B95E3D32C3691CDDFE6B8C475F563:
grp:::::::::288B05468D6AE5DC6AC8C285FF4DD40C7C18BD2C:
uid:e::::1621424053::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:e:2048:1:6F80256E86B21ABC:1621423688::::::s:::+:::23:
fpr:::::::::3B02AA8F749DCFA7469B43936F80256E86B21ABC:
grp:::::::::0BF6D9F55DCDC606EFE2E5218BD32B9F0F81676C:
```

Using GnuPG 2.3.1
```
gpg: key D1921AA60AFD3363 marked as ultimately trusted
gpg: directory '/tmp/reprod/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/tmp/reprod/gnupg/openpgp-revocs.d/37FB6998FA7976B3E4E33771D1921AA60AFD3363.rev'

$ gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec:u:2048:1:D1921AA60AFD3363:1621423857:::u:::scSC:::+:::23::0:
fpr:::::::::37FB6998FA7976B3E4E33771D1921AA60AFD3363:
grp:::::::::F2409D963FD426EE362139851F037C9D55654F68:
uid:u::::1621423857::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:u:2048:1:EBD6E7DEDADFD759:1621423857::::::s:::+:::23:
fpr:::::::::B5E184CB0A6BBF4395C3B13DEBD6E7DEDADFD759:
grp:::::::::CCBAA6F03DE7C173D769DEDBE14485BFE5D31DE6:
$ primary=37FB6998FA7976B3E4E33771D1921AA60AFD3363
$ subkey=B5E184CB0A6BBF4395C3B13DEBD6E7DEDADFD759
$ gpg --homedir gnupg --quick-set-expire "$primary" seconds=1
$ gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec:e:2048:1:D1921AA60AFD3363:1621423857:1621424048::u:::sc:::+:::23::0:
fpr:::::::::37FB6998FA7976B3E4E33771D1921AA60AFD3363:
grp:::::::::F2409D963FD426EE362139851F037C9D55654F68:
uid:e::::1621424047::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:e:2048:1:EBD6E7DEDADFD759:1621423857:1621424048:::::s:::+:::23:
fpr:::::::::B5E184CB0A6BBF4395C3B13DEBD6E7DEDADFD759:
grp:::::::::CCBAA6F03DE7C173D769DEDBE14485BFE5D31DE6:
```

**Comment by dbnicholson** [comment]
Thanks for confirming. I found the commit and bug where this changed:

https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commitdiff;h=265e6d670682e661cec89657c3330b0b388ca0a7
https://dev.gnupg.org/T3343

I also confirmed that if the subkey already has an expiration date, then the new primary expiration date is not applied to the subkey:

```
root@5f27786e543b:/# gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec:u:2048:1:F178A4D919604FA4:1622235820:::u:::scSC:::+:::23::0:
fpr:::::::::359BFE68B4E082A35153D313F178A4D919604FA4:
grp:::::::::BB62571F79B53265B5D78C3335B288764DD6F752:
uid:u::::1622236277::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:u:2048:1:0E8935C0516F1B8F:1622235820::::::s:::+:::23:
fpr:::::::::84BC3C70ACB9D3C84812099D0E8935C0516F1B8F:
grp:::::::::CF460FC700CC0B34BC6154EA498497054839A2EC:
root@5f27786e543b:/# gpg --homedir gnupg --quick-set-expire $primary seconds=1 $subkey && sleep 1 && gpg --homedir gnupg --quick-set-expire $primary seconds=1
root@5f27786e543b:/# gpg --homedir gnupg -K --with-colons
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2021-05-28
sec:u:2048:1:F178A4D919604FA4:1622235820:1622236294::u:::scSC:::+:::23::0:
fpr:::::::::359BFE68B4E082A35153D313F178A4D919604FA4:
grp:::::::::BB62571F79B53265B5D78C3335B288764DD6F752:
uid:u::::1622236293::88A002D8DE3362C644091841F91A088A637827FE::Test Key 2::::::::::0:
ssb:e:2048:1:0E8935C0516F1B8F:1622235820:1622236292:::::s:::+:::23:
fpr:::::::::84BC3C70ACB9D3C84812099D0E8935C0516F1B8F:
grp:::::::::CF460FC700CC0B34BC6154EA498497054839A2EC:
```

Anyways, for ostree I don't think we care. If the primary key is expired than the signature will not be validated regardless of the expiration status of the subkey. We can just remove this line in the test since it's already confirming the things we care about.
