### ISSUE TITLE
Branch rename from master to main breaks every single Yocto build using OSTree

### ISSUE THREAD

**Issue by JanneKiiskila** [ostreedev/ostree#2360]
Your branch PR (https://github.com/ostreedev/ostree/pull/2358) rename from `master` to `main` breaks every single Yocto build in the whole wide world that uses `OStree` .

Reason being that most Yocto recipes specify the SRC_URI with a hash and then as there is no branch specifier it goes and does an additional check if the hash is on the branch it assumes.
- It then goes on assuming the default branch to be master.
- Which in this case has stopped to exist, as it was renamed.

This is causing massive issues to a lot of Yocto builds around the world and we would greatly appreciate, if you could create a branch called `master` back to it (and it should point to the same hash it used to point before the rename).
- It can be deprecated.
- You can do all your activities on `main` as you wish.
- It just needs to exist.

The updated recipes will be compliant with the main branch, but it will take time and we cannot easily fix existing releases that rely on this.

Please?

**Comment by cgwalters** [comment]
```
$ git push origin master
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for 'master' on GitHub by visiting:
remote:      https://github.com/ostreedev/ostree/pull/new/master
remote: 
remote: Heads up! The branch 'master' that you pushed to was renamed to 'main'.
remote: 
To ssh://github.com/ostreedev/ostree
 * [new branch]        master -> master
 * $
```

But, please tell me there is an inbound Yocto/bitbake fix for this?

**Comment by shr-project** [comment]
meta-oe/master https://lists.openembedded.org/g/openembedded-devel/message/91252
meta-oe/hardknott https://lists.openembedded.org/g/openembedded-devel/message/91253
meta-oe/gatesgarth https://lists.openembedded.org/g/openembedded-devel/message/91254
meta-oe/dunfell https://lists.openembedded.org/g/openembedded-devel/message/91255

It will be a while until it's merged in these still supported branches, for older branches it would be responsibility of the unlucky people using unsupported release to fix it on their own with .bbappend.

**Comment by cgwalters** [comment]
xref https://lists.openembedded.org/g/openembedded-core/topic/master_main_branch_renaming/82782995?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,82782995

**Comment by bgilbert** [comment]
https://github.com/ostreedev/ostree/pull/2361 makes the deprecation of the `master` branch more obvious.

**Comment by JanneKiiskila** [comment]
Similar discussion also in - https://github.com/coreos/go-systemd/issues/371.

Main points from there:
- You cannot remove the `master` branch ever. Please just leave it there.
- Upcoming new releases will be fixed.

**Comment by cgwalters** [comment]
> You cannot remove the master branch ever.

I'm not sure I agree with that as a fundamental premise.  Discussion on this is ongoing on the thread [linked above](https://github.com/ostreedev/ostree/issues/2360#issuecomment-840098178).

But for now, we will keep the `master` branch around; marking as resolved.

**Comment by bgilbert** [comment]
It turns out that BitBake allows users to override the [SRC_URI](https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#var-SRC_URI) for a BitBake recipe, for example via a [.bbappend file](https://www.yoctoproject.org/docs/1.6/dev-manual/dev-manual.html#using-bbappend-files).  The Yocto project architect has [advised us](https://lists.openembedded.org/g/openembedded-core/message/151725) that this is a routine procedure when an upstream renames a branch.

Since it appears that the removal of the `master` branch will not have unavoidable long-term consequences for downstream Yocto users, **we plan to remove the `master` branch again on June 15**.  If your builds are affected by this change, please update your recipes or local configs and help spread the word to others who might also be affected.

**Comment by bgilbert** [comment]
The `master` branch has now been removed again. Thanks for bringing this issue to our attention.

**Comment by Jimmitknopf** [comment]
I am facing a similar kind of issue.
It would be great to get some insight on how to resolve the issue.

I am using Yocto Gatesgarth. (Bitbake 1.48.0). While building I face a failure about fetching the ostree repo.
`ERROR: ostree-2020.7-r0 do_fetch: Fetcher failure for URL: 'gitsm://github.com/ostreedev/ostree;branch=main'. Unable to fetch URL from any source.`

As you can see, the URL is already updated to the branch "main" as stated in the discussion.
Hash value vor reference:  SRCREV = "32a3a1297312e566df3141c6c7e3b99709e474b1"

I am able to manually clone the repo (with the given URL) on to the build machine. So I assume, that this is not internet access related.

**Comment by JanneKiiskila** [comment]
Gatesgarth is very, very old. You should seriously consider upgrading (yes, I know it's not a small task).

However, you need to find out in which branch the hash is and add that toe SRC_URI line, i.e. `branch=main` (assuming it's on the `main` branch).
