### ISSUE TITLE
Publish API docs

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#2362]
Forgive me if they're already published or this has already been discussed, but it would be really nice if the API docs were published somewhere. The version at https://developer.gnome.org/ostree/stable/ is from 2014.4. Yikes.

It would appear that ostreedev.github.io/api would be usable alongside the regular ostree docs. I probably don't have the privileges to get this done, but I'd be happy to work on it.

**Comment by jlebon** [comment]
Agreed, that'd be great! Hmm, we could have a GitHub Action which builds the docs and pushes them to some git repo. It'd be pretty messy to push it to the main branch of this repo itself though, so it might have to be a different website from https://ostreedev.github.io/ostree/ ?

Maybe simplest to just have a separate `ostreedev/ostree-api-doc` repo with its own GitHub Pages which we link to from https://ostreedev.github.io/ostree/.

**Comment by dbnicholson** [comment]
How does the GitHub pages integration work right now? I haven't used it a ton, but at Endless I recall there was a separate gh-pages branch and our CI would build the docs and push them to that branch. I don't see any of that here and presumably jekyll builds the stuff in `docs` before it's published. Oh, I think I see from https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll that github pages automatically generates them.

In line with using a separate branch, another option (not sure how complex this would be) would be to have a simple top level index with links to the current docs and the API docs as separate endpoints like https://ostreedev.github.io/ostree/manual and https://ostreedev.github.io/ostree/reference. I don't quite know if `manual` is the best way to describe the existing docs. In that scheme an ambitious person could even generate the man pages and add them as a separate endpoint. The downside there is that I think you'd have to do the jekyll build in the CI instead of letting github pages do it automatically.

I think a separate repo would also work, but I'm guessing that would require a bit more effort to pass in a github token to allow pushing to a separate repository.

**Comment by dbnicholson** [comment]
#2363 does this but pushes to the `gh-pages` branch in this repo as seems to be the convention. It's not super pretty but it seems to work.

**Comment by dbnicholson** [comment]
Unfortunately, the [build](https://github.com/ostreedev/ostree/runs/2668612246) failed:

```
remote: Permission to ostreedev/ostree.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/ostreedev/ostree.git/': The requested URL returned error: 403
```

I was using the [automatically generated token](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) in my forked repo, but maybe this repo has them defined differently. Oh, it's because the github token is restricted. I was using the default permissive mode, but that run has:

```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
```

I think I need to add
```
permissions:
  contents: write
```
to that workflow.

**Comment by dbnicholson** [comment]
#2365 addresses that. I believe the repo settings likely still need to change to use `gh-pages` as the source instead of the automatically generated docs.

**Comment by dbnicholson** [comment]
https://ostreedev.github.io/ostree/reference/ is a 404, which tells me that the repo is still using the the GitHub automatically generated jekyll docs. https://github.com/ostreedev/ostree/tree/gh-pages/reference has the API docs. From #2363:

> In order to put this in place the ostree repo Pages settings would need to be changed to use `gh-pages` as the branch with the root directory.

@cgwalters or someone with repo admin powers - can you have a look at that?

**Comment by jlebon** [comment]
@dbnicholson Thanks, I updated the repo settings now to have GitHub render from the `gh-pages` branch and it looks like that did the trick! https://ostreedev.github.io/ostree/reference/ is now live.
