### ISSUE TITLE
Use GitHub Actions instead of Travis CI

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#2371]
Many of the PRs here fail because the travis builds get rate limited. I don't see this project moving from travis-ci.org to travis-ci.com, so we should get off of Travis CI. While there are likely other CI systems, I think GitHub Actions does everything we're currently doing on Travis (build ostree and run `make check`) and is free.

I started poking at this the other day but figured I better check that others are on board first. What do you think?

**Comment by wmanley** [comment]
FWIW I've moved some projects to github actions and have been really pleased with how fast builds happen.

**Comment by cgwalters** [comment]
Oh definitely.  I was trying this in https://github.com/ostreedev/ostree/pull/2305 but haven't gotten back to it yet.  If anyone plans to work on this please self-assign this issue, feel free to reuse that code or force push the PR.

**Comment by dbnicholson** [comment]
Ah, I knew I'd seen something you'd done fly by. That's a good start, but I think I'm going to try to use the docker setup so that we can get more coverage than just whatever Ubuntu VM GitHub supplies.

Anyone else can feel free to take over, but I will probably try to do it later this week.
