### ISSUE TITLE
Tests fail with SOURCE_DATE_EPOCH set

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#2405]
Debian builds official packages with [SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/) set to the date in the Debian changelog, to get a reproducible result from the same source code.

Unfortunately, since 2021.3 this seems to be making several build-time unit tests fail with this message:

```
downgraded without --allow-downgrade?
```

I think this is probably because the tests build more than one ostree commit, expecting the second one to have a strictly higher mtime, but the new `SOURCE_DATE_EPOCH` support gives them both the same mtime.

At the moment I'm working around this with `unset SOURCE_DATE_EPOCH` before running the tests in the packaging, but ideally the affected tests would unset this themselves.

**Comment by dbnicholson** [comment]
I agree with the workaround. Tests that want to check that behavior can set it explicitly. I think there's only one test that does handle it and it already does manage the variable. @lucab what do you think?

**Comment by lucab** [comment]
Yes, I'd agree it would be good to fix the tests upstream (i.e. here).
@smcv do you maybe have the logs from the failing test somewhere? I couldn't find the 2021.3 packages/runs on debian yet. Is the failure showing up through a plain `make check`, or is it going through some other path?

It would be good to see what is the situation across the whole testsuite. If it is only `upgrade with and without override-commit` having issues, we can surgically fix the epochs there. If it is more widespread, `libtest.sh` may carry the tweak. Or perhaps both.

**Comment by smcv** [comment]
> do you maybe have the logs from the failing test run somewhere?

From a previous attempt: [ostree_2021.3-1_amd64_20210725t181136.build.gz](https://github.com/ostreedev/ostree/files/6877501/ostree_2021.3-1_amd64_20210725t181136.build.gz)

> I couldn't find the 2021.3 packages/runs on debian infra yet

I didn't upload the version that was failing tests, because it was failing tests :-)

The finalized version of 2021.3-1 with the workaround is only in `experimental` so far, because Debian is in freeze for the Debian 11 release.

> Is the failure showing up through a plain `make check`, or is it going through some other path?

https://salsa.debian.org/debian/ostree/-/blob/debian/master/debian/test.sh wraps `make check`, and currently has the workaround.

> If it is more widespread

`tests/test-pull-bare.sh`, `tests/test-pull-bareuser.sh`, `tests/test-pull-bareuseronly.sh`, `tests/test-admin-deploy-syslinux.sh`, `tests/test-admin-deploy-uboot.sh`, `tests/test-admin-deploy-grub2.sh`, `tests/test-admin-deploy-none.sh` are all failing, so I think I'd be more comfortable with putting this in `libtest.sh`.
