### ISSUE TITLE
Is there a way to ostree commit a subpath?

### ISSUE THREAD

**Issue by jallwine** [ostreedev/ostree#2429]
Is there a way to do the opposite of `ostree checkout --subpath="PATH"`?

For example:

```
ostree checkout --subpath="path/to/a/directory" mycheckout
cd mycheckout
# make some changes
ostree commit --flags_to_check_in_changes_to_subpath other_arguments_to_check_in_changes_to_subpath
```

Is there some combination of flags and arguments that could achieve this or does a whole tree need to exist for a commit to happen?

**Comment by jlebon** [comment]
You can repeat the `--tree` arg multiple times. So e.g. `--tree=ref=myref --tree=dir=mycheckout` will overlay those sources in the same order as they are given. Though in this case, you probably want `--base myref` instead which is optimized for this.

Tentatively closing.

**Comment by jallwine** [comment]
Thanks @jlebon! I was able to get it to work with that info. The key being that the entire parent structure of the subpath needs to be recreated. So:

```
mkdir -p root/path/to/a/
ostree checkout --subpath="path/to/a/directory" root/path/to/a/directory
# make any changes to root/path/to/a/directory
ostree commit --base=currentRef --tree=dir=root --branch=mybranch
```
