### ISSUE TITLE
No ability to pull single file

### ISSUE THREAD

**Issue by gasinvein** [ostreedev/ostree#2443]
OSTree allows pulling subdirectories instead of whole ref contents, but this is not suitable for cases when only a single file with well-known path is needed.
Example use case: flatpak-builder stores canonicalized flatpak manifest as `manifest.json` in the root directory of the ref. This file could be useful for automatic analysis of the flatpak repository, e.g. to find improperly bundled modules. If OSTree allowed pulling a single file, retrieving `manifest.json`'s for every app in a flatpak repository could be done in a fast and clean way.

**Comment by dbnicholson** [comment]
It's undocumented, but I believe that if you specify a file for the directory, [it will fetch it](https://github.com/ostreedev/ostree/blob/main/src/libostree/ostree-repo-pull.c#L544). Can you try it out? Maybe this just needs some documentation.

**Comment by gasinvein** [comment]
Tried that, it fetches the whole ref if a file path is passed to `--subpath` (ostree 2021.4).

**Comment by dbnicholson** [comment]
Hmm, it worked for me. I made a commit with the following tree:
```
$ tree files
files
├── a
└── b
    └── c
```
When I pulled it from another repo with `--subpath /a`, it fetched the commit, the root dirtree and dirmeta, and the `/a` file. It did not fetch the `/b` dirtree or `/b/c` file.

**Comment by gasinvein** [comment]
Indeed it works. Static deltas were the issue, with `--disable-static-deltas` it pulls only one file indeed.

**Comment by dbnicholson** [comment]
That's interesting. Perhaps static deltas should be disabled if subdirs are specified in the pull options. There's a tradeoff there since it might be faster to just pull the entire tree in a delta, but I think that's a case where the user explicitly asked for something, so ostree should just do it.

**Comment by dbnicholson** [comment]
I opened a couple issues to tackle the bugs here, but I think this is working. Please reopen if you disagree.

**Comment by gasinvein** [comment]
No, that's fine. Thanks for helping me sort this out.

**Comment by gasinvein** [comment]
@dbnicholson Is there any way to disable static deltas for pull in GObject API? I expected a flag in `OSTree.RepoPullFlags`, but don't see anything relevant.

**Comment by dbnicholson** [comment]
Yeah, use `pull_with_options` and the `subdirs` option. I'd consider `pull_one_dir` deprecated as it's just a wrapper around `pull_with_options` but without providing the full interface.
