### ISSUE TITLE
Add `ostree prune --commit-only`

### ISSUE THREAD

**Issue by jlebon** [ostreedev/ostree#2482]
On large OSTree repos, it's expensive to compute reachability. If we want to prune things one bit at a time to be explicit by invoking `ostree prune` multiple times, this can quickly add up.

This is a proposal to add a `ostree prune --commit-only` option where it would only delete the selected commit objects and do nothing else. Then we could have multiple cheap `ostree prune --commit-only` calls and only a single expensive `ostree prune` invocation which calculates full reachability once to shake off all orphan objects.

See also: https://github.com/coreos/fedora-coreos-releng-automation/pull/79#discussion_r735774851

**Comment by lucab** [comment]
For clarity, how will this new flag relate to the existing `ostree prune --delete-commit <COMMIT>`?

**Comment by dustymabe** [comment]
I think `--delete-commit` is when you know what commit you want to delete. This RFE is requesting that when we run a prune that spans many commits (i.e. delete all commits in the history of `$ref` that are older than `X` days) that it just deletes the commit and leaves the content objects. Then a later prune operation can sweep the repo and delete all objects that aren't reachable.
