### ISSUE TITLE
/run/ostree-booted present in initramfs after ostree-prepare-root?

### ISSUE THREAD

**Issue by kjbracey-arm** [ostreedev/ostree#2485]
Some of my initramfs scripting that was previously working has stopped working, and I'm not totally sure where. But I'd like to understand the intent here.

We've included a full ostree installation in an initramfs to perform various integrity checks, and those run after the `ostree-prepare-root /rootfs`, but before moving the mounts. (So that they can locate the current deployment from `ostree admin`, but we don't want to inadvertently start using anything from the rootfs yet).

`ostree-prepare-root` is creating `/run/ostree-booted`.

This then means that following commands including `ostree fsck` and `ostree diff` fail, because they see that we're "ostree booted", try to mess with the non-existent `/sysroot`, and we get `error: Remounting /sysroot read-write: No such file or directory`.

`ostree admin --sysroot=/rootfs --print-current-dir` works, because the `--sysroot` option suppresses the "ostree booted" flag, but you can't do that for the non-admin commands.

Shouldn't `ostree-prepare-root` be creating `/rootfs/run/ostree-booted`, if anything? Surely we don't want that created in the current initramfs layout prior to remounting? If it is being set for a good reason, maybe `ostree` commands need to be more selective about when to remount `/sysroot`, or more tolerant of failure?

This scripting was working - I'm guessing an ostree update changed something in the way `/run/ostree-booted` was created. This is now at 2021.1, and I believe it was previously at 2020.7. Could maybe have been some other environment change.

Going to attempt to work around it by (temporarily?) `rm`ing `/run/ostree-booted` from the initramfs.

**Comment by jlebon** [comment]
Yeah, really we shouldn't be trying to remount any repo at all here. Fix in https://github.com/ostreedev/ostree/pull/2486. I've manually verified that this fixes running `ostree fsck` from the initramfs.

**Comment by kjbracey-arm** [comment]
Thanks! My `rm /run/ostree-booted` from the initramfs seems to be a functioning workaround for 2021.1 - nothing else seems to care about that prior to the remount.

Although maybe I should have been more careful - it seems that in my environment the initramfs `/run` **does** actually move to become the sysroot `/run`, but then there's also a separate thing in sysroot init scripts to recreate the `/run/ostree-booted` anyway, so my deletion doesn't seem to break anything...
