### ISSUE TITLE
"Failure when receiving data from from the peer" is not retried

### ISSUE THREAD

**Issue by champtar** [ostreedev/ostree#2570]
Doing kickstart install from an Alma 8.5 iso / Alma 8.5 based tree ( libostree/2021.3 |  libcurl/7.61.1),
pulling content using http2 I'm getting `Failure when receiving data from from the peer`.
Disabling http2 make the install succeed, so root cause is likely a curl bug, but we might want to consider retrying more errors in _ostree_fetcher_should_retry_request

**Comment by cgwalters** [comment]
OK right, this also got filed as https://issues.redhat.com/browse/RHELPLAN-146197

The relevant code here is in `_ostree_fetcher_should_retry_request`.

I think what we may be missing here is a mapping from libcurl errors to GError.

Today we do:

```
      else if (curlres != CURLE_OK)
        {
          if (is_file && curlres == CURLE_FILE_COULDNT_READ_FILE)
            {
              /* Handle file not found */
              g_task_return_new_error (task, G_IO_ERROR, G_IO_ERROR_NOT_FOUND,
                                       "%s", curl_easy_strerror (curlres));
            }
          else
            {
              g_task_return_new_error (task, G_IO_ERROR, G_IO_ERROR_FAILED,
```

But...arguably perhaps we should just map all libcurl errors here to `G_IO_ERROR_TIMED_OUT` - this would force a retry.
