### ISSUE TITLE
pull_with_options uses /var/tmp as tmp space, preventing pulling big files during kickstart installs

### ISSUE THREAD

**Issue by champtar** [ostreedev/ostree#2571]
Using libostree/2021.3 (Alma 8.5)
I'm trying to install a tree over https containing big files (~1.5G) using anaconda/kickstart
While anaconda is running `/var/tmp` only has 800 Mo free (`/dev/mapper/live-rw`), and once `pull_with_options` pulls a big file, running `df -h`, I can see / fill up until I get a `No space left on device`.
`lsof /var/tmp` shows a deleted file:
![image](https://user-images.githubusercontent.com/3536755/160044755-6760c98a-2a7c-48bc-a394-c711eb69eb87.png)

`file://` install are working but not `https://` (so either libcurl or the code around it need love)
If possible tmp space should be in the ostree repo dir by default IMO.

As a workaround we can just mount a tmpfs on top of `/var/tmp`:
```
%pre
mount -t tmpfs -o size=100% tmpfs /var/tmp/
%end
```

**Comment by cgwalters** [comment]
> If possible tmp space should be in the ostree repo dir by default IMO.

Yes; hmm, AFAICS this should be the case right now.  This needs a bit more debugging; there's various places where we pass the tempdir down, and it *should* point to the repository tmpdir i.e. `/ostree/repo/tmp`.

**Comment by champtar** [comment]
Do you know if it shipped with 8.7, IE should I try again ?

**Comment by NeilHanlon** [comment]
Heya - Just a note as I am experiencing this as well in the current 8.8 releases with the following ostree/rpm-ostree.

```
ostree-2022.2-6.el8
rpm-ostree-2022.10.115.g15eba7b1-2.el8_8
```

More than happy to try and debug this -- I was looking into the code which performs the download and found my way toward the libGObject interfaces for ostree and rpm-ostree, but would appreciate any pointers you have to where I can look further, @cgwalters.

FYI the versions above are from Rocky Linux 8.8, but I did confirm it occurs w/ RHEL versions, too.

**Comment by dbnicholson** [comment]
I'm pretty sure this is from the fetcher. Unless `OSTREE_FETCHER_REQUEST_LINKABLE` is set (which is not the common case AFAICT), `_ostree_fetcher_tmpf_from_flags` uses `glnx_open_anonymous_tmpfile`, which uses `TMPDIR` or `/var/tmp` as a fallback.

**Comment by cgwalters** [comment]
PR in https://github.com/ostreedev/ostree/pull/2875

**Comment by cgwalters** [comment]
xref https://github.com/ostreedev/ostree/issues/2900#issuecomment-1609117759 - when we aim to re-land this it'll need to be done in a way that avoids breaking flatpak (even if we find a flatpak fix, we should be conservative and still work with older versions).
