### ISSUE TITLE
Incorrect installation path for test fixture

### ISSUE THREAD

**Issue by jtojnar** [ostreedev/ostree#2574]
Running 2022.2 installed tests, the `libostree/test-basic-bare-split-xattrs.sh.test` fails:

```
machine # tar: /nix/store/6mqxm67gv8qjb74i9fbacaqpjsqaz3xx-ostree-2022.2-installedTests/libexec/installed-tests/libostree/tests/fixtures/bare-split-xattrs/basic.tar.xz: Cannot open: No such file or directory
machine # tar: Error is not recoverable: exiting now
```

Contrary to the test’s expectation, the archive is installed to `/nix/store/6mqxm67gv8qjb74i9fbacaqpjsqaz3xx-ostree-2022.2-installedTests/libexec/installed-tests/libostree/basic.tar.xz`.

**Comment by jtojnar** [comment]
The file is installed here:

https://github.com/ostreedev/ostree/blob/574d35bbdf0f3e62c94bcb396ea4f005afc0418d/Makefile-tests.am#L205

but it is expected in a subdirectory:

https://github.com/ostreedev/ostree/blob/574d35bbdf0f3e62c94bcb396ea4f005afc0418d/tests/test-basic-bare-split-xattrs.sh#L59

**Comment by lucab** [comment]
Thanks for the report. I'm sorry I didn't realize I broke the installed tests. Can you please do a quick sanity check on https://github.com/ostreedev/ostree/pull/2578 to confirm that it fixes them for NixOS?
