### ISSUE TITLE
man: ostree-admin-instutil manpage layout is broken / incomplete

### ISSUE THREAD

**Issue by travier** [ostreedev/ostree#2581]
See rendered version at https://www.mankier.com/1/ostree-admin-instutil.

Sub commands section does not effectively list the sub commands.

Sources: https://github.com/ostreedev/ostree/blob/main/man/ostree-admin-instutil.xml

**Comment by dbnicholson** [comment]
Hmm, looks correct at https://ostreedev.github.io/ostree/man/ostree-admin-instutil.html. I imagine this is a docbook or docbook xsl stylesheets issue.
