### ISSUE TITLE
`ostree admin instutil set-kargs` does not operate on booted deployment

### ISSUE THREAD

**Issue by HuijingHei** [ostreedev/ostree#2599]
```
[core@cosa-devsh ~]$ sudo ostree admin instutil set-kargs --append=test -vvv
OT: Deployment fe9fea433b1c77b1cac208e4c333d8eb262373d8e07d0dcc5c4d5a724e50515b.0 unlocked=0
error: Attempting to remove booted deployment

[core@cosa-devsh ~]$ ostree admin status
* fedora-coreos fe9fea433b1c77b1cac208e4c333d8eb262373d8e07d0dcc5c4d5a724e50515b.0
    Version: 36.20220430.1.0
    origin refspec: fedora:fedora/x86_64/coreos/next

[core@cosa-devsh ~]$ rpm -q ostree
ostree-2022.2-1.fc36.x86_64
```
Also test with latest build `ostree-2022.3-2.fc36.x86_64`, get the same error

**Comment by cgwalters** [comment]
Long term we need to move all the rpm-ostree kargs logic down into ostree.  This `admin instutil set-kargs` was a quick hack intended to aid Anaconda long ago - it was designed to operate *offline*.

I think we do want to have `ostree admin kargs` that is basically the same as `rpm-ostree kargs`.

Short term, we could probably fix this command to understand it's operating on the booted deployment and not try to remove it.

**Comment by HuijingHei** [comment]
Thanks @cgwalters for the reply!

Command `ostree admin deploy --karg-append=test` which creates a pending deployment with append karg, not sure `ostree admin instutil set-kargs` should have the same output? And what is the difference?
```
[core@cosa-devsh ~]$ sudo ostree admin deploy --karg-append=test fedora:fedora/x86_64/coreos/stable
Copying /etc changes: 7 modified, 0 removed, 31 added
Bootloader updated; bootconfig swap: yes; bootversion: boot.0.1, deployment count change: 1

[core@cosa-devsh ~]$ ostree admin status
  fedora-coreos 83cb95041c99fb812714d5c1544504d77dbb76b7798f0b6d59bf40356bd8d058.1 (pending)
    Version: 35.20220410.3.1
    origin refspec: fedora:fedora/x86_64/coreos/stable
* fedora-coreos 83cb95041c99fb812714d5c1544504d77dbb76b7798f0b6d59bf40356bd8d058.0
    Version: 35.20220410.3.1
    origin refspec: fedora:fedora/x86_64/coreos/stable
```

**Comment by cgwalters** [comment]
The ostree philosophy in general is to avoid mutating the booted system by default, and this includes kernel arguments.  This is why `ostree_sysroot_deployment_set_kargs()` fails here, because it's trying to remove the booted deployment.

(OTOH of course, we give you all of `/etc` as mutable state to break things in)

The code is really just not designed to modify the bootloader configuration in place today; it goes to quite a lot of effort *not* to do that but instead create a new configuration and transactionally swap to it.

Implementing this is obviously possible by using the low level `ostree_bootconfig_parser_parse()` and `ostree_bootconfig_parser_write_at()` though.

**Comment by cgwalters** [comment]
I think jlebon mentioned this but coreos-installer has code which *is* designed for this, see https://github.com/coreos/coreos-installer/blob/01a6596de16fb9c1bebd237ac2f2db6d9ab158e3/src/io/bls.rs

I guess one path is copy-pasting that code into here (or into ostree-rs-ext?).  Having it be in Rust from the start is definitely appealing.

**Comment by HuijingHei** [comment]
> I think jlebon mentioned this but coreos-installer has code which _is_ designed for this, see https://github.com/coreos/coreos-installer/blob/01a6596de16fb9c1bebd237ac2f2db6d9ab158e3/src/io/bls.rs
> 
> I guess one path is copy-pasting that code into here (or into ostree-rs-ext?). Having it be in Rust from the start is definitely appealing.

Thanks @cgwalters for the suggestion!
This is really a big challenge to me, as I have no much knowledge about rust, will learn it first and try to read the code

One silly question, does this mean we shall have `ostree admin kargs` to implement updating kernel arguments in-place instead of creating a new deployment like `ostree admin deploy`?

**Comment by travier** [comment]
The idea is to copy the code that changes the kargs in the bls configs (/boot/loader/entries) from coreos-installer into ostree-ext-rs and then expose that as an additional command line option in rpm-ostree.

This has the advantage that we would not be adding more C code to ostree and instead write Rust.

**Comment by cgwalters** [comment]
> One silly question, does this mean we shall have ostree admin kargs to implement updating kernel arguments in-place instead of making a new deployment like ostree admin deploy?

I'd reiterate that `rpm-ostree kargs` today also does create a new deployment.

I think this is more like a different mode, something like `ostree admin kargs --in-place` or so?

I guess I'd probably vote that to start we introduce `ostree admin kargs --in-place` to start, don't do any Rust stuff.  Then eventually we backfill and make `ostree admin kargs` behave *exactly* the same as `rpm-ostree kargs`, except we have a new `--in-place` mode.

The `--in-place` mode would be in C to start.

WDYT?

**Comment by HuijingHei** [comment]
@cgwalters I understand your meaning now.
To me both are OK, it would be better to discuss in the meeting and make an agreement

**Comment by HuijingHei** [comment]
Summary:
Add `$ ostree admin kargs edit-in-place --append-if-missing=rw`
(the MVP defaults to “all deployments”, it works in-place, remains hidden for now, it’s a normal C subcommand i.e. not Rust, it exits with success when all deployments have the kargs present)

Based on the discussion, will leave as it is now and move to https://github.com/ostreedev/ostree/issues/2617
