### ISSUE TITLE
ChromeOS-like Verified Boot?

### ISSUE THREAD

**Issue by gghhkm** [ostreedev/ostree#2607]
A br created because of the conversation [here.](https://twitter.com/flawedworlddev/status/1525098422503612417?t=7ittho6p8DbR2BKo89FjkQ&s=19) 
ChromeOS verified boot is described as
> A verified boot is a sort of self-check, performed each time your Chromebook starts up. When a Chromebook detects foul play, meaning the system has been tampered with or corrupted in any way, the Chromebook repairs itself by reverting to a previous operating system and be good as new.

Would it be possible to do this here?

**Comment by cgwalters** [comment]
There are a few threads on this, most recent/active is https://github.com/ostreedev/ostree-rs-ext/issues/288

**Comment by gghhkm** [comment]
> There are a few threads on this, most recent/active is [ostreedev/ostree-rs-ext#288](https://github.com/ostreedev/ostree-rs-ext/issues/288)

Thanks. 👍
