### ISSUE TITLE
RFE: Add a hidden option to `ostree admin kargs edit-in-place` to update all existing deployments in place

### ISSUE THREAD

**Issue by HuijingHei** [ostreedev/ostree#2617]
Describe the enhancement

Add a hidden option to `ostree admin kargs edit-in-place` to update all existing deployments in place.

Example:

$ sudo ostree admin kargs edit-in-place --append-if-missing=rw
This would be useful for: https://fedoraproject.org/wiki/Changes/Silverblue_Kinoite_readonly_sysroot

**Comment by lucab** [comment]
@cgwalters we'd like to scope this logic into an hidden subcommand, solving the immediate needs of Silverblue only. This task has two odd semantic requirements (in-place changes; tweaking all the deployments) which we'd like not to advertise too much.

For future public kargs verbs we'd like to stick to something similar to rpm-ostree behavior, which creates new deployments and does not touch inactive ones. In that regard, future non-hidden/documented subcommands may look like this:
```
$ sudo ostree admin kargs edit --append-if-missing=rw
## Creates new deployment, starts from the default active one, does not impact inactive ones

$ ostree admin kargs editor
## Like the one above, but interactive editing via $EDITOR
```

Flags like `--in-place` and `--all-deployments` will create odd mixes, which we'd like not to surface to users right now as we hope to keep future UX cleaner and closer to the existing rpm-ostree one.

**Comment by HuijingHei** [comment]
Both make sense, the flag version can better reuse the code, and subcommand version make the logic more specific.
I will try with subcommand version (like `sudo ostree admin kargs edit-in-place --append-if-missing=rw`), when review if found the other is better then can change

@travier @cgwalters @lucab @jlebon , WDYT?

**Comment by HuijingHei** [comment]
Close this refer to https://github.com/ostreedev/ostree/pull/2639
