### ISSUE TITLE
Consider setting mtime to 1 instead of 0 to workaround logic bugs in other apps?

### ISSUE THREAD

**Issue by srd424** [ostreedev/ostree#2662]
I've just been bitten by this bug in cron which causes it not to load any crontab entries if the mtime of `/etc/crontab` and `/var/spool/crontab` are both 0:

https://bugs.launchpad.net/ubuntu/+source/cron/+bug/1773229

It's the sort of logic bug which I can easily imagine existing in other software too - is it worth setting the mtime to 1 instead of 0, or is there a particular reason why 0 is important?

**Comment by srd424** [comment]
(For completeness, https://github.com/ostreedev/ostree/issues/1469 and links from there document the original decision to set all files to 0.)

**Comment by cgwalters** [comment]
> I've just been bitten by this bug in cron which causes it not to load any crontab entries if the mtime of /etc/crontab and /var/spool/crontab are both 0:

Ah, ouch.  You might consider using systemd timers instead FWIW.

> is it worth setting the mtime to 1 instead of 0, or is there a particular reason why 0 is important?

We had to pick a value.  I don't think we can really easily change it now.
