### ISSUE TITLE
execute make  error: src/libostree/ostree-repo.c:2594:40: error: 'struct _gpgme_user_id'

### ISSUE THREAD

**Issue by yingzi2025** [ostreedev/ostree#2674]
[root@iZuf6edef2k4kmsakaabv4Z ostree]# make
echo '#include "config.h"' > libglnx-config.h
  GEN      src/libostree/ostree-enumtypes.h
  GEN      src/libostree/ostree-enumtypes.c
git.mk: Generating .gitignore
make[1]: 进入目录“/home/admin/adc-ostree/ostree/apidoc”
git.mk: Generating .gitignore
make[1]: 离开目录“/home/admin/adc-ostree/ostree/apidoc”
make  all-recursive
make[1]: 进入目录“/home/admin/adc-ostree/ostree”
Making all in .
make[2]: 进入目录“/home/admin/adc-ostree/ostree”
  CC       src/libostree/libostree_1_la-ostree-async-progress.lo
  CC       src/libostree/libostree_1_la-ostree-cmdprivate.lo
  CC       src/libostree/libostree_1_la-ostree-core.lo
  CC       src/libostree/libostree_1_la-ostree-date-utils.lo
  CC       src/libostree/libostree_1_la-ostree-dummy-enumtypes.lo
  CC       src/libostree/libostree_1_la-ostree-checksum-input-stream.lo
  CC       src/libostree/libostree_1_la-ostree-chain-input-stream.lo
  CC       src/libostree/libostree_1_la-ostree-content-writer.lo
  CC       src/libostree/libostree_1_la-ostree-lzma-common.lo
  CC       src/libostree/libostree_1_la-ostree-lzma-compressor.lo
  CC       src/libostree/libostree_1_la-ostree-lzma-decompressor.lo
  CC       src/libostree/libostree_1_la-ostree-rollsum.lo
  CC       src/libostree/libostree_1_la-ostree-varint.lo
  CC       src/libostree/libostree_1_la-ostree-linuxfsutil.lo
  CC       src/libostree/libostree_1_la-ostree-diff.lo
  CC       src/libostree/libostree_1_la-ostree-mutable-tree.lo
  CC       src/libostree/libostree_1_la-ostree-ref.lo
  CC       src/libostree/libostree_1_la-ostree-remote.lo
  CC       src/libostree/libostree_1_la-ostree-repo-os.lo
  CC       src/libostree/libostree_1_la-ostree-repo.lo
src/libostree/ostree-repo.c: In function 'ostree_repo_remote_get_gpg_keys':
src/libostree/ostree-repo.c:2592:18: error: 'struct _gpgme_user_id' has no member named 'address'
           if (uid->address != NULL)
                  ^

linux system: Linux version 3.10.0-1127.19.1.el7.x86_64 ; CentOS Linux release 7.6.1810 (Core)
git clone --recurse-submodules https://github.com/ostreedev/ostree.git;  branch: Release 2022.2

**Comment by dbnicholson** [comment]
What version of gpgme do you have? I don't remember what the package is called on CentOS, but maybe we need to bump that to a higher version.

**Comment by cheng0214** [comment]
I have same problems.  
gpgme version is 1.6.0-1 
ii  libgpgme11:amd64               1.6.0-1                               amd64        GPGME - GnuPG Made Easy (library)
ii  libgpgme11-dev                 1.6.0-1                               amd64        GPGME - GnuPG Made Easy (development files)
linxu system:  16.04.7 LTS (Xenial Xerus)

**Comment by cgwalters** [comment]
Sorry, we no longer support such old operating systems (centos 7, ubuntu 16.04) with the main ostree branch.  Feel free to reopen if you still have problems with a newer OS!
