### ISSUE TITLE
Build failure with conflicting enum types with glibc >= 2.36

### ISSUE THREAD

**Issue by GeorgesStavracas** [ostreedev/ostree#2685]
Apparently glibc developers decided to define FSCONFIG_* enum constants, which have been defined historically by linux/fs.h. Because ostree happens to include both headers in some files, the build is now broken.

See also: https://lists.gnu.org/archive/html/qemu-devel/2022-08/msg00346.html

**Comment by GeorgesStavracas** [comment]
This can be worked around by the following changes:

 * `src/libostree/ostree-sysroot-deploy.c`: Remove the `<sys/mount.h>` include
 * `src/ostree/ot-main.c`: Remove the `<linux/fs.h>` include

Not ideal but at least gets me a working build again

**Comment by cgwalters** [comment]
Thanks for the report.  In this case, I think actually what we should focus on is `linux/fs.h` - usage of that should be pretty small and isolated.  In fact, we *already have* a `ostree-linuxfsutil.[hc]` wrapper.  So moving the only include of that header to that file (without including the glibc headers) should address this systematically.

Can you test out https://github.com/ostreedev/ostree/pull/2686 ?

**Comment by lucab** [comment]
I also started cross-checking this, but I'll stop because #2686 seems the best way to handle this.
At the same time, I'm surprised because that `<sys/mount.h>` include indeed seems spurious, perhaps there is some room for an cleanup pass.
