### ISSUE TITLE
Metadata size limit too low

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#2715]
The metadata size limit is currently [defined](https://github.com/ostreedev/ostree/blob/c6c3c5ae9fbeaaa2207149ed348109400b88314e/src/libostree/ostree-core.h#L38) as 10 MB and is documented as an arbitrary limit. Unfortunately, flathub has hit that limit for the summary file and has had to resort to filtering refs out of it. It's not totally dire since flatpak has moved to its own subsummary format broken up by architecture, but eventually they'll hit the limit on those, too.

The [commit](https://github.com/ostreedev/ostree/commit/47610b45c2ac91d7d9749bc0a1ea5b3150a09a70) points to this [old bug](https://bugzilla.gnome.org/show_bug.cgi?id=725921). As mentioned in the commit message, the 10 MB is arbitrary, so I think it could just be raised to something bigger. However, I also think it would be possible to skip the limit when the remote URL is https:// under the assumption that there's no reasonable way to MITM that connection and TLS authenticates the source.

Obviously, changing the limit will not immediately fix anything since that change would have to roll out to clients, but eventually that would happen.

CC @barthalion

**Comment by cgwalters** [comment]
Probably worth seeing whether any other ecosystems have similar limits (e.g. does OCI limit JSON sizes?).  But yes, I'm probably ok to dramatically raise the limit (1G?) or just remove it altogether.

**Comment by logankaser** [comment]
Is there no hope for old clients?
I have `Flatpak 1.6.5` on Ubuntu 20 and no easy way to upgrade.
I get `Unable to load summary from remote flathub: URI https://dl.flathub.org/repo/summary exceeded maximum size of 10485760 bytes`
Whenever trying to use flathub.

**Comment by dbnicholson** [comment]
> Is there no hope for old clients? I have `Flatpak 1.6.5` on Ubuntu 20

I don't think upstream can do much about old clients besides telling you to upgrade. Ask Ubuntu to backport https://github.com/ostreedev/ostree/pull/2865. It's just changing a constant, and 2 of the 3 commits are for updating tests. It could easily be squashed into one patch.
