### ISSUE TITLE
Exclude /nix from ostree changes and effects

### ISSUE THREAD

**Issue by orowith2os** [ostreedev/ostree#2739]
Nix, as a packaging format, requires that `/nix` exist, and be mutable.

However, ostree prevents `/nix` from being created, and even if it were, it would be immutable, preventing the use of Nix on ostree systems. 

I suggest taking the appropriate measures to ensure that Nix is usable on an ostree-based system. Some folks from the Nix community may be able to detail everything that would be required to support this, I am just making this issue, as it's one of my (few!) complaints about using an ostree-based system (Fedora Silverblue).

**Comment by cgwalters** [comment]
Hi, I think Nix has a ton of great ideas, and I definitely want ostree to play nicely with it.
This issue touches on https://github.com/ostreedev/ostree/pull/2681

Try this today:

```
mkdir /var/nix
chattr -i /
ln -sr /var/nix /nix
```

Does that work?  IOW can `/nix` be a symlink?  If so, then things get simpler.  If it can't be, can it be a mountpoint?  i.e. does 

```
chattr -i /
mkdir -p /nix /var/nix
mount --bind /var/nix /nix
```

work?

**Comment by lucab** [comment]
There is some related discussion in https://github.com/coreos/rpm-ostree/issues/337 as well.
Over there, it was mentioned that the symlink may have some negative side-effects on the artefacts purity, and that the mountpoint approach is recommended instead: https://nixos.org/manual/nix/stable/command-ref/env-common.html#env-NIX_IGNORE_SYMLINK_STORE.

So overall I think the deployment should carry an empty top-level `/nix` directory, to be bind-mounted to node-local storage.

**Comment by orowith2os** [comment]
What's the current status of this? I can see some work being done over in https://github.com/nix-community/nix-installers/pull/8 that installs to /var/nix, but some utilities might still use /nix if they're used to it.

**Comment by jcdickinson** [comment]
@orowith2os nix-installers installs to /var/nix and mounts that to /nix using systemd. No change are required for rpm-ostree.

**Comment by orowith2os** [comment]
Closing this issue, since the PR seems to handle everything needed.
