### ISSUE TITLE
aria2 integration for downstream flatpak 

### ISSUE THREAD

**Issue by jnorthrup** [ostreedev/ostree#2741]
I'm on 100MB link experiencing an ostree single-source bottleneck.

Installing 5/5… █████▍                27%  405.4 kB/s  42:56

this is actualy fantastically better than average flatpak downloads, in southeast Asia.  the issue tracking on flatpak with the same complaint from I think Venezuela has been ignored entirely for 2 years because, hey, it's ostree's fault, SEP! see [Flatpak fails to download updates and install even small packages on slow Internet connection. #3407](https://github.com/flatpak/flatpak/issues/3407)

I notice that ostree is to some degree leveraging http

there is a very mature and robust c++ codebase called aria2 which performs multi-home, multi-threaded, resuming transfers across not only http (and https of course) but torrents and other DHT's.

on my local system i run the following as a direct replacement for `wget -c`

`alias aget='aria2c -Z -c -{j,s,x}\ 15  --file-allocation=none '`

this command above uses up to 15 hosts, up to 15 connections, up to 15 per host.  adding -Z  --force-sequential[=true|false] Fetch URIs in the command-line sequentially and download each URI in a separate session, like the usual command-line download utilities.  preallocation is supported and volumes are verified on completion. 

what is possible with relatively low complexity is to exec call to aria2c executable to test if it returns zero, and also with parameters to perform a blocking call while the exec runs aria2c to perform a parameterized fetch of some http or torrent blob.  

not that ipfs wouldn't be cool, but I just brought up a low-complexity option that could give instant benefits with almost no engineering in the grand scheme of things.

cheers

**Comment by vrumjantsev** [comment]
any plan on implementing it? 
I'm traveling in Asia right now and now i get the pain you guys have :D 
even with 300 mbps internet flatpak updates are so slow. 
event simultaneous upgrade of multiple packages could make it better, but aria2 implementation should definitely be considered

**Comment by jnorthrup** [comment]
https://github.com/ostreedev/ostree/issues/3033 seems to indicate that the very reliable and performant docker delivery system and ostree are the same thing and so aria2 and http clients internally used by ostree are apples and oranges  concepts, because OSI.

**Comment by ericcurtin** [comment]
So just to be clear there's two supported delivery mechanisms that I am aware of, the http one you are likely currently using (I think it uses libcurl) and a new OCI based one that's only been around in the last year.

That comment was essentially a poke to try the new OCI-based transport mechanisms if you'd like, as it might alleviate your concerns without implementing aria2.

OCI has the advantage and that it's a consolidated approach for many related artefact pulling tools: containers (via podman), vms (via libkrun, checkout krunvm) and now ostree bootable images also (via bootc/rpm-ostree/ostree/etc.) and there may be more OCI based transport things coming.

**Comment by jnorthrup** [comment]
this is crucoa; info for like 99% of asia.  is there a faq or link ?
