### ISSUE TITLE
thread 'main' panicked at 'failed to unpin deployment: Error { domain: g-io-error-quark, code: 21, message: "Writing out origin file: open(O_TMPFILE): Read-only file system" }', src/main.rs:15:14

### ISSUE THREAD

**Issue by juhp** [ostreedev/ostree#2769]
This is probably something elementary, but after upgrading to Fedora 37 Silverblue my tiny [ostree-pin](https://github.com/juhp/ostree-pin/blob/main/src/main.rs) utility started to panic:

```shellsession
$ RUST_BACKTRACE=1 ~/.cargo/bin/ostree-pin 
thread 'main' panicked at 'failed to unpin deployment: Error { domain: g-io-error-quark, code: 21, message: "Writing out origin file: open(O_TMPFILE): Read-only file system" }', src/main.rs:15:14
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: ostree_pin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Any ideas what might be wrong?  Basically it is crashing in `deployment_set_pinned()`.
(I am currently running Silverblue 37.20221116.0.)

I believe the code was working in SB36 (when I upgraded a couple of weeks ago) - so maybe something has changed?
I tried rebuilding with newer ostree/glib bindings but that didn't help.

Running `sudo ostree admin pin ...` by hands works fine.  I had a look at its C implementation but couldn't really see anything obvious stand out for me yet. Hopefully it is just something trivial I am missing.

**Comment by cgwalters** [comment]
It's because https://fedoraproject.org/wiki/Changes/Silverblue_Kinoite_readonly_sysroot

So...we don't yet have an ergonomic way exposed in the Rust API to do the unshare bits.  Will work on it at some point.  Basically it should work if you do e.g.:

```
unshare -m /bin/sh -c 'mount -o remount,rw /sysroot && ~/.cargo/bin/ostree-pin`
```

**Comment by juhp** [comment]
Ah I see thank you!  (I had missed that Change:)

**Comment by juhp** [comment]
Thanks!

**Comment by juhp** [comment]
Thanks again: I finally tried to use `ostree_sysroot_initialize_with_mount_namespace` in ostree-pin and it works nicely :pray:
