### ISSUE TITLE
Potential risk of panic out of `catch_unwind()`

### ISSUE THREAD

**Issue by shinmao** [ostreedev/ostree#2775]
Hello guys, when I tried to review the implementation of `filter_trampoline_unwindsafe()`, I found that the function would call `print_panic` to print out the error message as following.
https://github.com/ostreedev/ostree/blob/0dbd87c01724e1c2291c693eec255b068b4856a8/rust-bindings/src/repo_checkout_at_options/repo_checkout_filter.rs#L101

`print_panic` would call `eprintln!` to print out error message. However, based on the documentation of `eprintln`(https://doc.rust-lang.org/std/macro.eprintln.html), it will trigger panic if writing to `io::stderr` fails. This would cause to another unwinding out of `catch_unwind()`, and become undefined behavior when unwinding reaches the "C" ABI boundary.

Do you think such potential risk exist? Thanks.

**Comment by cgwalters** [comment]
> Actually, I am trying to find some elegant use catch_unwind() on github. Your code comes to my sight because the repo is popular.

Ah, heh.  Well to be honest I didn't personally write that code; it dates to https://gitlab.com/fkrull/ostree-rs/-/commit/2cf6602f973a8af4b45cb9d04e31496a127ffc49

For idiomatic use of `catch_unwind`...I'm not sure it's the best; what's your goal?  To do the same thing and just print it to stderr?

Anyways, I did a PR in https://github.com/ostreedev/ostree/pull/2776

**Comment by shinmao** [comment]
Yes. I saw your PR.

It seems that `write_all` would still possibly return variant of `ErrorKind`. It would be swallowed by the assigned variable `_`. However, I think it is much better than unexpected `panic!`.

**Comment by lucab** [comment]
@shinmao yes there is still a chance of hitting error cases in that scenario, but I don't see a better way of handling them over discarding them behind `_`. We'll merge this code for now, but if any better idea comes up feel free to ping here.

**Comment by shinmao** [comment]
Hi, is it possible for you guys to help me report issue to RUSTSEC? I am a security researcher trying to build some tools, and I might need some results on CVE/RUSTSEC to evaluate my tools. Though the issue has been closed, could you help me to explain the importance of finding this issue?

In `filter_trampoline_unwindsafe()`, what would happen if panics escaped to C function? I know unwinding from Rust function to foreign function is still undefined behavior. In your application scenario, will crash or something more serious happen?
