### ISSUE TITLE
problem with cross compile on x86-64

### ISSUE THREAD

**Issue by bigbearishappy** [ostreedev/ostree#2826]
I am trying to cross compile the ostree on a x86-64 PC. The install files will be used on a arm64 device.
But I encountered with a compile error with gpg-error.h.
Error log is here:
```
  GEN      man/ostree.repo-config.5
  CC       src/ostree/ostree-main.o
  CC       src/ostree/ostree-ot-builtin-admin.o
  CC       src/ostree/ostree-ot-builtin-cat.o
  CC       src/ostree/ostree-ot-builtin-config.o
  CC       src/ostree/ostree-ot-builtin-checkout.o
In file included from ./src/libotutil/ot-gpg-utils.h:22,
                 from ./src/libotutil/otutil.h:101,
                 from src/ostree/ot-builtin-cat.c:27:
/usr/include/gpgme.h:30:10: fatal error: gpg-error.h: No such file or directory
   30 | #include <gpg-error.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:5743: src/ostree/ostree-ot-builtin-cat.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./src/libotutil/ot-gpg-utils.h:22,
                 from ./src/libotutil/otutil.h:101,
                 from src/ostree/ot-builtin-config.c:27:
/usr/include/gpgme.h:30:10: fatal error: gpg-error.h: No such file or directory
   30 | #include <gpg-error.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:5757: src/ostree/ostree-ot-builtin-config.o] Error 1
In file included from ./src/libotutil/ot-gpg-utils.h:22,
                 from ./src/libotutil/otutil.h:101,
                 from src/ostree/ot-builtin-checkout.c:30:
/usr/include/gpgme.h:30:10: fatal error: gpg-error.h: No such file or directory
   30 | #include <gpg-error.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:5771: src/ostree/ostree-ot-builtin-checkout.o] Error 1
make[2]: Leaving directory '/home/seeed/test/ostree'
make[1]: *** [Makefile:7843: all-recursive] Error 1
make[1]: Leaving directory '/home/seeed/test/ostree'
make: *** [Makefile:3184: all] Error 2
```

Steps I did before compile:
1 install the cross compile tools
`apt install crossbuild-essential-arm64`
2 config the Makefile
```
env NOCONFIGURE=1 ./autogen.sh
./configure --host aarch64-linux-gnu --with-dracut --prefix=/usr LDFLAGS=
```
3 cross compile
```
make -j`nproc`
```

What I did to fix this problem?
1 I tried to compile it with out cross compile. And it works fine.
2 I find the gpg-error.h is in /usr/include/x86_64-linux-gnu/. It seems the cross compiler don't find it. So I tried to copy it to /usr/include,the compile can continue. But some other error happened. Then I tried to configure the Makefile with --includedir=/usr/include/x86_64-linux-gnu/.But it can not work too.

I attach the config.log after I configure the Makefile.
[config.log](https://github.com/ostreedev/ostree/files/10907229/config.log)

I am wondering if I missed some software package or some steps?
Looking forward to your reply~

**Comment by cgwalters** [comment]
There are multiple cross-compilation friendly build systems out there, such as Buildroot and Yocto for example.  There's also ostree recipies for the latter at least.  I'd recommend looking into one of those instead of hand-rolling one.

I'm not personally very familiar with the Debian cross-compliation setup.  I think you'd have to ask for advice there, not here sorry.
