### ISSUE TITLE
Want an option for transient /etc

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#2868]
For the automotive usecase, and for the general extension of the composefs work (https://github.com/ostreedev/ostree/issues/2867) it would be nice to have a mode where /etc is mounted as an overlayfs on top of /usr/etc from the commit and a tmpfs directory (say in /run). This way you can have a system that is validated by composefs, where you cannot persist system changes between boots.

In theory this should not be very complex, but my initial experiments ran into some issues with selinux contexts which need to be resolved. 

In addition, there are some files that we really want to per persist in /etc that are host machine specific. In particular, the `machine-id` file.  This would have to be solved by copying in it from some persistent location during early boot.

Additionally, and vaguely related:  

In the automotive project we are interested in being able to extend the system dynamically, but in a controlled fashion. In particular, we want to install container images and add systemd service files, but only for a trusted set of apps. Such service files would have to be persisted in /etc/systemd/system, but allowing files to be added there is very risky. The plan we have for this is to have a systemd generator that copies these files from a persisted location, after having verified that they are all signed (for example, using fs-verity signatures) against a trusted key. 

For full chain of trust, this also needs a container image backend using composefs, which is also in the works.

**Comment by cgwalters** [comment]
Some WIP for this in https://github.com/ostreedev/ostree/pull/2970

**Comment by cgwalters** [comment]
This was fixed by https://github.com/ostreedev/ostree/pull/3062
