### ISSUE TITLE
ostree export and hard links

### ISSUE THREAD

**Issue by owtaylor** [ostreedev/ostree#2925]
I tried converting https://hub.docker.com/_/busybox into a OCI-format Flatpak, and got instead of a 2MB result, a 240MB result.
The busy box filesystem has all of the /usr/bin images hardlinked together - they were all separate files in the layer tarfile.

I think the problem is that ostree_repo_export_tree_to_archive(), which Flatpak and 'ostree export' use simply never writes a hard link. It probably should keep track of what checksums have been seen and when the same checksum is seen again, write a hardlink rather than a regular file.

Since ostree doesn't maintain a difference between "duplicated file" and "hardlinked file", this would also reduce archive size when the original filesystem tree had non-hardlinked duplicated files.

If hardlinking duplicated files in the 'ostree export' output is seen as a problem or compatibility break, then it would be useful if OstreeRepoExportArchiveOptions had a new option that Flatpak could use when creating OCI layer archives.

**Comment by cgwalters** [comment]
Note the new ostree-container stuff that lives instead in https://github.com/ostreedev/ostree-rs-ext/ does deduplicate things - though it *also* forces on an ostree-style filesystem layout.

**Comment by owtaylor** [comment]
Having a common format between ostree-rs-ext and Flatpak would be awesome - and maybe that common format could just be the ostree-rs-ext format... I have not analyzed the situation at all.[*] But that's definitely a long term thing, since even if we implemented support for reading ostree-rs-ext style commits today, we wouldn't be able to deploy them until that was available in most Flatpak clients.

So this is definitely worthwhile in the short term. If the busybox example seems contrived - here's the stats for the Fedora Flatpak runtime: 

   compressed layer size as we write it today: 1345M
   After untar, hardlink(1), tar:  712M 

So this is almost doubling the size!

[*]  off the top of my head: the ostree format makes things harder for delta generation, because tardiff uses filenames as hints - but that could be overcome with some level of complexity.
