### ISSUE TITLE
Provide a way to add a ref to an existing commit

### ISSUE THREAD

**Issue by jlebon** [ostreedev/ostree#300]
Making a note of this here since I again found a need for it. Not sure in which subcommand it would go, but this should be trivial to implement with a single call to `ostree_repo_set_ref_immediate()`.

**Comment by jlebon** [comment]
Oh right, there's @cgwalters's [ostree-write-ref](https://github.com/cgwalters/ostree-scripts/blob/master/ostree-write-ref), but this should really be built in.

**Comment by yuqi-zhang** [comment]
A followup to the subcommand, should it go under "ostree refs"? Maybe "ostree refs add ORIGIN NEW" to add a NEW ref to an existing ORIGIN ref?

**Comment by jlebon** [comment]
Hmm, or maybe we should just make `ostree commit` smarter so that if it's only given `--tree=ref=COMMIT`, it knows not to create a new commit for it? Though there might be use cases for having that ability as well.

Or maybe `ostree refs my_ref --create=my_new_ref`?

**Comment by yuqi-zhang** [comment]
I think the second one is more preferable, since as you said, the first option could have other use cases, and "ostree commit" is intuitively creating a new commit anyways.

**Comment by cgwalters** [comment]
One thing I think is important about the write-ref code above was that it acted like `git tag` in refusing to create if one already existed.  Something to consider for this.

**Comment by yuqi-zhang** [comment]
Currently the existing "commit --tree=ref=foo --branch=bar" overwrites the existing bar to foo without any warning. Should that also not happen? Or should commit ask "ref bar already exists, would you like to overwrite? y/n"

**Comment by jlebon** [comment]
Think of it as "committing" to the branch (in the git sense), rather than overwriting. The previous commit will still be available as the parent of the new ref (e.g. using `ostree show bar^`).

**Comment by yuqi-zhang** [comment]
Ah I see, I will make sure that "ref --create" doesn't overwrite existing refs then

**Comment by jlebon** [comment]
This was fixed in #340.
