### ISSUE TITLE
Mount /sysroot with read-write permissions

### ISSUE THREAD

**Issue by Tibi09** [ostreedev/ostree#3076]
Hi!
I am relative new to ostree and I am trying to perform an atomic upgrade on a machine with Atomic Host and ostree version 2019.1 (the upgrade is made via HTTP). In the new image, the ostree will have the version 2023.7 and I also want the /sysroot to be mounted with read-write permissions. As far as I understand, in the newer versions of ostree, the default mode in which the sysroot is mounted is read-only. I found out that there is a configuration option in the /sysroot/ostree/repo/config file in the sysroot section, "readonly=true/false". So, when I created the repository containing the upgrade (the steps are below), I also set this flag to "false". But after the instalation finished, the /sysroot was still mounted read-only and in the /sysroot/ostree/repo/config file the flag was set to "true". Moreover, it seems that after this, the changes I make in the current deployment to the config file remain valid for the newly installed images as well. In other words, it seems that this config file is not updated between upgrades any more. Am I doing something wrong or is there another way to mount the /sysroot read-write?

Steps made to create the new repo with the upgrade:

```bash
ostree --repo=path/to/repo init --mode=archive-z2
ostree config --repo=path/to/repo set "sysroot.readonly" "false"
rpm-ostree compose tree --unified-core --repo=path/to/repo jsonfile.json
```

The created repo/config file:
```
[core]
repo_version=1
mode=archive-z2

[sysroot]
readonly=false
```

The /sysroot/ostree/repo/config file on the current deployment:
```
[core]
repo_version=1
mode=bare
```

The /sysroot/ostree/repo/config file after the upgrade:
```
[core]
repo_version=1
mode=bare

[sysroot]
readonly=true
```

Steps made for the upgrade:

```bash
ostree remote add my_remote_name my_url
rpm-ostree rebase my_remote_name:my_branch_name
reboot
```

Thank you!

**Comment by cgwalters** [comment]
>  As far as I understand, in the newer versions of ostree, the default mode in which the sysroot is mounted is read-only.

That's not currently true; for backwards compatibility reasons it's off by default.  You may be using a buildsystem that turns it on?  For example in coreos-assembler and osbuild it's turned on by default.

> Moreover, it seems that after this, the changes I make in the current deployment to the config file remain valid for the newly installed images as well. In other words, it seems that this config file is not updated between upgrades any more.

Yes, today the ostree repository configuration is *not* updated in place, and must be managed "out of band".  See e.g. https://gitlab.com/redhat/centos-stream/rpms/ostree/-/blob/c9s/ostree-readonly-sysroot-migration.service?ref_type=heads which is shipped downstream for now, though it would make sense to upstream too.

Does that help?

**Comment by Tibi09** [comment]
Yes, the ostree-readonly-sysroot-migration service seemed to be the problem. Thank you!
