### ISSUE TITLE
Many tests fail in 2023.7 on s390x: _ostree_bootloader_zipl_post_bls_sync: assertion failed: (self->sysroot->booted_deployment)

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#3084]
Debian builds libostree in a chroot. In that environment, 25 tests fail with something similar to:

`ERROR: tests/test-admin-upgrade-unconfigured.sh - Bail out! OSTree:ERROR:src/libostree/ostree-bootloader-zipl.c:387:_ostree_bootloader_zipl_post_bls_sync: assertion failed: (self->sysroot->booted_deployment)`

Did #3059 perhaps not account for the fact that it's possible, and indeed likely during unit testing, that there should be no active boot loader at all?

cc @cgwalters

**Comment by smcv** [comment]
Alternatively, do the tests need to be skipping bootloader setup if `!self->sysroot->booted_deployment`?

**Comment by cgwalters** [comment]
This is on s390x right?  

> Did https://github.com/ostreedev/ostree/pull/3059 perhaps not account for the fact that it's possible, and indeed likely during unit testing, that there should be no active boot loader at all?

Yes, you're right.
