### ISSUE TITLE
No download progress when rebasing to a container image

### ISSUE THREAD

**Issue by jbtrystram** [ostreedev/ostree#3118]
When rebasing to a container image, the inital download of the image layers before the rebase opration takes some time, and there is no indication of something happenning in the terminal .

I first I thought rpm-ostree was hung up on something, but it was just network IO.
Here is an example: 
```
rpm-ostree rebase ostree-unverified-image:registry:quay.io/jbtrystram/fedora-kinoite-main:39
Pulling manifest: ostree-unverified-registry:quay.io/jbtrystram/fedora-kinoite-main:39
Importing: ostree-unverified-registry:quay.io/jbtrystram/fedora-kinoite-main:39 (digest: sha256:27d010480f27bd83dc0e7f33002a6361448c081c75ed1517387659655eeee012)
ostree chunk layers needed: 65 (2.5 GB)
custom layers needed: 2 (407.8 MB)

```

This step takes a couple of minutes but no progress is shown. It would be a nice improvement to have something to help with the wait. 
I ll try to take a look !

**Comment by codegod100** [comment]
journalctl -u rpm-ostreed -f

**Comment by jbtrystram** [comment]
I just noticed that it show progress now.
