### ISSUE TITLE
Licensing Debate

### ISSUE THREAD

**Issue by Mathnerd314** [ostreedev/ostree#313]
Revisiting the licensing question from https://github.com/ostreedev/ostree/pull/305#issuecomment-221243161, what is the reason for OSTree to be LGPL licensed?

Maybe Apple or Google would like to use the code, but in that case it would probably have to be even more permissively licensed, BSD or something.

On the other hand, making it GPL would make it easier to share code with other open-source projects (for example, Git). And the GNU project recommends using GPL for new libraries: http://www.gnu.org/licenses/why-not-lgpl.en.html, particularly for "unique" libraries that will typically only be found on free operating systems.

**Comment by cgwalters** [comment]
One thing I think the FSF's recommendations don't capture well is that it's very common for code to flow from applications into libraries.  In particular ostree shares with LGPL ecosystems such as GNOME and more recently systemd.

The recent discussion in systemd land about extracting some of its internals as a shared library is enabled by having the apps themselves be LGPL.

If we're talking about the test suite though I'm not opposed to adding GPL code there, it'd just have to be somewhat compelling, and I'm not sure what of git's code would be there for us.

Several projects apparently use https://github.com/sstephenson/bats/ which sounds nice, see discussion in https://github.com/projectatomic/bubblewrap/issues/10

**Comment by cgwalters** [comment]
So, I hope this answers the question.  For me, sharing code with systemd is more important than sharing code with git.
