### ISSUE TITLE
rofiles-fuse: does not compile with musl (v2024.4)

### ISSUE THREAD

**Issue by YukariChiba** [ostreedev/ostree#3200]
I noticed that https://github.com/ostreedev/ostree/commit/4d95848b8c5d2bc400bcf795e5307f01b404dcd4 introduced `statx` which is not supported by [musl](http://musl.libc.org/).

To reproduce, compile ostree v2024.4 with any musl-based distro (e.g, alpine).

**Comment by cgwalters** [comment]
Hmm, messy.  I wonder if musl users care about rofiles-fuse?   Hmm, looks like flatpak-builder uses it.

Well, this is a bit painful as the code is significantly cleaner with statx...

And OK wow, where is the issue tracker for musl?  (OK, some digging through the mail-archives-as-bug-tracker leads to https://www.openwall.com/lists/musl/2020/01/19/7 so we're hardly the first to hit this pain)

**Comment by cgwalters** [comment]
Per https://lwn.net/Articles/964181/ 

> On February 29, the musl project [announced](https://www.openwall.com/lists/musl/2024/03/01/2) release 1.2.5, including support for loongarch64 and riscv32. This release also contains support for the [statx()](https://www.man7.org/linux/man-pages/man2/statx.2.html), [preadv2(), and pwritev2()](https://man7.org/linux/man-pages/man2/readv.2.html) system calls.

So...dunno.  I guess my inclination here is to recommend that musl users carry a downstream patch to revert the commits in https://github.com/ostreedev/ostree/pull/3175
until such time as they can update to the new musl.

And I guess we need to add a CI job here that covers alpine.

**Comment by YukariChiba** [comment]
It's been a while since musl 1.2.5 was released. It's basically a non-issue now.
