### ISSUE TITLE
Remove "RHIVOS"; CentOS Automotive SIG uses OSTree for AutoSD

### ISSUE THREAD

**Issue by kleinffm** [ostreedev/ostree#3225]
Red Hat In-Vehicle Operating System does not officially use the acronym "RHIVOS"; it's only short form is Red Hat In-Vehicle OS. Please delete this acronym.

The CentOS Automotive SIG publishes topics about [how it uses OSTree](https://sigs.centos.org/automotive/building/updating_ostree/) in its Automotive Stream Distribution (AutoSD) if you'd like to link to that also or instead.

Thank you!

**Comment by ericcurtin** [comment]
#3226
