### ISSUE TITLE
/usr/lib/ostree/prepare-root.conf default config is not shipped 

### ISSUE THREAD

**Issue by jbtrystram** [ostreedev/ostree#3293]
I noticed today that there is no `prepare-root.conf` default config file in `/usr/lib/ostree` on my machine. The same can be observed on coreOS.

[This script](https://github.com/ostreedev/ostree/blob/main/src/boot/dracut/module-setup.sh) is supposed to copy it in the initramfs but it's not there in the first place. 

The man page of ostree-prepare-root says it should be there, but i can't find it even in this repo. So maybe it was deleted by accident at some point ?  

I just checked the latest RPM (https://koji.fedoraproject.org/koji/buildinfo?buildID=2513490) and it's not in there either.

**Comment by jbtrystram** [comment]
So i guess the default config of ostree-prepare-root should be provided by the distribution shipping ostree rather than ostree.

**Comment by travier** [comment]
It was added to https://ostreedev.github.io/ostree/man/ostree-prepare-root.html in https://github.com/ostreedev/ostree/commit/22b8e4f953ed183a368ec97ce7f74337b1574045.

**Comment by travier** [comment]
We could update the man page as it's not mandatory but recommended.
