### ISSUE TITLE
init-fs: set `--epoch=2` as default for `--modern`

### ISSUE THREAD

**Issue by travier** [ostreedev/ostree#3298]
Following https://github.com/ostreedev/ostree/pull/3230, which introduced `ostree init-fs --epoch=2` to address https://github.com/ostreedev/ostree/issues/3211, we should consider making it the default.

It breaks unprivileged calls to `rpm-ostree db diff` but it should probably should not block us from doing it.

Or we could consider doing it in bootc only as we don't have such as command there and bootc is root only: https://github.com/containers/bootc/blob/858b4fb2848c68102ddbcdd7a42e10835286e98c/lib/src/install.rs#L584

**Comment by cgwalters** [comment]
The whole reason for making it a new thing was to allow people to opt-in to the change. I've been keeping ostree pretty conservative to avoid breaking people. 

And in this specific instance, we know it breaks something.

As far as deeper changes in this area, I think the real fix is to go "dedicated composefs" where we e.g. don't even do the hardlink checkout. This also relates to https://github.com/ostreedev/ostree/issues/2933 and https://github.com/ostreedev/ostree/issues/3291

But all of this collides more with https://github.com/containers/bootc/issues/20 where I want to really have something more container-native as the storage heart.

So, closing.
