### ISSUE TITLE
Readthedocs site says it was hacked

### ISSUE THREAD

**Issue by genodeftest** [ostreedev/ostree#3312]
The readthedocs site `https://ostree.readthedocs.io/en/latest/` says it was hacked. That site is referenced multiple times across the repos so I guess it should be the legit documentation website.

**Comment by Khursipar** [comment]
Hi 👋  bro meri madam Kar do plz

**Comment by cgwalters** [comment]
Ouch. Thanks for the report. I'm not sure  I submitted https://github.com/ostreedev/ostree/pull/3313 - the only place I found a reference was the Rust bindings.

**Comment by Khursipar** [comment]
https://gold365.site/m/login hack

**Comment by Khursipar** [comment]
> Ouch. Thanks for the report. I don't remember now what the credentials setup was for that. A bit...lame...for this researcher to just take over sites permanently. In any case the GH pages setup should be more secure in the sense that it doesn't have distinct credentials to publish anything.
> 
> I submitted #3313 - the only place I found a reference was the Rust bindings.

Hi sir https://gold365.site/m/login

**Comment by genodeftest** [comment]
Thanks! It might make sense to contact the `readthedocs.io` support to get the site back.

Some references still point to the readthedocs URL, for example the Fedora package's metadata ([PR to change that](https://src.fedoraproject.org/rpms/ostree/pull-request/40)). There might be more in other upstreams.
