### ISSUE TITLE
bootc: symbol lookup error: /lib64/libostree-1.so.1: undefined symbol: g_unix_mount_entry_free

### ISSUE THREAD

**Issue by henrywang** [ostreedev/ostree#3338]
bootc install failed with error `bootc: symbol lookup error: /lib64/libostree-1.so.1: undefined symbol: g_unix_mount_entry_free`.
And `ostreecontainer` command in anaconda deploy failed with error:
```
The command 'ostree admin instutil set-kargs console=ttyS0,115200n8
boot=UUID=b4bfca43-f43d-408f-aabc-256b37920086 rd.lvm.lv=fedora_vm-1/root fips=1
root=UUID=fd7fb6a2-5094-4dfd-97b0-f831e0244c07 vconsole.keymap=us rw' exited
with the code 127.
```

ostree version: `ostree-2024.9.4.g8705495b-1.fc42.x86_64`

**Comment by cgwalters** [comment]
> fc42

OK so this is Fedora rawhide. 

> symbol lookup error: /lib64/libostree-1.so.1: undefined symbol: g_unix_mount_entry_free.

This is probably a regression in glib2. Oh I see looking at recent changes there I see https://gitlab.gnome.org/GNOME/glib/-/commit/aac56f1618aabfcf4c6b3ef1ee5b87322208e9ad and I think what's going on here is skew between the build and runtime deps. Basically we need to ensure that we have the updated glib2 in the runtime environment too, so we need to ensure the testing here is operating from a rawhide base image.

**Comment by cgwalters** [comment]
This is a dup of https://gitlab.com/fedora/bootc/tracker/-/issues/46 - basically f42 is broken because of kdump.
