### ISSUE TITLE
Issues with ref (tmp file cleanup, deleting folders, commit/create conflict with remote)

### ISSUE THREAD

**Issue by yuqi-zhang** [ostreedev/ostree#338]
Currently there are 3 minor issues with refs:

1 ostree_repo_transaction_set_ref and ostree_repo_set_ref_immediate should clean up .tmp files on failure

Currently, if a ref "foo/bar" exists (foo is a folder), and a user tries to create foo, the API functions ostree_repo_transaction_set_ref and ostree_repo_set_ref_immediate in ostree-repo-commit.c would fail, and create a .tmp file (in the format of .tmpABCDE). ostree_repo_transaction_set_ref needs to abort the transaction or the .tmp file is not cleaned up. ostree_repo_set_ref_immediate will always create the .tmp file. This should be cleaned up on failures.

2 allow deleting of folders in ref

Currently, if a ref "foo/bar/baz" exists, and a user either "refs --delete foo" or "refs --delete foo/bar/baz", only the "baz" file gets deleted. All folders (both in local and remote) cannot be deleted unless the user goes into the refs folder and manually rm. The folders don't actually show up in "refs --list" and could cause much hassle. They should be deleted when a) the user specifies to delete or b) when the folder is empty of refs.

3 allow local refs with same name as remote refs/folders, for both commit and ref --create

Currently, if there is a remote ref "remote:foo/bar" or "remote:foo", and the user wants to create a local ref of the name "foo", either through "commit" or "refs --create" (new option), ostree errors saying that the folder "foo" exists, even though it is in the "remote" and not local. The user should be able to create a local ref called foo, which is not affected by the remote repo.

**Comment by jlebon** [comment]
@yuqi-zhang I think all of these are fixed now, no?

**Comment by yuqi-zhang** [comment]
I believe so, I'll close this now
