### ISSUE TITLE
remove hotfix from origin on upgrades

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#339]
Otherwise it shows up as incorrectly hotfixed.

**Comment by cgwalters** [comment]
Also related to this...we need to consider whether to require some sort of flag to upgrade-and-drop-hotfixes.

`ostree admin upgrade --drop-hotfix` or something?

**Comment by jlebon** [comment]
That sounds reasonable. It enforces the idea that hotfixes are only meant for dire situations.

**Comment by jlebon** [comment]
To elaborate on what I meant: if you had to resort to a hotfix, then you probably want to be careful when doing an upgrade to ensure your hotfix won't be needed anymore.

**Comment by cgwalters** [comment]
Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1346335

**Comment by Mathnerd314** [comment]
Hotfix is a property of the deployment, not the remote. I'm not sure why OSTree stores unlocked=hotfix on the remote at all, since the deployment can just check for .usr-ovd-work.

As far as upgrades, could OSTree do a 3-way merge for hotfixes like with /etc?

**Comment by cgwalters** [comment]
It's stored in the `.origin` file.  We certainly could investigate replaying the hotfix on top of upgrades.  The only ugly part would be extracting the data from overlayfs.

**Comment by cgwalters** [comment]
This is really an rpm-ostree issue, submitted: https://github.com/projectatomic/rpm-ostree/pull/322
