### ISSUE TITLE
Requires glib 2.40 but needs glib 2.44

### ISSUE THREAD

**Issue by hadess** [ostreedev/ostree#376]
https://github.com/ostreedev/ostree/blob/master/configure.ac#L50 says:
```
GIO_DEPENDENCY="gio-unix-2.0 >= 2.40.0 libgsystem >= 2015.1"
```

But G_DEFINE_AUTOPTR_CLEANUP_FUNC is used in the code, which makes it need 2.44.

**Comment by smcv** [comment]
`libglnx/glnx-backport-autoptr.h` provides a backport of `G_DEFINE_AUTOPTR_CLEANUP_FUNC`. What is the exact build failure that you're seeing? In the past this has been addressed by commits like d3686247.

I've seen ostree 2016.6 + some cherry-picked commits (see <https://anonscm.debian.org/cgit/collab-maint/ostree.git/tree/debian/patches>) building and passing tests on Debian 8 (Glib 2.42), so I know this is possible.
