### ISSUE TITLE
An OStree remote without DirectoryIndex fails with a `404 Not Found`

### ISSUE THREAD

**Issue by gbraad** [ostreedev/ostree#388]
A remote that has been added, that has no index page, and therefore returns a `404`, will return an error. This happens when a remote server does not offer a DirectoryIndex.

Either the user has to provide an empty index.html to make it work (index is not needed to retrieve the actual ostree). Or, `ostree` checks for the existence of `[url]/config` instead. If this would return a 200, it can be assumed the repository exists and 'works'.

**Comment by cgwalters** [comment]
I often use:
```
docker run --name nginx-root -p 80:80 -v /var/srv:/usr/share/nginx/html:ro -d nginx
```
to expose my `/srv` directory on my workstation to VMs/containers.  And in this configuration nginx isn't configured to allow directory listings, so it `403`s. Accessing ostree repos in `/var/srv` definitely works though.

Are you sure you didn't just typo the remote location?

**Comment by gbraad** [comment]
I'll check again over the weekend...

**Comment by cgwalters** [comment]
Feel free to reopen if there is an issue here.
