### ISSUE TITLE
Regression in "ostree admin upgrade"

### ISSUE THREAD

**Issue by gatispaeglis** [ostreedev/ostree#405]
https://github.com/GNOME/libglnx/commit/40ef5f7400d4f8eed6a8f834917008b33ad4fb4e Introduced a regression.

Example:

input_text="588 metadata, 6952 content objects fetched; 196612 KiB transferred in 269 seconds"
ncolumns=40
const guint spacelen = ncolumns - input_textlen; // negative value assigned to uint.

This results in a console infinitely printing empty lines.

**Comment by cgwalters** [comment]
Closed by https://github.com/ostreedev/ostree/pull/406
