### ISSUE TITLE
don't execute static deltas for mirroring

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#407]
Currently we abort:

```
15:11:37 + ostree --repo=repo remote delete centos-atomic-continuous
15:11:37 + ostree --repo=repo remote add --set=gpg-verify=false centos-atomic-continuous http://artifacts.ci.centos.org/sig-atomic/rdgo/centos-continuous/ostree/repo
15:11:37 + ostree --repo=repo pull --mirror --disable-fsync --depth=0 --commit-metadata-only centos-atomic-continuous centos-atomic-host/7/x86_64/devel/continuous
15:11:37 
15:11:37 OSTree:ERROR:src/libostree/ostree-repo.c:3017:_ostree_repo_read_bare_fd: assertion failed: (self->mode == OSTREE_REPO_MODE_BARE || self->mode == OSTREE_REPO_MODE_BARE_USER)
15:11:37 /home/builder/sig-atomic-buildscripts/centos-ci/libtoolbox.sh: line 3: 21574 Aborted                 ostree --repo=repo pull --mirror --disable-fsync --depth=0 --commit-metadata-only centos-atomic-continuous ${ref}
```

**Comment by cgwalters** [comment]
Also, using --commit-metadata-only should likely disable deltas?

**Comment by Mathnerd314** [comment]
There are several `(repo->mode == OSTREE_REPO_MODE_BARE || repo->mode == OSTREE_REPO_MODE_BARE_USER)` assertions in the delta code. Does this only happen with mirroring, or with all attempts to use deltas and archive-z2?

> Also, using --commit-metadata-only should likely disable deltas?

Deltas can have fallbacks, in which case the normal commit-pulling code is called, so the combination of `OSTREE_REPO_PULL_FLAGS_COMMIT_ONLY` and deltas does have a small, reasonable effect. On the other hand, I will note that git has no equivalent flag; is `commit-metadata-only` actually useful? IIRC most commits are a timestamp and not much else.

**Comment by cgwalters** [comment]
Closed by https://github.com/ostreedev/ostree/pull/408
