### ISSUE TITLE
Static deltas with no checksums

### ISSUE THREAD

**Issue by dbnicholson** [ostreedev/ostree#419]
I was experimenting with static delta management and made a delta between 2 commits that were exactly the same but different revisions. The delta was created successfully, but later `_ostree_static_delta_parse_checksum_array` returned an error because there were no checksums.
```
$ ostree static-delta show 5824a0ce049681f17d4c7a40c51b8d1338b8d5131f79f29157066cf89f53b9bd-9617d9c15ba643ccf566b2cdf793d46f3b9bc42d392b1ac2940e9311e232e2c8
...
Delta: 5824a0ce049681f17d4c7a40c51b8d1338b8d5131f79f29157066cf89f53b9bd-9617d9c15ba643ccf566b2cdf793d46f3b9bc42d392b1ac2940e9311e232e2c8
Endianness: little
Timestamp: 1469740860
Number of parents: 0
Number of fallback entries: 0
Total Fallback Size: 0 (0 bytes)
Total Fallback Uncompressed Size: 0 (0 bytes)
Number of parts: 1
PartMeta0: nobjects=0 size=61 usize=0
PartPayload0: nmodes=0 nxattrs=0 blobsize=0 opsize=0
error: Invalid checksum array length 0
```
Should ostree refuse to generate these empty deltas or should the check be relaxed? It looks like `_ostree_static_delta_part_execute` has an assertion that there are more than 0 checksums, although `_ostree_repo_static_delta_part_have_all_objects` looks like it would succeed.

**Comment by cgwalters** [comment]
I think I'd vote to:

 - Accept empty deltas since they may have been generated before
 - Refuse to generate new ones ?

**Comment by dbnicholson** [comment]
That does sound like the best plan, but I worry about refusing to generate them now that I think about it. If that's going to become an error, then the caller has to somehow check ahead of time if the contents of the commits are the same. That seems annoying, and I'm not sure how you'd do it.

So, I think generating and accepting these useless deltas is probably the safest thing to do for users. It doesn't really hurt anything.

**Comment by cgwalters** [comment]
Closed by https://github.com/ostreedev/ostree/pull/420
