### ISSUE TITLE
wrong releases page on github?

### ISSUE THREAD

**Issue by vtolstov** [ostreedev/ostree#503]
```
9 hours ago  v2016.10  …  36e8ba1   zip   tar.gz
9 days ago v2016.9  …  dd71999   zip   tar.gz
Latest release
 v2016.8  73eabca Verified 2016.8
@cgwalters cgwalters released this on Aug 9 · 57 commits to master since this release

```

Why latest so old?

**Comment by vtolstov** [comment]
As i understand 2016.8 create via release feature of github, and contains attachment (tar.xz)
But latest releases created only tag without attach. Does it possible to create tar.xz and attach to release on github?

**Comment by smcv** [comment]
I would also appreciate tarball releases: they're what the Debian packaging expects.

Alternatively, if ostree is deliberately no longer producing tarball releases, I'll adapt the Debian packaging so it alerts Debian contributors when there's any new tag (not just a "release" with release notes as it does now), and has a script to produce Debian-specific tarballs with the submodules included.

**Comment by cgwalters** [comment]
I'll try to commit to running `make dist`.

https://github.com/ostreedev/ostree/releases/tag/v2016.11

**Comment by vtolstov** [comment]
thanks!
