### ISSUE TITLE
No gpg verification of commits if using static deltas

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#517]
I accidentally got a few commits signed with the wrong gpg key, but you can download these fine, as long as you use static-deltas (the summary is signed with the correct key).

Is this the expected behaviour? I have both gpg-verify and gpg-verify-summary set in the remote config.

I understand that there is some level of trust from the signed summary, but it would cause less confusing errors if gpg-verify=true means we always require signed commits.

**Comment by cgwalters** [comment]
Yes, this is a flaw.  It looks like we are putting the detached metadata in the delta, so in the pull path we need to extract that and use it.

An open question here is in the situation where there's no signatures in the "detached" metadata baked into the delta whether we should go out and request it.
