### ISSUE TITLE
Badfile descriptor loading commit with libostree

### ISSUE THREAD

**Issue by simao** [ostreedev/ostree#532]
I am trying to load a commit with libostree using the following code:

```C
GFile* file = NULL;

file = g_file_new_for_path("/home/simao/ostree/arch");

gboolean exists = g_file_query_exists(file, NULL);

if (exists == FALSE) {
  printf("does not exist!\n");
}

OstreeRepo* repo = ostree_repo_new(file);

g_autoptr(GVariant) commit = NULL;

OstreeRepoCommitState commitstate;

GError *error = NULL;

gboolean res = ostree_repo_load_commit(repo,
    "0d346553459730f48924705ee467c4a5a78fde9409bd489e72bfcf4a7adf8a29",
    &commit,
    NULL,
    &error);

if(res == FALSE) {
  printf ("error: %s\n", error->message);
  printf ("code: %s\n", error->code);
}
```

This just outputs:

```
error: Bad file descriptor
code: (null)
```

Am i doing something wrong? How can I get more information about the error?

The repository and the commit exist and the path is correct.

Thank you.

**Comment by jlebon** [comment]
Try opening the repo first with `ostree_repo_open`.

**Comment by simao** [comment]
Thanks very much for your help, this now works.

What I am trying to do is to read the parent commit of a commit. Sometimes I don't have access to the entire repository and I only have the object file of the commit, for example `<myrepo>/objects/4f/32315f837a63f5cf307026622464d5c86977c177ec7d2095b9d6567371b4f6.commit`. Can I use `libostree` to read the metadata from that file or I always need the full repo to use `libostree`?

**Comment by cgwalters** [comment]
You can use `ostree_repo_load_variant_if_exists()` to try to load a commit, if you have partial history.

**Comment by simao** [comment]
I'll try that, but for that I still need to `ostree_repo_open` some partial repo, right? So I can't just have that object file in the repo?

**Comment by cgwalters** [comment]
`ostree_repo_open` doesn't parse any of the objects, it will work just fine on an empty repository or one with partial commits, or for that matter one with corrupted objects.

**Comment by simao** [comment]
yes, this works, but I do need to setup a dummy repo before I can read it, `ostree_load_variant_if_exists` needs a `config` file and a `tmp` directory. 

Thanks!

**Comment by cgwalters** [comment]
Oh, you somehow have just a `.commit` file?  Yeah, you could just manually copy it into a repo.  Glad you have it solved.
