### ISSUE TITLE
commitpartial data shared between multiple pulls can break

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#543]
There seem to be an issue with how pull handles partial commits.
If we're pulling some metadata, and its already locally available (is_stored in scan_one_metadata_object_c) then we don't scan it, assuming we have all the dependencies.
However, this is not right if the object stored locally is from a partial commit.

The code _does_ somewhat handle this case, by always scanning if pull_data->commitpartial_exists is set. However, that is only set if the commit we're pulling has a local commitpartial marker. However, that is not the case here, we're only just pulling this commit, instead the local metadata object is from _another_ partial commit.

**Comment by cgwalters** [comment]
I think it'd fix this to do full scans for dirtree/dirmeta always, and just leave the "assume is complete" optimization for commits.

**Comment by cgwalters** [comment]
Potential fix in https://github.com/ostreedev/ostree/pull/564
