### ISSUE TITLE
--commit-metadata-only pulls static deltas

### ISSUE THREAD

**Issue by gatispaeglis** [ostreedev/ostree#586]
Tested with: ostree 2016.8
When the ostree repository on the sever contains `deltas/` then:

`ostree pull --commit-metadata-only $os $branch`

will pull delta files, even if all we want is *commit-metadata-only*. To disable pulling static deltas, we have to explicitly add `--disable-static-deltas`:

`ostree pull --commit-metadata-only --disable-static-deltas $os $branch`

But this should not be necessary as we already explicitly say `--commit-metadata-only`

**Comment by cgwalters** [comment]
Dup of https://github.com/ostreedev/ostree/issues/528 looks like, please reopen if not.

**Comment by gatispaeglis** [comment]
Indeed, looks like a duplicate.
