### ISSUE TITLE
question: ostree admin upgrade does it twice

### ISSUE THREAD

**Issue by johan-smits** [ostreedev/ostree#640]
When we run a _ostree admin upgrade_ it deploys a new one (when there is one).
When you run it again (and you did not reboot yet to the new one) it does a redeploy of the already deployed again.
Why does it redeploy when the last one was successful?

We want to _cron_ the upgrade task on the desktops but we are limited to daily because we do not want to reboot automatically but we want to check for updates more frequently.

**Comment by cgwalters** [comment]
You can do the "download but don't deploy" with a raw "ostree pull".  We don't have good porcelain for this right now though.

**Comment by paulvt** [comment]
One would expect `ostree admin upgrade` downloads and decides not to deploy if it already has done so.
You do get this desired behaviour if you are already booted to the newest OS:

```
$ sudo ostree admin upgrade

1 metadata, 0 content objects fetched; 313 B transferred in 0 seconds                                                   
No update available.
```

**Comment by cgwalters** [comment]
Yes - it's complex, one reason we do a redeploy is to re-do copying /etc, in case there were any changes.  See also https://github.com/projectatomic/rpm-ostree/issues/40

Big picture, at some point I'd like to merge the "pure ostree daemon" code from https://github.com/endlessm/eos-updater into ostree, and have it support things like "background pull of updates, deploy last pulled and reboot".

**Comment by cgwalters** [comment]
Daemon aside, I think it'd be pretty easy to implement:

```
ostree admin upgrade --pull-only  # Run this in a cron job
ostree admin upgrade --deploy --reboot # Run this to actually do the deployment, just before rebooting
```

**Comment by johan-smits** [comment]
We use it in a desktop environment and we want to prevent a reboot (users can be working on their desktop and do not appreciate a reboot in the middle of their work).

Will have a look at https://github.com/endlessm/eos-updater

**Comment by cgwalters** [comment]
I took a quick crack at this in https://github.com/ostreedev/ostree/pull/642

**Comment by cgwalters** [comment]
Going to close this as fixed by https://github.com/ostreedev/ostree/pull/642 - but I only lightly tested that, so feel free to reopen.  There's definitely bigger picture stuff here around having better tooling than raw `ostree admin upgrade` to fix, but I think the raw functionality is there now.
