### ISSUE TITLE
RFE: support JSON output for 'ostree show'

### ISSUE THREAD

**Issue by miabbott** [ostreedev/ostree#649]
Would be a nice to have.

Something like this?

```
$ ostree show --json 59d072dac8ec0001c498c61cec480f8684ba94738b9073d5fd4f6fdc49095a79
{
    "commit": "59d072dac8ec0001c498c61cec480f8684ba94738b9073d5fd4f6fdc49095a79",
    "subject": "(no subject)",
    "timestamp": 1484755876,
    "version": "7.2017.41"
}
```

Not sure if it would be useful when only printing a single metadata key, etc.

**Comment by cgwalters** [comment]
Nice to have to do what though?   This would bring in a json-glib dependency to ostree which I'm not totally opposed to but would like to avoid just for this.

If this is for tests...one can access the raw commit GVariant data via the API.  See [this script](https://github.com/cgwalters/ostree-releng-scripts/blob/master/print-current-version) for an example.  (In practice for e.g. Atomic Host you'd probably want to do this in a container, with `/host/ostree/repo` mounted in)

**Comment by miabbott** [comment]
> Nice to have to do what though? This would bring in a json-glib dependency to ostree which I'm not totally opposed to but would like to avoid just for this.

Because everyone needs more JSON in their lives?  :)

Jokes aside, it was related to some Jenkins job I was working on, but not critical to it's success.

I think the script is a good enough example, in the event I do need to parse the commit data.
