### ISSUE TITLE
Question: If not ostree will be the tool for commit, what is?

### ISSUE THREAD

**Issue by ortogonal** [ostreedev/ostree#666]
The commit message of 7803fe1d60f32f659555acf32a8812a45ab15792 states the ostree just is a demo tool for libOSTree. It says "Let's make that more obvious, so people don't
try to use `ostree admin upgrade` for their real systems, and also don't use
e.g. `ostree commit` on the command line outside of test suites/quick hacking."

I've been using OSTree for full OS updates on embedded devices with ostree and som scripts. If ostree commit is just for quick hacking which tools shall I use for "none quick hacking"?

**Comment by cgwalters** [comment]
Yes, that was poorly phrased.  We will continue to support *all* current features of the command line.  I think I would just like to encourage the development of more sophisticated build systems that use the API.
