### ISSUE TITLE
static-delta generation flake?

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#736]
Seeing a core dump I think from `static-delta generate`.  [For example](https://github.com/ostreedev/ostree/pull/733#issuecomment-286124175):

```
+ env LD_PRELOAD=/var/tmp/checkout/tests/libreaddir-rand.so ostree --repo=ostree-srv/exampleos/repo static-delta generate '--from=exampleos/42/standard^^' '--to=exampleos/42/standard^'
  To:   e16208ef1844df7c3f84e6019f75336bfd190e43235cff05b3ead176633e6a8d
Generating static delta:
  From: e16208ef1844df7c3f84e6019f75336bfd190e43235cff05b3ead176633e6a8d
timeout: the monitored command dumped core
  To:   f36cecf42b1f21668b1ef1cd298a682bfc0e75b1561368f43d1618416cd49fe5
ERROR: tests/test-pull-many.sh - missing test plan
ERROR: tests/test-pull-many.sh - exited with status 124
```

**Comment by cgwalters** [comment]
I ran delta generation in a loop for a day, but couldn't get it to crash.

**Comment by jlebon** [comment]
I was playing with enabling automatic core dump collection & uploads in RHCI to make this easier in the future. Jotted down some initial ideas in https://github.com/jlebon/redhat-ci/issues/31.

**Comment by cgwalters** [comment]
Haven't seen this in quite a while.
