### ISSUE TITLE
Investigate pull-local flakes

### ISSUE THREAD

**Issue by jlebon** [ostreedev/ostree#751]
We seem to be hitting this more and more often in the PR testers now:

```
+ ostree --repo=ostree-srv/exampleos/build-repo commit --link-checkout-speedup -b exampleos/42/standard --tree=dir=main
c6b5a9566db4370a872418c60d029fae63b5cb827d7b611ca917a0c45a420fdd
+ ostree --repo=ostree-srv/exampleos/repo pull-local --depth=-1 ostree-srv/exampleos/build-repo
timeout: the monitored command dumped core
25cec76c4e4a5497afa511c17a3ef65d3989d44a0194da61373460ec52b1c448
ERROR: tests/test-pull-many.sh - missing test plan
ERROR: tests/test-pull-many.sh - exited with status 124
```

E.g.: https://github.com/ostreedev/ostree/pull/746 https://github.com/ostreedev/ostree/pull/747

**Comment by cgwalters** [comment]
[This one](https://s3.amazonaws.com/aos-ci/ghprb/ostreedev/ostree/90da5d90b724960cfc514a23b4f7315ab0722c2f.3.1490202187478194991/artifacts/test-suite.log) looks like `fsck` dumped core, though I'm not entirely sure.

If that's the case though it means there's something going wrong in the core.

**Comment by cgwalters** [comment]
Haven't seen this in quite a while.
