### ISSUE TITLE
unlock: Fix SELinux labeling

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#762]
```
ls -aldZ /usr
drwxr-xr-x. root root unconfined_u:object_r:tmp_t:s0   /usr
```

I think we need to get the label of `/usr` and then pass `context=system_u:object_r:usr_t:s0` to `mount()`.

**Comment by rhatdan** [comment]
https://github.com/ostreedev/ostree/pull/763

**Comment by rhatdan** [comment]
I think my patch will fix this, but untested.
