### ISSUE TITLE
setting up an ostree deployment on alpine 🏔

### ISSUE THREAD

**Issue by untoreh** [ostreedev/ostree#772]
building the tree with this
```bash
#!/bin/bash

cd /srv/tree

rm -rf ./*
cp -a /usr .
cp -a /etc .
cat <<EOF > usr/etc/init.d/vardirs
#!/sbin/openrc-run

mkdir -m 0755 -p /var/mnt /var/opt /var/roothome /sysroot/ostree /sysroot/tmp
ln -s /var/home /sysroot/home
EOF

ln -s /etc/init.d/vardirs usr/etc/runlevels/boot/

mkdir -p var/home var/mnt var/opt var/roothome sysroot/ostree sysroot/tmp
ln -s usr/bin bin
ln -s usr/sbin sbin
ln -s usr/lib lib
ln -s usr/lib64 lib64
ln -s var/home home
ln -s var/roothome root
ln -s var/mnt mnt
ln -s var/opt opt
ln -s sysroot/ostree ostree
ln -s sysroot/tmp tmp

## BOOT
mkdir -p boot
cp -a /boot/vmlinuz-virtgrsec boot/
cp -a /boot/initramfs-virtgrsec boot/
knsum=`sha256sum boot/vmlinuz-virtgrsec | cut -f 1 -d ' '`
fssum=`sha256sum boot/initramfs-virtgrsec | cut -f 1 -d ' '`
mv boot/vmlinuz-virtgrsec boot/vmlinuz-virtgrsec-${knsum}
mv boot/initramfs-virtgrsec boot/initramfs-virtgrsec-${knsum}${fssum}

cd /srv
ostree --repo=pine commit -s $(date)'-build' -b trunk --tree=dir=tree
ostree summary -u --repo=pine

```

booting from ram on the machine for deployment, trying with this
```bash
#!/bin/bash

umount /os/boot /os/etc /os/usr /os/sysroot /os/dev /os/sys /os/proc /os &>/dev/null
mkfs.ext4 -F /dev/vda1
mkfs.ext4 -F /dev/vda3
mkswap /dev/vda2

mkdir -p /os
mount /dev/vda3 /os
mkdir -p /os/boot
mount /dev/vda1 /os/boot
mkdir -p /os/sysroot
mount /dev/vda3 /os/sysroot
ostree admin init-fs /os
ostree admin os-init --sysroot=/os pine

ostree --repo=/os/ostree/repo remote add one http://192.168.100.216:39767 trunk --no-gpg-verify
ostree --repo=/os/ostree/repo pull one
ostree admin deploy --sysroot=/os --os=pine trunk

mkdir -p /os/usr
mkdir -p /os/etc
mount --bind  `find /os/ostree/deploy/pine/deploy/ -maxdepth 1 | grep "\.0$"`/usr /os/usr 
mount --bind  `find /os/ostree/deploy/pine/deploy/ -maxdepth 1 | grep "\.0$"`/etc /os/etc
cd /os
mkdir -p var/home var/mnt var/opt var/roothome sysroot/ostree sysroot/tmp
ln -s usr/bin bin
ln -s usr/sbin sbin
ln -s usr/lib lib
ln -s usr/lib64 lib64
ln -s var/home home
ln -s var/roothome root
ln -s var/mnt mnt
ln -s var/opt opt
ln -s sysroot/ostree ostree
ln -s sysroot/tmp tmp
mount --bind /dev/ /os/dev
mount --bind /sys  /os/sys
mount --bind /proc /os/proc
chroot .
grub-install /dev/vda
grub-mkconfig -o /boot/grub/grub.cfg
reboot
```
getting kernel panic
```
unable to mount root fs on unknown-block(0,0)
```
grub ostree part
```
### BEGIN /etc/grub.d/15_ostree ###
menuentry 'Alpine Linux v3.5 (ostree:0)' --class gnu-linux --class gnu --class os --unrestricted 'ostree-0-32dc2301-5da2-4e0a-86e8-d0e16567d4cd' {
load_video
set gfxpayload=keep
insmod gzio
insmod part_msdos
insmod ext2
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root  32dc2301-5da2-4e0a-86e8-d0e16567d4cd
else
  search --no-floppy --fs-uuid --set=root 32dc2301-5da2-4e0a-86e8-d0e16567d4cd
fi
linux16 /ostree/pine-28ea2db5214490ed1453586c85d5dbac36d92d8ac2b35f2c6f819dc7d7275278/vmlinuz-virtgrsec ostree=/ostree/boot.1/pine/28ea2db5214490ed1453586c85d5dbac36d92d8ac2b35f2c6f819dc7d7275278/0
}
### END /etc/grub.d/15_ostree ###

```

```
localhost:/# blkid
/dev/loop0: TYPE="squashfs"
/dev/sr0: UUID="2017-03-02-20-19-30-00" LABEL="alpine-virt 3.5.2 x86_64" TYPE="iso9660" PTUUID="43f816a2" PTTYPE="dos"
/dev/vda1: UUID="32dc2301-5da2-4e0a-86e8-d0e16567d4cd" TYPE="ext4" PARTUUID="1c73f266-01"
/dev/vda2: UUID="2820610d-9d46-42f6-a70d-ba0812b2a4b7" TYPE="swap" PARTUUID="1c73f266-02"
/dev/vda3: UUID="20161098-bccf-4942-93c8-a052c6fbccd3" TYPE="ext4" PARTUUID="1c73f266-03"

```

**Comment by cgwalters** [comment]
You need to specify the root partition in the kernel arguments.  Instead of:
```
ostree admin deploy --sysroot=/os --os=pine trunk
```

You need to do e.g.:
```
ostree admin deploy --sysroot=/os --os=pine trunk --karg=root=UUID=20161098-bccf-4942-93c8-a052c6fbccd3
```

You may want other kernel arguments too of course, but you need a root.

**Comment by cgwalters** [comment]
One example is how for Fedora/CentOS we use [Anaconda](https://github.com/rhinstaller/anaconda/blob/0c2655d7f5d371c9b172b4ffe73420bb34eb4644/pyanaconda/payload/rpmostreepayload.py#L330) - this example is a bit more involved since we do the deployment, perform some postprocessing there, then change the kernel arguments after.

**Comment by untoreh** [comment]
I was generating the checksum wrongly, so I fixed that and the initramfs gets copied over to the boot directory and solved the problem.

about the init changes instead,
- the ro bind mount on /usr , plain `/usr` in the ramfs or `/sysroot/usr` or /sysroot$ostree/usr` ?
- the bind mount to /sysroot like `mount --bind /sysroot /sysroot$ostree/sysroot` ?
- the move like...?
```
mount --bind /sysroot$ostree /sysroot$ostree
mount --move /sysroot$ostree /sysroot
```

**Comment by cgwalters** [comment]
ostree itself will try to run `grub2-mkconfig` in a chroot (and at some point in the future probably [bwrap](https://github.com/projectatomic/bubblewrap) as long as it detects grub2 is in use; something like this (not tested):

```
mkdir sysroot/boot/loader.0
ln -sr sysroot/boot/{loader.0,loader}
touch sysroot/boot/loader/grub2.cfg
ostree admin deploy --sysroot=/os --os=pine trunk
```

See also [this bit in the tests](https://github.com/ostreedev/ostree/blob/master/tests/libtest.sh#L417).

**Comment by untoreh** [comment]
that does not seem to work, if it did it should also work after a commit/pull/deploy cycle having already grub in place but it doesn't update the grub config

**Comment by untoreh** [comment]
it does not even trigger when switching deployments on the client...

**Comment by cgwalters** [comment]
Is this an EFI or BIOS system?  What's likely going wrong is that ostree's grub2 code is failing to find the bootloader config.  See `_ostree_bootloader_grub2_query()` in the source.

**Comment by untoreh** [comment]
so the path must be grub2, and the cfg name grub.cfg (without the 2). The folder name can't be chosen upon `grub-install` I guess it's a compile time option so a grub->grub2 has to be used
The `/loader*` folders are supposed to pass the deployments assertion? but it still fails
```
OSTree:ERROR:src/libostree/ostree-bootloader-grub2.c:367:_ostree_bootloader_grub2_write_config: assertion failed (deployments->len > 0): (0 > 0)
```
Also ostree calls `grub2-mkconfig` so another link in the binaries is needed to `grub-mkconfig`. 
And the path that triggers the mkconfig is `boot/grub2/grub.cfg` even though ostree stores the file in `boot/loader/grub.cfg`

**Comment by rkraneis** [comment]
Is https://bugzilla.redhat.com/show_bug.cgi?id=1483818 related? Is more input needed or help in reproducing the issue?

**Comment by GrabbenD** [comment]
Did you ever figure it out @untoreh?
I'm interested in trying this!
