### ISSUE TITLE
Latest ostree broke flatpak

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#798]
The 2017.4 release broke flatpak: https://github.com/flatpak/flatpak/issues/710

It seems bare-user symlink checkouts are using hardlinks when they should not.
I bisected this to 
https://github.com/ostreedev/ostree/commit/d3385a3014e173299094133d644763e34e5ecd52

**Comment by cgwalters** [comment]
Urg.  PR in https://github.com/ostreedev/ostree/pull/799
