### ISSUE TITLE
Partial pull --mirror overwrites summary

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#846]
If i mirror a specific ref (or sets of refs) and the source repo has a summary file, then the target summary file is replaced. I don't really think this is the right behaviour unless you're mirroring the entire source repo.

**Comment by cgwalters** [comment]
Yeah, agree we shouldn't do this.  In the short term one can work around this by regenerating the summary after, though it does introduce a race if clients are going to pull from it directly.

**Comment by alexlarsson** [comment]
I'm hitting this when mirroring some of the gnome runtimes into the flathub repo. Will look at it.
