### ISSUE TITLE
ostree defaults to non-upstream gpgme pkg-config files (but supports gpgme m4)

### ISSUE THREAD

**Issue by ikeydoherty** [ostreedev/ostree#851]
The configure routine for ostree looks for `gpgme-pthread`.
Many discussions have happened upstream, and they have no interest in adopting pkgconfig. For the most recent discussion on this that I can find, please see: https://dev.gnupg.org/T1329

Note that `gnome-continuous` has this available due to Yocto patching gpgme for non-standard behaviour (as they destroy all `*-config` binaries to replace with what they deem as standard pkgconfigs, even when not expected)

Outside of Yocto I'm not currently aware of distros using this, so I assume testing distros are being patched to support this.

Can we revert the pkg-config check to something that isn't Yocto-specific, please? :)

https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-support/gpgme/gpgme/pkgconfig.patch

I'd rather not jank my distro up with non-standard points-of-philosophy patches :P

**Comment by cgwalters** [comment]
I obviously disagree with GPG upstream, but anyways...don't we do both?  In git master today we have:

```
PKG_CHECK_MODULES(OT_DEP_GPGME, gpgme-pthread >= $LIBGPGME_DEPENDENCY, have_gpgme=yes, [
    m4_ifdef([AM_PATH_GPGME_PTHREAD], [
       AM_PATH_GPGME_PTHREAD($LIBGPGME_DEPENDENCY, have_gpgme=yes, have_gpgme=no)
    ],[ have_gpgme=no ])
])
```

So presumably you're hitting `AM_PATH_GPGME_PTHREAD` not being defined or something?  How exactly are you building? 

Basically if you have a not-ugly patch you've tested I have no problem carrying it but...I'm tempted to put the pkg-config patch in Fedora at least I have to say.

**Comment by ikeydoherty** [comment]
Eh. Well. You got me there. I have no non ugly methodology. I hadn't considered this third option of "make it standard, without upstream". If Fedora adopts the pkgconfig patch then admittedly I'd feel less dirty about doing so too

**Comment by cgwalters** [comment]
Are you not able to build libostree today?  If so, what's the error specifically?  

Or is this just a philosophical issue you wanted to bring up after reading the source to `configure.ac`?

**Comment by ikeydoherty** [comment]
Mostly philosophical as one of our contributors raised the issue on IRC. You can untag bug and make it an opinion piece, that's fine with me, it mostly is. :) I also wanted to get a feel for how the rest of the distro world is treating the gpgme... situation.. If the ayes have it in terms of adopting the pkgconfig patch over what upstream says, then I'd rather join in.

**Comment by cgwalters** [comment]
Closing this one since while I'd like to improve the situation, I think what we're doing in libostree is fine - we're supporting both cases.   Please reopen if there are build integration issues or the like.

**Comment by ikeydoherty** [comment]
Nah that's fine, cheers. Lemme know if you do merge that patch into Fedora though, certainly curious.
