### ISSUE TITLE
ostree pull not working as expected. maybe.

### ISSUE THREAD

**Issue by bcl** [ostreedev/ostree#906]
I'm not sure if I'm misunderstanding something, or if there is a bug, or something else.
We have an ostree repo that we import (using our own tool) rpm contents into. It has a single ref, master, and appears to be working correctly. I use `python3 -m http.server` on the repo to serve it to local users.
I do the following to mirror it (bdcs-2 is the mirror, bdcs-1 is the original repo):
```
ostree --repo=bdcs-2 init --mode=archive-z2
ostree --repo=bdcs-2 remote --no-gpg-verify add upstream http://lister.brianlane.com:8000/
ostree --repo=bdcs-2 pull --depth=-1 --mirror upstream
```
(Note this is using patched ostree to work around the recursion problem)
This works, I can use our tools to export files from the mirrored repo at this point.

Next I want to try adding more content to the original repo, using our tool, and then pull the results to the mirror. I do the following after running our import, and confirm that the log shows the new commits.
```
ostree --repo=bdcs-1 summary -u
ostree --repo=bdcs-2 pull upstream master
```
Which doesn't pull in the new commits. I've tried also using `--mirror` again and `--depth=-1` with no success. I'm fairly sure I'm missing something, but don't know what :)

Any help would be appreciated, thanks!

**Comment by jlebon** [comment]
Hmm, I can't reproduce this. Is this on v2017.6 + the recursion patch, or git master?

> I've tried also using --mirror again and --depth=-1 with no success.

Yeah, it should work with `--mirror` again. (It will work as well of course without it, though the commit will be under the `upstream:master` ref, rather than just `master`).

**Comment by bcl** [comment]
Ok, I may have a better idea of what's going on.
After the initial mirroring the only ref is `master` and the summary and log master match, both pointing to the last commit.

If I add another commit to `bdcs-1` and run `summary -u` on it, and then do:
`ostree --repo=bdcs-2 pull --verbose upstream master`

 * There are now 2 refs, `master` and `upstream:master`
 * `log master` doesn't have the new commit.
 * `log upstream:master` has the new commit.
 * `summary -v` only shows master, pointing to the last master commit.

Running `summary -u` does not change the `master` ref, and also does not add the `upstream:master` ref. Is that a bug?

The way our import/export works right now is that it always uses a branch named `master` so it won't find the new commits on `upstream:master`. Is there a way to merge those onto the `bdcs-2` master branch?
Attaching the verbose log of the pull FWIW. It doesn't look very useful without the actual repo.

[bdcs-2-pull.txt](https://github.com/ostreedev/ostree/files/1055838/bdcs-2-pull.txt)

**Comment by cgwalters** [comment]
This is one of those things where ostree diverges a bit from git.    If you do a `pull --mirror,` you currently need to specify `--mirror` *every time*.

I'd be the first to say this *is* confusing and has bitten me in the past too.

There's another important factor going on here though - I would avoid naming refs in ostree generic things like `master`.  They're intended to be globally unique.

Somewhat unlike git, there are use cases for putting "semantically unrelated" content in the same repository.  For example, one could have all of `rhel-atomic-host/7/x86_64/standard`, `fedora/26/x86_64/atomic-host` and `fedora/27/x86_64/atomic-host` refs in the same repo.  The advantage of this is that they share storage.

Anyways, does it fix things if you `ostree --repo=bdcs-2 refs --delete master` and always use `pull --mirror`?

**Comment by bcl** [comment]
That left me with `upstream:master` and no new master so I restarted from scratch.
Our use is a bit unusual, we're using it as a data store, not splitting things into branches (we have an external metadata.db that stores all the file attrs, etc.).

I tried using `--mirror` with a few more imports, and it looks like the default is to only pull the most recent commit, and it loses the history it had with the previous `--mirror`. Does that mean I need to do a `--depth=-1` each time? And does that mean it is re-pulling everything every time?

I guess a better way to put this is: Can we use ostree as a data store, and do incremental updates from a remote repo to a local repo? Without pulling the whole thing each time and while preserving the original branch names? If we have to deal with `remote:branch` I'm sure we can add that, but it makes things inconsistent between the local repo and one that has been pulled.

Thanks!

**Comment by cgwalters** [comment]
You do need to specify `--depth=-1` each time, but `ostree pull` will only download commits (and in general, objects) it doesn't have.  

Definitely - supporting this use case is also crucial for efficiently mirroring ostree-as-host (e.g. Atomic Host) or ostree-as-container (e.g. flatpak) content.

**Comment by bcl** [comment]
Thanks, I think I have this sorted out now.
