### ISSUE TITLE
autocompletion

### ISSUE THREAD

**Issue by albfan** [ostreedev/ostree#933]
I must confess I understand the "git idea" under ostree but in general all seems like black magic

Provide autocompletion will help to demistify it (as people can list contents and understand what's under the hood)

For example I recently learn how to use `ls` or `cat` command after realize that it list contents under repo/refs, like (for flatpak)

```
$ ostree --repo=/var/lib/flatpak/repo remote list
gnome
gnome-apps-nightly
gnome-nightly

$ ostree --repo=/var/lib/flatpak/repo remote show-url gnome-nightly
https://sdk.gnome.org/nightly/repo/

$ ls -1 /var/lib/flatpak/repo/refs/remotes/gnome-nightly/runtime/
org.gnome.Platform
org.gnome.Platform.Locale
org.gnome.Sdk
org.gnome.Sdk.Debug
org.gnome.Sdk.Locale
```

So you can complete this useful commands with ease:

- Contents of a repo:
    ```
    $ ostree --repo=/var/lib/flatpak/repo ls -R gnome-nightly/runtime/org.gnome.Sdk.Debug/ | less
    ```

- Contents of a file in a repo:
    ```
    $ ostree --repo=/var/lib/flatpak/repo cat gnome-nightly/runtime/org.gnome.Sdk.Debug/x86_64/master /files/source/glib/glib/gvariant-parser.c | less
    ```

Do you find useful an autocompletion script for bash-completion, is there any ongoing effort for that? I can provide a first implementation if none exist yet

**Comment by alexlarsson** [comment]
You are aware that the checked out versions of all the apps are regular directories, right?
`/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.24/active/files/` has the gnome 3.24 platform files.

**Comment by albfan** [comment]
@alexlarsson Have no idea. Good to know! 

That was only examples of long commands that can be autocompleted, to show how autocompletion would help to move around

autocompletion makes sense then?

**Comment by cgwalters** [comment]
Yep, would be happy to have completions!

**Comment by albfan** [comment]
Great. Let's work on it

**Comment by cgwalters** [comment]
This was done in https://github.com/ostreedev/ostree/pull/1077 :confetti_ball:
