### ISSUE TITLE
Please clarify: does libostree require systemd?

### ISSUE THREAD

**Issue by williamh** [ostreedev/ostree#934]
Your releases page seems to imply that the current release requires systemd, but I don't see any statement to that affect in the README.md.
Can you please clarify?

Thanks much. :-)

**Comment by cgwalters** [comment]
We currently don't hard require systemd, and there aren't any immediate plans to do so.  The change made in https://github.com/ostreedev/ostree/pull/859 increased integration with systemd, but I tried to keep the non-systemd code paths functional.  But I didn't test the non-systemd path.  If it's broken, please do report it, and I may spend some time fixing it.  Would definitely review patches.

Does that answer the question?

**Comment by lws-team** [comment]
It seemed to answer the question to me.

Since you have 77 open issues right now and this guy didn't care to reply with a followup in 9 weeks, or close it despite he opened it, I would think you could close it :-)
