### ISSUE TITLE
pkgconfig(ostree-1) = 2017.3	while beeing version 2017.6

### ISSUE THREAD

**Issue by zaitor** [ostreedev/ostree#938]
Building libostree 2017.6, I end up with a package that provides an old pkgconfig symbol

Provides

Symbol
libostree-devel = 2017.6-12.1	
libostree-devel(x86-32) = 2...	
ostree-devel = 2017.6	
pkgconfig(ostree-1) = 2017.3
libostree-devel = 2017.6-12.1

**Comment by cgwalters** [comment]
What package system?  RPM?  What distribution?  How did you do the build?

I don't know what's going on there, but AFAICS our `.pc` file gets correctly substituted with the version upstream.   Are you carrying any patches?

**Comment by jlebon** [comment]
Strange. Using the latest F27 build at least I see:

```
$ curl -sLO https://kojipkgs.fedoraproject.org//packages/ostree/2017.6/4.fc27/x86_64/ostree-devel-2017.6-4.fc27.x86_64.rpm
$ rpm -q --provides -p ostree-devel-2017.6-4.fc27.x86_64.rpm | grep pkgconfig
pkgconfig(ostree-1) = 2017.6
```

**Comment by zaitor** [comment]
Ha, indeed my bad, I cocked it up when checking out from git in our buildsystem.

**Comment by zaitor** [comment]
<param name="versionformat">2017.6</param>
     <param name="filename">libostree</param>
     <param name="changesgenerate">enable</param>
-    <param name="revision">refs/tags/v2017.3</param>
+    <param name="revision">refs/tags/v2017.6</param>
   </service>
   <service name="recompress" mode="disabled">
     <param name="file">*.tar</param>

I missed the rather important tag part, so I set the version to be .6, but the tarball was infact still .3
