### ISSUE TITLE
summary: Support --omit-commit to help with atomicity for clients

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#941]
There is a problem with flatpak build-update-repo and deltas. If you pass --generate-static-deltas this will create new from-scratch and from-last-version deltas for all refs. It will also remove all deltas for earlier versions.

The problem is when to remove the old deltas wrt when to update the summary. If we delete the deltas before updating the summary, then the old active summary file will point to the files being deleted, but if we keep the deltas around until we created the new summary file, then the new summary will contain the old deltas that were deleted, because summary update uses readdir() to figure out which deltas there are.

It would be nice if I could pass in a list of deltas to add, or to remove or something, so that the summary doesn't contain the deltas I'm planning to remove.

**Comment by cgwalters** [comment]
Does `build-update-repo` drop the older version?  If so, I don't think there's any way to avoid races, like where a client fetches the old summary and is in progress of downloading the old version's deltaparts.  Basically you need to keep (at least) 2 versions, and only prune N-2, right?

**Comment by alexlarsson** [comment]
I fixed this in flatpak: https://github.com/flatpak/flatpak/commit/326507602c81f64347370ddd61d7c3ce39f93666
