### ISSUE TITLE
lower flatpak's xa.ref to ostree

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#983]
Per [discussion on the list](https://mail.gnome.org/archives/ostree-list/2017-June/msg00034.html).  Strawman: call it `ostree.ref-binding`.  Check this in `ostree_repo_pull()`.

Do we need to make this configurable on the client side to ignore it?  I'm not sure if there's a case.

**Comment by cgwalters** [comment]
@alexlarsson @pwithnall Make sense?

**Comment by pwithnall** [comment]
This is PR #972, right?

**Comment by alexlarsson** [comment]
I don't see why you would need it to ever be optional. If you need a different name, create a different commit (with same content).

**Comment by cgwalters** [comment]
@pwithnall Hmm...I think that require collections to be set up, right?  Which I think we¹ will do obviously after things land and settle, but I was thinking of simply lowering the flatpak check as is, since it doesn't require collections as it is today.

OK, I looked now and see that it is doing both.  Maybe it'd be cleaner if we had two properties:

 - ostree.collection-binding
 - ostree.ref-binding

?

¹ we=Fedora Atomic etc.

**Comment by cgwalters** [comment]
(And actually per list discussion, let's make `ostree.ref-binding` have GVariant type `as`)

**Comment by pwithnall** [comment]
> OK, I looked now and see that it is doing both. Maybe it'd be cleaner if we had two properties:
> 
>  * ostree.collection-binding
>  * ostree.ref-binding

That works. An alternative would be to move the collection ID stuff (but *not* the `OstreeRepoFinder` stuff) out from behind `--enable-experimental-api` and make it unconditional. It might be a bit early for that yet. Depends whether you think the concepts are stable enough to be set in stone, or whether you’d like some deployment experience with them first.

**Comment by cgwalters** [comment]
Done in https://github.com/ostreedev/ostree/pull/972
