### ISSUE TITLE
Delta update fails with EPERM (O_TMPFILE + old glibc?)

### ISSUE THREAD

**Issue by alexlarsson** [ostreedev/ostree#991]
In flathub i got: https://flathub.org/builds/#/builders/4/builds/446/steps/9/logs/stdio
```
Updating: org.gnome.Platform/x86_64/3.24 from flathub
Error: Failed to update org.gnome.Platform/x86_64/3.24: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote flathub: opcode open-splice-and-close: opcode open-splice-and-close: Writing object 579128a0d09b4fad3ed5156eef81e495e2da0d145e26002199553c956b5954be.file: Unable to set xattr: Permission denied
```
Which is a per-user repo that is type bare-user. Ostree version is 2017.7.
Updating with --no-static-deltas worked.

**Comment by cgwalters** [comment]
The `Unable to set xattr` string comes from `write_file_metadata_to_xattr()` - i.e. we failed to write the `bare-user` `user.ostreemeta` xattr.

Did you expect to have a `bare-user-only` repo?  

Although I can't imagine though why `--no-static-deltas` would work.  The code paths are really the same between the two.

**Comment by cgwalters** [comment]
I'm going to operate on the theory here that what happened is when you did a pull manually, you actually used the system repo instead of the per-user one or something like that.

This PR should make things a lot more clear: https://github.com/ostreedev/ostree/pull/993

**Comment by cgwalters** [comment]
That build log also has an assertion error, urg.

**Comment by alexlarsson** [comment]
I did no expect a bare-user-only pull. But I also did not expect an xattr error, because it was updating the repo in a location that definately supported xattrs, because we've installed a lot of things there before, and the update wih --non-static-deltas worked.

I don't know what could have caused this, and since this was the live flathub build machine i no longer have this state. 

One guess is that some codepath writes a file in /tmp rather than the ostree repo tmp dir.

**Comment by cgwalters** [comment]
Is it continuing to happen?  Offhand...oh wait, I see a potential issue; in the delta path it looks like we're not doing a `fchmod()` before we try to set the xattr.  That's possibly why you were seeing `EPERM`.  This isn't an issue with `EOPNOTSUPP` as we were thinking at first.

**Comment by cgwalters** [comment]
Hmmm...I seem to recall something with `O_TMPFILE` files being mode `0`...there's some comments in the source to that effect, but looking at this more, that's not the case here with `fedora-27:fedora/rawhide/x86_64/workstation`, `Version: 27.45 (2017-07-03 11:27:28)` and `glibc-2.25.90-15.fc27.x86_64`.

I mention the glibc version since I found this bug: https://sourceware.org/bugzilla/show_bug.cgi?id=17523

I filed https://github.com/GNOME/libglnx/pull/60

What's the host system for this builder?

**Comment by cgwalters** [comment]
And yeah, pairing this with the knowledge that in the delta path we were missing a `fchmod` before trying to set the xattr -  if this is an older system with that glibc bug, it would explain the symptoms.

**Comment by alexlarsson** [comment]
Don't have the exact version here, but it's a centos7 install.

**Comment by cgwalters** [comment]
I believe https://github.com/GNOME/libglnx/pull/60 was the cause here, and that's in v2017.9.
